### ISSUE TITLE
Pass raw IP to ThreadLocalServerAndClientSpanState

### ISSUE THREAD

**Issue by adriancole** [openzipkin/brave#100]
ThreadLocalServerAndClientSpanState requires you use an `InetAddress` class. In many cloud environments, you can lookup your public ip from an environment variable or a metadata service. I think it would be nice if we had a constructor that either took the int form or byte[] form of an IP, avoiding ns lookup.

**Comment by henrikno** [comment]
ThreadLocalServerAndClientSpanState doens't do any lookups, but the Brave builder does call
InetAddressUtilities.getLocalHostLANAddress() which does do a lookup.
InetAddress is only a "data" object for an IP address, unless you invoke one of the lookup methods.
`Brave.Builder` should have a constructor which does not do lookups.

Another problem I see is that it converts the IP address to an int, which means it only supports IPv4. Seems like that is a limitation in Zipkin.

**Comment by adriancole** [comment]
The problem is that the only parameter is an InetAddress, which in many
cases leads a user down paths where they have to do complicated things to
prevent it from doing NS lookups.

**Comment by adriancole** [comment]
IOTW InetAddress makes you do needless conversion, which usually interferes
and has poor relevance for cloud environments, where in many cases your
public ip/port is not readable from the host except via property. The idea
of using something like InetAddress is for type safety, when its only
purpose is carrying an ip address. In this case, this is a cure worse than
the disease. Brave should allow a user to specify an IP without dancing or
monkeying, IOTW.

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-instance-addressing.html#concepts-public-addresses

Regardless, I agree that ipv6 is a limitation of brave.

**Comment by adriancole** [comment]
>
>
> Regardless, I agree that ipv6 is a limitation of brave.
>
sorry I meant zipkin! anyway even when we have ipv6 you wouldn't conflate
them in the same endpoint.

**Comment by henrikno** [comment]
What's wrong with InetAddress.getByAddress(byte[])? Just curious. Is there an easier way of representing a IPv4/IPv6 address (byte[] seems so... raw)?

**Comment by adriancole** [comment]
because zipkin only supports ipv4, for example. the type InetAddress is a lie. I'd rather pass an int or byte[] as that's at least not lying about what it is capable of. In general lying types feel worse to me, and also if you look at the constructor, all it is doing is coercing to an int. Having an alternate constructor that removes the complexity of how to safely use the InetAddress stuff would be of help imho.

**Comment by adriancole** [comment]
I mean this isn't a user-level interface! This is literally an internal detail of the system. People should know what it does, and InetAddress *usually* implies name lookup and a possibility of maybe ipv4 etc, right? That reduces the surface area to people who should already know zipkin only supports ipv4, and shouldn't confuse people who don't know that yet (for example by docs on an alternate constructor that doesn't try to wash things through InetAddress class)

**Comment by adriancole** [comment]
PS I agree with what you said, that `InetAddress.getByAddress(byte[])` will
avoid lookup. Just it is a shame we cannot pass the data that brave
actually uses.

**Comment by adriancole** [comment]
anyway I'll close this. I can see how folks who want brave/zipkin to support ipv6 would want this represented as an abstraction higher than what's transported.
