### ISSUE TITLE
Immutable carrier type Injector

### ISSUE THREAD

**Issue by klass-ivan** [openzipkin/brave#1025]
**Feature:**
Injector interface should return same type value, not void

**Rational**
Injector design relies on mutability. It's impossible to use instrumentation interfaces with immutable structures

**Example Scenario**
Tracing middleware for http application, where headers are immutable library object

**Comment by jeqo** [comment]
Hi @klass-ivan thanks for bringing this up.

In the example that you provide, how would request/response headers be updated then? recreating the whole payload? Could you share a concrete example (eg. gist) where you require `injector` to return a new value?

**Comment by adriancole** [comment]
I totally appreciate your concern about mutability, and we encountered that also. However, this design concern is no longer relevant, as we found it is not a good idea to use raw types in injectors. It is a deprecated pattern, in other words. It is better to make a wrapper as that serves more goals.

https://github.com/openzipkin/brave/releases/tag/5.7.0 (note current is 5.8)
https://github.com/openzipkin/brave/blob/master/instrumentation/http/RATIONALE.md#httpclientrequest-httpclientresponse-httpserverrequest-and-httpserverresponse-types

Here's an example of a wrapper that works with mutable headers.

https://github.com/openzipkin/brave/blob/master/instrumentation/okhttp3/src/main/java/brave/okhttp3/TracingInterceptor.java#L79

Feel free to jump on https://gitter.im/openzipkin/zipkin for more questions!
