### ISSUE TITLE
Tracing stream components catch RuntimeException | Error 

### ISSUE THREAD

**Issue by jorgheymans** [openzipkin/brave#1029]
Lombok's `@SneakyThrows` defeats this because it allows you to throw checked exceptions. Maybe `Throwable` would be better here ?

**Comment by jeqo** [comment]
@jorgheymans sorry for the late reply. Currently (before #1030), instrumentation handles unchecked exceptions, as checked ones would be up to the user to instrument.

Even we something as `SneakyThrows`, user is responsible to instrument it, isn't it?

Just trying to check if this is a common issue, as other instrumentations follow the same pattern: 

https://github.com/openzipkin/brave/blob/6cb5dcfeee46ac7e5ceff31c1cc98d18c4af608c/instrumentation/kafka-clients/src/main/java/brave/kafka/clients/TracingProducer.java#L129-L136

and

https://github.com/openzipkin/brave/blob/c956c400b251100f358cf7556fc6d98dc1e25698/instrumentation/grpc/src/main/java/brave/grpc/TracingServerInterceptor.java#L122-L128

**Comment by jeqo** [comment]
on the other hand, JMS uses throwable:

https://github.com/openzipkin/brave/blob/6cb5dcfeee46ac7e5ceff31c1cc98d18c4af608c/instrumentation/jms/src/main/java/brave/jms/TracingJMSProducer.java#L108-L112

Maybe these are patterns we can define when to use.

**Comment by jorgheymans** [comment]
@jeqo all valid comments. I guess we could just support the exception pattern that the transport we're tracing offers and not bother with lombok tricks (which i admit can be dangerous sometimes) That would be totally valid. I admit i did not give that much thought and had more my usecase in mind (stream transformers dealing with javax.crypto so basically lots of checked exceptions). Maybe let the PR sink for a bit, while we think if this should be aligned in other instrumentations as well.

**Comment by jeqo** [comment]
cc @anuraaga

**Comment by anuraaga** [comment]
I agree that it's not a good idea for code to circumvent exceptions where possible, using `@SneakyThrows` or `throwUnsafely`. It's not that hard to wrap callbacks with something that copies checked exceptions into unchecked ones if we're dealing with a lot of them.

That being said, we can't be sure what user code does - do these callbacks get defined by users or only the instrumented library? Catching `Throwable` around user code to catch errors as much as possible seems like a reasonable pattern to me, but if it's known code it's not as important. On the flip side, I can't think of a downside to catching `Throwable` either aside from the extra noise of `propagateIfFatal`.

**Comment by jorgheymans** [comment]
Another usecase perhaps is aop, where an Around advice typically throws `Throwable`. Not that i would recommend anyone applying an advice around a stream transformer, but as @anuraaga says we can't be sure what user code is going to do. More food for thought :)

**Comment by jeqo** [comment]
Thanks for you feedback! I'm more confident about changes in #1030. We can keep promoting catching unchecked exceptions as we do in https://github.com/openzipkin/brave/tree/master/brave#in-process-tracing; and catch `Throwable` + `propagateIfFatal` in instrumentation internals.
