### ISSUE TITLE
I am having a problem  because the correlationId not propagated through kafka producer-consumer routes.

### ISSUE THREAD

**Issue by metchegaray33** [openzipkin/brave#1031]
I am having a problem  because the correlationId not propagated through kafka producer-consumer routes.

I update my project with the following version of spring-kafka to   2.2.8.RELEASE and spring-boot 2.1.8.RELEASE.

My producer do the following:

@Async("passDataProducerExecutor")
public void send(PassData passData) {
    String correlationId = requireNonNull(MDC.get(PlatformHeaderNames.TMPS_CORRELATION_ID), "mdc.correlationId");
    log.info("Sending message='{}' to topic='{}'", passData, passDataKafkaTemplate.getDefaultTopic());
    Message<PassData> message = MessageBuilder
            .withPayload(passData)
            .setHeader(PlatformHeaderNames.TMPS_CORRELATION_ID, correlationId)
            .setHeader(KafkaHeaders.MESSAGE_KEY, passData.getSerialNumber())
            .build();
    passDataKafkaTemplate.send(message);
    log.info("message sent");
}

My consumer do the following:

@KafkaListener(topics = "${kafka.passdata.topic}", containerFactory = "passDataKafkaListenerContainerFactory")
public void listen(@Payload List<PassData> entities,
        @Header(KafkaHeaders.RECEIVED_TOPIC) List<String> topics,
        @Header(KafkaHeaders.RECEIVED_PARTITION_ID) List<Integer> partitionIds,
        @Header(KafkaHeaders.OFFSET) List<Long> offsets,
        @Headers MessageHeaders headers) {
    List<String> correlationIds = attemptCorrelationIdHeadersExtraction(headers);
    processBatch(entities, topics, partitionIds, offsets, correlationIds);
}

private List<String> attemptCorrelationIdHeadersExtraction(MessageHeaders headers) {

    List<String> correlationIds = new ArrayList<>();
    try {
        @SuppressWarnings("unchecked")
        List<Map<String, Object>> producerHeaders = ((List<Map<String, Object>>) headers.get(KafkaHeaders.BATCH_CONVERTED_HEADERS));
        producerHeaders.forEach(header -> {
            Object cid = header.get(PlatformHeaderNames.TMPS_CORRELATION_ID);
            if (cid instanceof String) {
                correlationIds.add((String) cid);
            } else if (cid instanceof byte[]) {
                correlationIds.add(new String((byte[]) cid, StandardCharsets.UTF_8));
            } else {
                correlationIds.add(null);
            }
        });
    } catch (Exception e) {
        return null;
    }
    return correlationIds;
}
My problem is that I am receiving the MessageHeaders headers null. Would you please help me or give mi a hints to help me with this issue please?

**Comment by jorgheymans** [comment]
@metchegaray33 this does not look to be related to Zipkin or Brave. Maybe try https://github.com/spring-projects/spring-kafka/ ?

**Comment by jeqo** [comment]
closing this as seems to be not related with Brave. @metchegaray33 if you happen to have more questions, we can follow up on gitter https://gitter.im/openzipkin/zipkin
