### ISSUE TITLE
Why is everything before the last / removed when getting the path and how to include the full path.

### ISSUE THREAD

**Issue by rheda-atlassian** [openzipkin/brave#1035]
I just updated my project from using `brave-instrumentation-http` 5.6.5 -> 5.8.0. We noticed that the zipkin span names for our client requests removed the elements of the url before the last slash and we were wondering what the purpose was behind this and if there was a way we could include the entire url 

current behavior
 "/v1/digest" -> "/digest"

desired behavior
 "/v1/digest" -> "v1/digest"

Thank you very much for your help and for maintaining openzipkin!

**Comment by devinsba** [comment]
Which instrumentation do you use? (ie: servlet, spring mvc, etc..)

Also, is your app configured with a context path or base path of `/v1`. I'm wondering if we lost that part of the path somewhere

**Comment by rheda-atlassian** [comment]
We are using `brave-instrumentation-httpclient` and `brave-instrumentation-servlet`. However, I this behavior occurs when using `brave-instrumentation-httpclient` 5.8.0 and the path is trimmed by the following code https://github.com/openzipkin/brave/blob/master/instrumentation/httpclient/src/main/java/brave/httpclient/TracingProtocolExec.java#L87

Thanks for getting back to me so quickly!

**Comment by rheda-atlassian** [comment]
sorry accidentally closed it

**Comment by devinsba** [comment]
So this only happens in `httpclient` and not in the servlet? Thanks for the pointer

I'm not sure if this was intended or not. I assume it wasn't. cc @anuraaga

**Comment by devinsba** [comment]
Please check https://github.com/openzipkin/brave/compare/issue-1035 and let me know if that matches the behavior and expectation you have. I have to assume you are using `ClientParser` like that test, otherwise the span name would be the HTTP method

**Comment by rheda-atlassian** [comment]
The behavior I have is slightly different. In terms of the test case you have written 

`String uri = "/foo/bar?z=2&yAA=1"`;

the current behavior should make the following assertion true.

`.isEqualTo("get /bar")`

but will fail the following assertion (expectation)

`.isEqualTo("get /foo/bar")`

**Comment by anuraaga** [comment]
Thanks for the report and investigation - @devinsba I can confirm your test works on 5.6.8 and breaks on 5.9.0. There is a clear diffierence between the code for `HttpClient` and `AsyncHttpClient` - there's a lot of duplication too, it might be nice if we can reduce that at some point. Sent a fix
