### ISSUE TITLE
how to create child span in batch processing message system,like rocketmq?

### ISSUE THREAD

**Issue by ni-ze** [openzipkin/brave#1044]
I want to tracing rocketmq with brave-5.7.0. but I found that, in rocketmq consumer side,it is batch processing, which mean it process many messages every time. however, messages may have different span information injected by producer. 

In this case,I can only create ONE child span,   all the  batch messages share this child span?
so, whick api  inbrave-5.7.0 I can use to achieve this.

thx.

**Comment by jeqo** [comment]
@ni-ze thanks for bringing this up! I'll recommend, as the issue template states, to follow up this kind of questions on gitter https://gitter.im/openzipkin/zipkin until we find a bug/feature request to report here. See you there.
