### ISSUE TITLE
Sampled traces lose there extra fields

### ISSUE THREAD

**Issue by juliusse** [openzipkin/brave#1052]
## Describe the Bug
I use sleuth to propagate a custom field through my applications that I am getting with a header from an incoming request.
Config:
```
spring:
  sleuth:
    propagationKeys: request-id
    log:
      slf4j:
        whitelisted-mdc-keys: request-id
```

For sampled traces I lose the field as soon as return from another REST call within my application.

## Steps to Reproduce
- send a request with a custom header (e.g. request-id) to a spring application with sleuth and sampling enabled
- within your application make a REST call to another route (can be in the same application)
- log something when this request returns
=> The log-line does not contain **request-id** anymore

```
trace[00d67be23cac5686,00d67be23cac5686] request-id[someId] : [REQUEST] {method=GET; uri=/get}
trace[00d67be23cac5686,a1900718d54091fc] request-id[someId] : [REQUEST] {method=GET; uri=/get/internal}
trace[00d67be23cac5686,a1900718d54091fc] request-id[someId] : [RESPONSE] {status=200; method=GET; uri=/get/internal} (took 4 ms)
trace[00d67be23cac5686,00d67be23cac5686] request-id[] : Sampled: true
trace[00d67be23cac5686,00d67be23cac5686] request-id[] : [RESPONSE] {status=200; method=GET; uri=/get} (took 75 ms)
```

## Expected Behaviour
Logging should still contain **request-id**
```
trace[00d67be23cac5686,00d67be23cac5686] request-id[someId] : [REQUEST] {method=GET; uri=/get}
trace[00d67be23cac5686,a1900718d54091fc] request-id[someId] : [REQUEST] {method=GET; uri=/get/internal}
trace[00d67be23cac5686,a1900718d54091fc] request-id[someId] : [RESPONSE] {status=200; method=GET; uri=/get/internal} (took 4 ms)
trace[00d67be23cac5686,00d67be23cac5686] request-id[someId] : Sampled: true
trace[00d67be23cac5686,00d67be23cac5686] request-id[someId] : [RESPONSE] {status=200; method=GET; uri=/get} (took 75 ms)
```

**Comment by adriancole** [comment]
I'd recommend starting with sleuth's gitter as the code involved is in that project, not here. you'll likely want to also log the parentId field to make sure that you know the relationships  https://gitter.im/spring-cloud/spring-cloud-sleuth

If at some point this becomes a concrete broken code, we can re-open this with a new title of what code needs to be fixed. good luck
