### ISSUE TITLE
Upgrade Kafka dependencies to 2.4.0

### ISSUE THREAD

**Issue by msmsimondean** [openzipkin/brave#1053]
**Feature**

Update kafka-clients and kafka-streams dependencies to version 2.4.0.

**Rational**

Gain access to new features like https://cwiki.apache.org/confluence/display/KAFKA/KIP-479%3A+Add+StreamJoined+config+object+to+Join and other features in 2.4.x https://www.apache.org/dist/kafka/2.4.0/RELEASE_NOTES.html

**Comment by adriancole** [comment]
we need this satisfied so that we can test it https://github.com/charithe/kafka-junit/issues/46

**Comment by adriancole** [comment]
https://github.com/openzipkin/brave/pull/1063 makes it possible to use the library. Someone with more experience will need to analyze or raise a PR for any additional tracing helpers for kstreams cc @jorgheymans @jeqo @simondean

**Comment by adriancole** [comment]
wait you are simon :) sorry other simon

**Comment by jeqo** [comment]
I can confirm v2.4 doesn't add additional changes to current Kafka Streams tracing interface.

#1063 should be enough to close this issue :)

**Comment by adriancole** [comment]
thanks tons!
