### ISSUE TITLE
Brave not passing spanId to finagle client

### ISSUE THREAD

**Issue by rojanu** [openzipkin/brave#106]
I am trying to use brave-jersey2 implementation with dropwizard [ContactRestServer](https://github.com/rojanu/thrift-swift-finagle-example/blob/master/thrift-swift-finagle-example-rest/src/main/java/com/github/rojanu/contact/rest/ContactRestServer.java)

``` java
SpanCollector spanCollector;
        if(contactRestServerConfig.tracing != null ) {
            spanCollector = new ZipkinSpanCollector(
                    contactRestServerConfig.tracing.server,
                    contactRestServerConfig.tracing.port);
        } else {
            spanCollector = new EmptySpanCollectorImpl();
        }
        int sampleRate = 0;
        try {
            sampleRate = Math.round(1 / contactRestServerConfig.tracing.sampleRate);
        } catch (Exception ignored) {}

        Brave brave = new Brave.Builder("contact-rest")
                .spanCollector(spanCollector)
                .traceFilters(ImmutableList.of((TraceFilter) new FixedSampleRateTraceFilter(sampleRate)))
                .build();

        ServerTracer serverTracer = brave.serverTracer();

        ServerRequestInterceptor requestInterceptor = new ServerRequestInterceptor(serverTracer);
        SpanNameProvider spanNameProvider = new DefaultSpanNameProvider();
        BraveContainerRequestFilter containerRequestFilter = new BraveContainerRequestFilter(requestInterceptor, spanNameProvider);
        environment.jersey().register(containerRequestFilter);

        ServerResponseInterceptor responseInterceptor = new ServerResponseInterceptor(serverTracer);
        BraveContainerResponseFilter containerResponseFilter = new BraveContainerResponseFilter(responseInterceptor);
        environment.jersey().register(containerResponseFilter);
```

And finagle client is used here [ContactResource](https://github.com/rojanu/thrift-swift-finagle-example/blob/master/thrift-swift-finagle-example-rest/src/main/java/com/github/rojanu/contact/rest/resource/ContactResource.java)

``` java
Future<Contact> contactFuture = client.get().create(RestContactRequest.to(restContactRequest));
```

Full code available at https://github.com/rojanu/thrift-swift-finagle-example/tree/contact-service

I get a trace entry on the zipkin server, however rest service(contact-rest) is consuming a finagle service(contact-server), but the call made to contact-server from contact-rest looks like two different requests.  They really should be one request with two spans.

It looks like trace id generated by contact-rest is not passed to contact-server.

What did I miss or am doing wrong?
Thanks

**Comment by kristofa** [comment]
@rojanu Sorry for the late reply! This might need some investigation but I think it is important because brave should be compatible with Finagle. One obvious question: are you configuring your Finagle client/server with `ZipkinTracer`?

**Comment by adriancole** [comment]
Getting a 404 on your example project.

If the downstream call is being made with finagle, you would need to
associate the span id from brave manually. It would be something like
Trace.letId(from brave){ thrift client.execute() }

If you repost your example, I don't mind taking a look.

PS this issue title is a little imprecise, as it looks like dropwizard isnt
working, when the cardinal issue is around brave/finagle. Mind adjusting?

I've had one person ask about dropwizard and this issue might falsely lead
them to believe it doesn't work. For example, dropwizard has nothing to do
with finagle.

**Comment by rojanu** [comment]
@kristofa yes I am using `ZipkinTracer`
```scala
val tracer: Tracer = config.tracingConfig match {
      case tc if tc != null => ZipkinTracer.mk(
        config.tracingConfig.server,
        config.tracingConfig.port,
        DefaultStatsReceiver,
        config.tracingConfig.sampleRate)
      case _ => null
    }
    try {
      var thriftClient: Thrift.Client = Thrift.client
      if (tracer != null) {
        thriftClient = thriftClient.configured(param.Tracer(tracer))
      }
```

**Comment by rojanu** [comment]
@adriancole I updated the title and project URL

**Comment by adriancole** [comment]
In recent Brave, it is now possible to synchronize finagle's context with brave's. Try this out and if you want this to be a formal part of the project, report back or raise a PR
https://github.com/openzipkin/brave/tree/master/brave/src/test/java/brave/features/finagle_context
