### ISSUE TITLE
Multiple request/response parsers

### ISSUE THREAD

**Issue by adriancole** [openzipkin/brave#1069]
We currently have FinishedSpanHandler, which allows tuning of the span data per backend, or even obviating the span reporter. Multiple span handlers can be registered, and they have access to the finished data as well the trace context that represents. From a plugin POV, this works in so far as it supports mechanisms like secondary sampling without coupling them together.

The parsers on the other hand, only operate once. This is simple in so far as it allows centralized control. However, it doesn't allow plugin-like collaboration of data. For example, the [Haystack Blobs](https://github.com/ExpediaDotCom/haystack-blob-example/issues/5#issuecomment-579035878) project could add span tags given a raw http request only, or possibly in combination of that plus a trace context. Doing so would allow "user code" to continue accumulating the data they need, where infrastructure or feature flags related data could accumulate on demand or trigger, independently. The latter would only incur a parsing performance ding when they are hit.

thoughts?

cc @ashishagg @marcingrzejszczak @narayaruna @anuraaga @jeqo

**Comment by anuraaga** [comment]
I probably don't understand the use case very well but it seems domain specific. Is there any abstraction to provide vs just adding tags to `currentSpan`?

**Comment by adriancole** [comment]
accessing the current span isn't a problem, it is accessing it from a portable hook. Imagine if you have servlet, reactor, armeria etc.. you end up with N hooks unless there's a generic one with access to the request object. Right now, the only thing that can see the request object is the sampler and the parser, and in both cases there can be only one.

make sense?

**Comment by adriancole** [comment]
actually technically you can build this, if request based, as a custom propagation plugin. The argument to extract is a request. For example, the blobs thing could be a plugin to [secondary sampling](https://github.com/openzipkin-contrib/zipkin-secondary-sampling) cc @ashishagg

**Comment by adriancole** [comment]
closing from lack of interest.. we can resurrect this later but in the mean time it is possible to do this externally.
