### ISSUE TITLE
Cilent request is not showing in zipkin

### ISSUE THREAD

**Issue by jitenvij1992** [openzipkin/brave#1072]
I have configured brave for trace id and span id in spring web-mvc project. It is showing the server call but it is not showing the call which I am making from spring mvc project to spring boot project because of which trace id is different in spring MVC and spring boot. Please advise.

**Comment by adriancole** [comment]
we don't use issues for question and answer or troubleshooting as it spams the watchers. please join https://gitter.im/openzipkin/zipkin to discuss further
