### ISSUE TITLE
brave is not working with apache httpclient 4.3.X

### ISSUE THREAD

**Issue by jitenvij1992** [openzipkin/brave#1079]
brave/instrumentation/httpclient/src/main/java/brave/httpclient/TracingHttpClientBuilder.java

 HttpHost target = httpRequest.getTarget(); 

HttpRequest in apache doesn't have method getTarget, it is supported since version 4.4.x.

I can't upgrade to 4.4.x.

**Comment by adriancole** [comment]
the module is marked 4.4+, so not a bug. can you give some rationale for why you can't use 4.4.x? Is it due to an internal reason or some open source dependency you can't change?

there are approaches to make this work, just some lifting involved (reflective check like we do in servlet, adding invoker test to ensure 4.3 works). We need to justify the effort as it sticks with the project. Particularly we need to know when we can stop that effort (rationale)

**Comment by jitenvij1992** [comment]
This is some thing internal which we are using and we are forced to use the httpclient version below 4.3.x. Since some of the plugins which we are using can't be upgraded to the higher version of httpclient. 

If you can provide the support for below httpclient 4.3.x, it would be great. If not, can you please tell some approach which we can use to make the work since we are almost done configuring in our application. We are getting the exception while getting the response.

**Comment by jitenvij1992** [comment]
Added example in https://github.com/jitenvij1992/brave-webmvc.git 

Exception: 

javax.servlet.ServletException: org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: org.apache.http.client.methods.HttpRequestWrapper.getTarget()Lorg/apache/http/HttpHost;
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:162)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:494)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:374)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by adriancole** [comment]
It would require making an abstraction that safely looks for the missing method (similar to ServletRuntime), adding a maven invoker test to pin v4.3 (/src/it) and sorting out any test refactorings needed for both versions to pass.

If you are up to that, I could help review, but I don't have the energy personally to do this right now.

**Comment by adriancole** [comment]
https://github.com/openzipkin/brave/issues/431 was the first request for this version

**Comment by adriancole** [comment]
There was a glitch in v5.10 and I have to re-cut anyway. I gave this a shot and we can get this into 5.10.1!

**Comment by adriancole** [comment]
latest fixes this ex https://github.com/openzipkin/brave-webmvc-example/commit/a0669b4eacd7574f68ed90f9f256b6eb9f564cb1
