### ISSUE TITLE
Make tracing more efficient when explicit propagation is in use

### ISSUE THREAD

**Issue by adriancole** [openzipkin/brave#1082]
When creating a client or message producer span, we can use `Tracer.nextSpan(clientRequestSampler(), request)` which handles sampling correctly. However, this relies on the `CurrentTraceContext` component, namely the `.get()` method to look at the current span.

When instrumentation happens via callbacks, this implies having to wrap the whole thing like so:
```java
try (Scope ws = currentTraceContext().maybeScope(ref.parent)){
	Span clientSpan = tracer().nextSpan(clientRequestSampler(), request);
}
```

The scoping operation is expensive, especially in sleuth as it associates logging context. For example, we'd be doing that work only for the single line of code to make and sample the span.

To avoid this overhead, we should allow a third parameter of the parent context.

**Comment by adriancole** [comment]
this also affects apache async http client, from a different call path. you can see this pattern, which is again.. inefficient.

```java
      TraceContext parent = (TraceContext) context.getAttribute(TraceContext.class.getName());
      Span span;
      try (Scope scope = currentTraceContext.maybeScope(parent)) {
        span = handler.handleSend(wrapped);
      }
```

okhttp handles this also by wrapping a chain with `TraceContextInterceptor`.. something we could do easier if we can pass the parent directly.

This doesn't affect armeria or ratpack because both require a custom CurrentTraceContext component which integrates with their context.

**Comment by adriancole** [comment]
technically, the best signature would be at the http abstraction, allowing this:

```java
Span clientSpan = handler().handleSend(request, ref.parent);
```

instead of this:
```java
try (Scope ws = currentTraceContext().maybeScope(ref.parent)) {
	Span clientSpan = handler().handleSend(request);
--snip--
}
```

Just internally, this implies a change to the tracer I think.

**Comment by anuraaga** [comment]
I'm a bit surprised to see the scope around just span creation and not also around a user callback. Didn't look at the code, but if we're scoping twice, once for span creation and again around a callback, is it possible to just combine the code paths?

**Comment by adriancole** [comment]
the scope trying to remove here is about establishing the parent context. Since the parsing callbacks would occur in the client context, we'd need another scope for that. So main thing here is getting rid of the accidental scope which is only to determine if it is a root span or not.

**Comment by anuraaga** [comment]
Ah got it - yeah this seems like a nice tweak.

> The scoping operation is expensive

Also this reminded me of an Armeria discussion

https://github.com/line/armeria/pull/2375

We solved the problem of users using slow scoping code by just getting rid of scope decorators ;) We'll bring them back in a (hopefully) better way if there is demand though.

Armeria does its own log correlation without decorators, but reading directly from the current context.

https://github.com/line/armeria/blob/master/logback/src/main/java/com/linecorp/armeria/common/logback/RequestContextExportingAppender.java

I don't know if this pattern works for sleuth but if log decoration of scopes specifically is something causing performance issues, possibly a point of reference.

**Comment by adriancole** [comment]
it is mainly an issue that you can't guarantee you will have a valid
reactor context. and also if you pick one context you are not picking
another..

it is a good point though and if we could force one.. it could work. main
issue is not all contexts are mutable. this is a hit of a pain in reactor
as you need to change something in a void return callback. a little more
awkward than what is going on in armeria

**Comment by adriancole** [comment]
https://github.com/openzipkin/brave/pull/1083
