### ISSUE TITLE
Impossible to change format of tracing tags in brave 5.9

### ISSUE THREAD

**Issue by konstantinzyubin** [openzipkin/brave#1087]
In brave.spring.rabbit.SpringRabbitTracing one could read 
`    /**
     * @deprecated as of v5.9, this is ignored because single format is default for messaging. Use
     * {@link B3Propagation#newFactoryBuilder()} to change the default.
     */
    @Deprecated public Builder writeB3SingleFormat(boolean writeB3SingleFormat) {
      return this;
    }
`
If we look at brave.propagation.B3Propagation.FactoryBuilder there is method 
`public FactoryBuilder injectFormat(Span.Kind kind, Format format)`
 with 2 parameters. This method has public access type but  Format is package private, so you can't use it outside of same package. 

So as a result I can't change headers format for rabbit producer

**Comment by adriancole** [comment]
the package visibility was fixed in a recent patch, can you verify this is still an issue?

**Comment by adriancole** [comment]
https://github.com/openzipkin/brave/commit/157a4702fccb1d8d85a6658b551d3e5a296920d0#diff-61900271c6385c8d771b1a33e31270e0

**Comment by konstantinzyubin** [comment]
Yes, now it's better. @adriancole thanks for the reply. Hadn't you thought to use properties to set propagation format? It would be much easier for spring users.

**Comment by adriancole** [comment]
@konstantinzyubin we do have a spring-beans project here, and we could add properties to configure this, if it is in use. I'm wondering though if you are using spring-beans or maybe sleuth (boot)? Properties should live in the property manager (ex it is also different for dropwizard etc)..
