### ISSUE TITLE
ui display wrong hierarchy between rpc, `PRODUCER` and `CONSUMER` spans

### ISSUE THREAD

**Issue by KKKIIO** [openzipkin/brave#1094]
## Describe the Bug

zipkin ui (both old ui and lens) display wrong hierarchy between rpc, `PRODUCER` and `CONSUMER` spans.

rpc span:

![rpc](https://user-images.githubusercontent.com/12840157/75043171-9402f380-54fa-11ea-88d0-a588764234f9.png)

produce span(should be child of rpc):

![produce](https://user-images.githubusercontent.com/12840157/75043192-9b2a0180-54fa-11ea-8823-4edd11248f3e.png)

## Steps to Reproduce

Not sure

## Expected Behaviour

the produce span should be child of the rpc span in the ui.

**Comment by adriancole** [comment]
brave 5.10 will fix this https://github.com/openzipkin/brave/pull/1095

**Comment by KKKIIO** [comment]
thank you for the help!
