### ISSUE TITLE
Writing a message into an OracleAQJms Topic throws NPE if a trace context already exists

### ISSUE THREAD

**Issue by nomeez** [openzipkin/brave#1098]
I get a NPE (java.lang.NullPointerException: value of jms.queue == null) when trying to enqueue a message to an Oracle AQJms Topic. It works with an Oracle Queue.
The Exception atually is thrown in MutableSpan.java:266 when we try to tag a span with the destination name.

The issue is caused when trying to read the channelName from the Destination in [MessageParser.java](https://github.com/openzipkin/brave/blob/0f03bcbdb419ac92c51761c377a57e09a0b63d73/instrumentation/jms/src/main/java/brave/jms/MessageParser.java#L46)

[AQjmsDestination implements Queue and Topic](https://docs.oracle.com/cd/B19306_01/server.102/b14291/oracle/jms/AQjmsDestination.html) so in this method we always treat any destination as queue. Which results in null when reading the queueName if it's actually a Topic.

**Comment by adriancole** [comment]
will fix the bug, but the rationale is curious.. if what you are given implements both queue and topic, queue should return...

```java
  @Nullable static String channelKind(@Nullable Destination destination) {
    if (destination instanceof Queue) return "queue";
    if (destination instanceof Topic) return "topic";
    return null;
  }
```

**Comment by adriancole** [comment]
oh sorry I understand now. ps does either of the name methods return for you?

**Comment by adriancole** [comment]
ex do both `getQueueName()` and `getTopicName()` return null?

**Comment by nomeez** [comment]
Hi @adriancole 
One of them always returns null. For a Topic getQueueName() returns null. For a Queue getTopicName() returns null. So maybe the instance of is not even required. I currently do not know any other way other than returning the method that does not return null.

Thanks a lot.

**Comment by adriancole** [comment]
https://github.com/openzipkin/brave/pull/1099 thanks for helping find the bug. excellent work!
