### ISSUE TITLE
Inconsistent library versions reminder.

### ISSUE THREAD

**Issue by calvinhkf** [openzipkin/brave#1107]
Hi. I have implemented a tool to detect library version inconsistencies. Your project have 4 inconsistent libraries and 14 false consistent libraries.

Take javax.annotation:javax.annotation-api for example, this library is declared as version 1.3.2 in instrumentation/grpc, 1.3.1 in instrumentation/jaxrs2 and etc... Such version inconsistencies may cause unnecessary maintenance effort in the long run. For example, if two modules become inter-dependent, library version conflict may happen. It has already become a common issue and hinders development progress. Thus a version harmonization is necessary.

Provided we applied a version harmonization, I calculated the cost it may have to harmonize to all upper versions including an up-to-date one. The cost refers to POM config changes and API invocation changes. Take javax.annotation:javax.annotation-api for example, if we harmonize all the library versions into 1.3.2. The concern is, how much should the project code adapt to the newer library version. We list an effort table to quantify the harmonization cost. 

The effort table shows the overall harmonization cost on APIs. It seems your project have no API invokes on this library, which could be safely upgrade to 1.3.2

|Index|Module|NA(NAC)|NDA(NDAC)|NMA(NMAC)|
|-|-|-|-|-|
|1|instrumentation/grpc|0(0)|0(0)|0(0)|
|2|instrumentation/jaxrs2|0(0)|0(0)|0(0)|

Also we provided another table to show the potential files that may be affected due to library API change, which could help to spot the concerned API usage and rerun the test cases. 

If you are interested, you can have a more complete and detailed report in the attached PDF file.

**Comment by adriancole** [comment]
hi. This is an instrumentation library, which intentionally supports different libraries with different versions. In general, please read issue template before unsolicited issues. This would have mentioned to come to gitter first with questions. bot-like behavior, even if well intention, can distract folks. No harm done, though and good luck!

**Comment by calvinhkf** [comment]
Sorry this unsolicited issue...Currently we do not consider project environments, and library runtimes which false positive may arise. Thanks for your reply~ We will improve the tool in the future.

**Comment by calvinhkf** [comment]
Sorry this unsolicited issue...Currently we do not consider project environments, and library runtimes which false positive may arise. Thanks for your reply~ We will improve the tool in the future.
