### ISSUE TITLE
how to konw brave support which version of zipkin?

### ISSUE THREAD

**Issue by BenZhang5779** [openzipkin/brave#116]
Hi 
.
I used the brave as client as zipkin recently, and the version of brave is 2.4.2. But I do not know which version of zipkin I should use? can any one get me some suggestion on this issue?

I haved used Zipkin 1.1.0 to tested, and I used "ZipkinSpanCollectorTest" to send the span to the zipkin control service. And the control service can received the Span Data, but when process Span, only insert data into "Traces" family. I cannot find any data at any others family. This is because the Zipkin 1.1.0 is not the corrent version ?
.
Thansk

**Comment by adriancole** [comment]
I'd suggest using latest zipkin, 1.28.0, and the latest brave 3.2.0, as
they have the least bugs and easier to support on
https://gitter.im/openzipkin/zipkin

**Comment by BenZhang5779** [comment]
Thanks for your reply. I haved clone the recently version of brave and zipkin from the github. I start the zipkin-web, zipkin-query-service and zipkin-control-service, then I run ScribeSpanCollectorTest in brave to send the span data to zipkin, and zipkin control cannot received any data for the brave client. If I haved missing some step for the test case for sending span?

**Comment by adriancole** [comment]
The easiest way to get started is to use docker to launch your test
cluster. You don't need to clone zipkin's repo to use zipkin.

https://github.com/openzipkin/docker-zipkin

Brave's span collector then needs to be pointed to your docker ip address
on the corresponding port for the collector.

It is hard to do walk-throughs over a github issue. I'd suggest using
gitter for exploratory questions.
https://gitter.im/openzipkin/zipkin

**Comment by adriancole** [comment]
closing for now... please catch me on gitter if you need more help
