### ISSUE TITLE
publish javadoc to gh_pages like we do in zipkin

### ISSUE THREAD

**Issue by adriancole** [openzipkin/brave#1160]
we have such nice javadoc, shame it isn't published! we can copy/pasta from travis/publish.sh in zipkin

**Comment by anuraaga** [comment]
Armeria is moving to migrate from self-hosting to just using javadoc.io. Not too sure why but I guess it is simple, especially by handling cross dependency links (not helpful for brave which has no dependencies though :) )

/cc @trustin

**Comment by adriancole** [comment]
sounds interesting, though some services come and go. Has this been around a while? I'd hate to setup something formal there, just to have it disappear (it is unlikely gh-pages will disappear)

**Comment by adriancole** [comment]
ex this scares me a little https://github.com/maxcellent/javadoc.io

**Comment by anuraaga** [comment]
I agree with the sentiment. FWIW, I think I've seen it for at least 3 years. But have always wonderer where it gets funding. Have been meaning to ask @trustin whether there was any special motivation for the switch other than simplicity.

I guess one way of putting it is it requires no setup to use, just need to copy the link, so the cost even if it does disappear is extremely low.

**Comment by adriancole** [comment]
https://github.com/openzipkin/brave/pull/1161 as a spike, reusing @abesto's script. We can still consider also hosting to the above, just personally I think the lack of engagement on javadoc.io repo is telling.

**Comment by anuraaga** [comment]
@adriancole You don't get to pick whether it's also hosted to above, it automatically is if you push to maven ;)

**Comment by adriancole** [comment]
similar to jitpack in this regard, just saying I wouldn't in good faith give these links out as permalinks. to each their own!

**Comment by adriancole** [comment]
mentioned in the associated PR that probably now is a good time as any to use a CNAME here for gh-pages, as if github changes their url again, less redirecting

cc also @jorgheymans who's been interested in docs being stable

**Comment by trustin** [comment]
javadoc.io allows to hosting different versions of Javadoc conveniently. With self hosting, we'll have to keep the copies of different versions. If javadoc.io goes away, we can always switch back to self hosting.

**Comment by adriancole** [comment]
by hosting I guess you mean links between versions. that is something our script doesn't do by default (eventhough hosting old versions is implicitly done) https://zipkin.io/zipkin/

**Comment by adriancole** [comment]
in fact it also doesn't point to latest etc (even though we do this in our docker tags.. ex latest major major.minor and major.minor.patch are all "linked")

**Comment by jorgheymans** [comment]
note at some point jdiff reports were deemed useful to have alongside the javadocs https://github.com/openzipkin/zipkin/issues/1221
