### ISSUE TITLE
Add copyright information to license

### ISSUE THREAD

**Issue by seb-ehm** [openzipkin/brave#1206]
**Feature:**
If possible, please add copyright information to the license. Currently, the license only contains the following placeholder :

   Copyright {yyyy} {name of copyright owner}

**Rational**
It makes it easier to get legal approval to use the library in a corporate setting.

**Example Scenario**
Inclusion of brave in a commercial project.

**Prior Art**
Not applicable.

**Comment by adriancole** [comment]
Similar to the apache foundation, we use the NOTICE file to annotate
copyright. This allows the LICENSE file to be an exact match of the
source.

Hope this helps

**Comment by seb-ehm** [comment]
Thank you for your immediate response! I missed the notice file. Thank you for your efforts.

**Comment by adriancole** [comment]
no prob. thanks for using Brave!
