### ISSUE TITLE
Be a bit smarter on transport failures

### ISSUE THREAD

**Issue by adriancole** [openzipkin/brave#122]
That we could be a bit better around errors was acknowledged in the initial import of the http transport. What was agreed was that whatever mechanism we add needs to be tested, and since things like this are hard to test, we should layer fanciness on top.

Seems the time has come!

@marcingrzejszczak mentioned some instability in network causing spans to be dropped. Then, @bensigelman mentioned an algo, which happens to be the same one used in htrace, [the one @clehene wrote](https://github.com/apache/incubator-htrace/blob/master/htrace-zipkin/src/main/java/org/apache/htrace/impl/ZipkinSpanReceiver.java)

It goes like this..
1. (flush() or similar is called)
2. remove all N records from the queue to be flushed
3. attempt to send to remote peer / server / whatever
- if successful, great
- if unsuccessful, add all N records back to the queue while respecting any heuristics about max queue length / total byte size / etc
- regardless of success, wait until trying to flush again

wait until trying is the tricky part, of course… if there are expectations about time ordering in the queue the corner cases are subtle. and of course if you hit your max length there’s still the possibility of dropping data

it’s also important that all flushes are serialized, at least if it’s important that records are delivered to the peer in order (otherwise if flush1 is in flight (and will fail) and flush2 succeeds in the interim, bad things happen, etc)

---

In our implementation, we can do this for sure. Luckily, we can drop corner cases around ordering as there's no expectation of ordering in zipkin's POST endpoint.

One case to call out is HTTP 400, there's no point sending the spans again, as they are malformed. In this case, we can just log a higher level as usually that's a bug.

**Comment by marcingrzejszczak** [comment]
One more thing... In brave HTTPS span collector we're just ignoring all
errors instead of at least logging them. It's impossible to understand what
was the reason for receiving 400 for example. It would be good to start
logging those things.

**Comment by adriancole** [comment]
Heh scroll down in the desc ;)

**Comment by marcingrzejszczak** [comment]
As you can see I've already removed the message ;) I have to read those issues after I'm fully awake ;)

**Comment by adriancole** [comment]
this is all handled by zipkin-reporter-java now
