### ISSUE TITLE
Support GraalVM native images by providing a SamplerPredicate interface

### ISSUE THREAD

**Issue by sdeleuze** [openzipkin/brave#1235]
While working on Spring Cloud Sleuth support for GraalVM native images as part of [spring-graalvm-native](https://github.com/spring-projects-experimental/spring-graalvm-native), I found a blocking issue: `RateLimitingSampler` and `ProbabilityBasedSampler` are not compatible with GraalVM native images because they require a CGLIB proxy (by design not supported) because `Sampler` is an abstract class not an interface.

As shown in [this draft commit](https://github.com/sdeleuze/brave/commit/sampler-interface), with Java 8 it is almost straightforward to turn it into a proper interface that 1) is more clean conceptually 2) allows to use JDK dynamic proxies which are compatible with native images, but it creates 2 challenges:
 - It is a breaking change
 - Android support currently require Java 6 or 7 compatibility (I have seen both mentioned so not sure)

A potential way to solve this issue in a non-breaking way and while retaining keeping Android compatibility could be to introduce a `SamplerPredicate` interface that would then be used on Spring Cloud Sleuth side and similar use cases to allow using JDK dynamic proxies instead of CGLIB ones.

```
interface SamplerPredicate {
	boolean isSampled(long traceId);
}

public abstract class Sampler implements SamplerPredicate {
  // ...
}
```

Could it be possible to do such change?

**Comment by adriancole** [comment]
sorry I don't understand why a cglib proxy is required at all.. are we talking about spring-cloud-sleuth or here? we don't use cglib

**Comment by adriancole** [comment]
I think we can say categorically we can't break that api, but let's chat in case we can make the needs met some other way?

ex possibly the logic in sleuth that's implying a CGLIB proxy can be rejigged.. it is probably confusing sleuth has a class of the same name for example, but it is at the end of the day under the control of that.

https://gitter.im/openzipkin/zipkin

**Comment by adriancole** [comment]
Ironically we do have a sampler predicate function (for requests), just Sampler is one of the oldest apis and even if we did want to transition to that for the trace ID thing, we'd want to do that pretty carefully. https://github.com/openzipkin/brave/blob/master/brave/src/main/java/brave/sampler/SamplerFunction.java

**Comment by adriancole** [comment]
also one of the issues about this is if we want to break it we'd probably want to switch the input to a string heh. I know @anuraaga and I've discussed migrating the trace ID generator etc to that.. compat is annoying!

**Comment by sdeleuze** [comment]
JDK dynamic proxies only support interfaces, so CGLIB proxies are required when using plain classes. In Sleuth, `RateLimitingSampler` and `ProbabilityBasedSampler` extends Brave `Sampler` and uses it in a lot of places.

I think it could be technically possible to put the interface on Sleuth side, but I wanted to check first if there is a way to have an interface at Brave level we could leverage on Sleuth side, since it seems a cleaner approach to me if possible.

**Comment by adriancole** [comment]
I don't think we'll convert everything to interfaces. I assume proxies are used to implement things like refresh scope etc right? basically I'm thinking at least near time we should focus on rejigging that as those types are properties anyway.

Say we use `SamplerFunction<String>` for the base thing, somehow efficiently backport over the isSampled(long) thing.. still it will have to be deprecated and wait for brave 6 to remove. Just want to see what we can do. There are other types besides sampler that are abstract classes also.. so maybe you can share a project that fails to compile, or maybe a fork of https://github.com/openzipkin/sleuth-webmvc-example with a graalvm build?

I'm super interested in making things work one way or another just in reality brave 6 if out would be sleuth 3 earliest as people already inject the other thing. make sense?

**Comment by marcingrzejszczak** [comment]
> I don't think we'll convert everything to interfaces. I assume proxies are used to implement things like refresh scope etc right? basically I'm thinking at least near time we should focus on rejigging that as those types are properties anyway.

Yup that's the case

**Comment by sdeleuze** [comment]
Ok so the fix is easier than expected then, refresh scope makes IMO no sense on native image so I have disabled it by default and was able to run Sleuth without a proxy on `Sampler`. As a consequence I close this issue. Thanks for your support.

**Comment by adriancole** [comment]
Thanks for looping back, and reminding what we should watch out for!
