### ISSUE TITLE
RabbitMQ: tracing headers not propagated to reply of @RabbitListener

### ISSUE THREAD

**Issue by pzapasni** [openzipkin/brave#1258]
**This is a copy of [spring-cloud-sleuth/issues/1752](https://github.com/spring-cloud/spring-cloud-sleuth/issues/1752), since I was asked to report this issue here**

In my app I'm using ``spring-cloud-starter-sleuth:2.2.5`` with ``spring-boot-starter-amqp:2.2.7``. I have a ``@RabbitListener`` annotated method which accepts a message, processes it, and returns a response:

```java
@Service
@RequiredArgsConstructor
@Slf4j
@Transactional
public class MyListener {

    private final MyService service;

    @RabbitListener(queues = "${amqp.queue.name}")
    public MyEvent handleCommand(@Payload @Valid MyCommand command) {
        log.info("Received command {}", command);
        return service.handleCommand(command);
    }
}
```

If the incoming message has the ``b3`` header, the tracing information is present throughout the processing of the message. However, when the response message from that processing is being returned to RabbitMQ, it does not contain the ``b3`` header, which breaks the tracing.

I've investigated this issue a bit, and it seems to me that the only instrumentation for the listener (or rather ``SimpleRabbitListenerContainerFactory``) is being done through the ``SleuthRabbitBeanPostProcessor`` and ``TracingRabbitListenerAdvice``, however I couldn't find any code there that would take care of injecting the header into the response message. Is my assumption correct and this is a missing feature, or did I miss something?

**Comment by adriancole** [comment]
We typically use https://gitter.im/openzipkin/zipkin for starting issues, but this is fine as I think it is likely to result in a code change.

Here's the part about this from [rabbit docs](https://docs.spring.io/spring-amqp/api/org/springframework/amqp/rabbit/annotation/RabbitListener.html)
>  Annotated methods may have a non void return type. When they do, the result of the method invocation is sent as a reply to the queue defined by the ReplyTo header of the incoming message. When this value is not set, a default queue can be provided by adding @SendTo to the method declaration.

As you noticed, right now this reply-to feature isn't implemented in a way that would continue the trace. There's no test for this and no one had asked for it until now. Depending on the code involved, it may be easy or hard to wrap the producer code in spring-rabbit in context of the "listener span" executing this method.

Zipkin is a completely volunteer run project, so if you can help implement this, it would be grand.

I would start by adding a test that captures the minimal for the reply-to concern into a new test in `ITSpringRabbitTracing`, taking care to follow conventions in that file. Bonus points for implementing the feature!

cc @jeqo @jorgheymans as this is an interesting take on listeners. I hadn't noticed one with request/reply processing before this..

**Comment by pzapasni** [comment]
@adriancole I tried to come up with a PR using your guidelines, but there were a couple of issues I am unsure how to fix. I've linked the draft PR to this issue.

**Comment by adriancole** [comment]
next release will have this in. meanwhile can test snapshot
