### ISSUE TITLE
(Kafka) TracingProducer errors without sending record if setting headers fails

### ISSUE THREAD

**Issue by m50d** [openzipkin/brave#1266]
## Describe the Bug
TracingProducer tries to inject headers to propagate the current trace context. If an exception occurs during this then that exception is allowed to propagate and the record does not get sent to Kafka.

## Steps to Reproduce
https://github.com/m50d/brave/commit/8e9b256f8f52219b5edd0accb41ca3c1eae15b6a has a test reproduction with the case I encountered: `setReadOnly` had already been called on the relevant record's headers, and so attempting to change them failed.

## Expected Behaviour
I appreciate that this is arguable, but I would expect tracing to swallow and log exceptions as far as possible rather than allowing an error in tracing to interfere with the application's main functionality.

**Comment by adriancole** [comment]
fair enough. I think we have some defense like this in JMS, in the setter implementation. Mind fixing this and adding your test? you can use the same exception logging approach as JMS

**Comment by adriancole** [comment]
here's what I meant https://github.com/openzipkin/brave/blob/master/instrumentation/jms/src/main/java/brave/jms/MessageProperties.java#L40-L47
