### ISSUE TITLE
Span did not share between Span type "Client" and "Server" while using SpringBoot 2.4.5 and SpringCloud 2020.0.2

### ISSUE THREAD

**Issue by desertTown** [openzipkin/brave#1307]
## Steps to Reproduce
use SpringBoot 2.4.5 and SpringCloud 2020.0.2
and do a Restful Call, you will find  SpanId did not share between Kind of "Client and Server"

![image](https://user-images.githubusercontent.com/17807898/134481887-e28ab204-5c4d-4e86-bd8a-519b6e2a4261.png)
unexpected result

![image](https://user-images.githubusercontent.com/17807898/134481972-c111387d-ad3b-402b-9f86-aaf6b9a586b5.png)## 
expected result

Expected Behaviour
SpanID  shared between Span type "Client" and "Server" if you use SpringBoot 2.4.5 and SpringCloud 2020.0.2
I have tested in versions: SpringBoot 2.3.1 and SpringCloud Hoxton.SR8,  and they will share the span

**Comment by marcingrzejszczak** [comment]
Interesting cause we're also setting it to `true` and haven't changed that code in years https://github.com/spring-cloud/spring-cloud-sleuth/blob/main/spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/brave/BraveAutoConfiguration.java#L97 https://github.com/spring-cloud/spring-cloud-sleuth/blob/main/spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/brave/SleuthProperties.java#L39 .

**Comment by marcingrzejszczak** [comment]
That was a bug in a Sleuth release that has already been fixed. We can close this issue.
