### ISSUE TITLE
Latest version Brave 5.13.4 cannot be found on mvnrepostiory

### ISSUE THREAD

**Issue by btrajkovski-mms** [openzipkin/brave#1314]
## Describe the Bug
As you know there was a security patch done and the latest version on Github is 5.13.4 https://github.com/openzipkin/brave/releases. I wanted to use this version to update my dependencies, however it is still not present on mvnrepository or jcenter repo

Regardless, the best is to spend some time to write a failing test. Bugs with tests get fixed and stay fixed.

## Steps to Reproduce
- Update `io.zipkin.brave:brave depndency` to `5.13.4`
- Run `mvn install` or `gradle build`

## Expected Behaviour
Version should be successfully updated because 5.13.4 is released. However gradle throws
```
io.zipkin.brave:brave-context-log4j2:5.13.4 (selected by rule) FAILED
   Failures:
      - Could not find io.zipkin.brave:brave-context-log4j2:5.13.4.
        Searched in the following locations:
          - https://repo.maven.apache.org/maven2/io/zipkin/brave/brave-context-log4j2/5.13.4/brave-context-log4j2-5.13.4.pom
          - https://repo.maven.apache.org/maven2/io/zipkin/brave/brave-context-log4j2/5.13.4/brave-context-log4j2-5.13.4.jar
          - https://jcenter.bintray.com/io/zipkin/brave/brave-context-log4j2/5.13.4/brave-context-log4j2-5.13.4.pom
          - https://jcenter.bintray.com/io/zipkin/brave/brave-context-log4j2/5.13.4/brave-context-log4j2-5.13.4.jar
```

**Comment by jcchavezs** [comment]
We have some issues with Sonatype (see https://github.com/openzipkin/brave/runs/4517949090?check_suite_focus=true#step:4:6563). @llinder is looking into a solution soon.

**Comment by ilyasjaan** [comment]
When are we expecting this to be fixed and available on maven? Also i see log4j has 2.16.0 now... any plans to use that instead?

**Comment by 4markumar** [comment]
Both 5.13.4 and 5.13.5 are not available on maven due to the sonatype issue. When are we expecting this to be fixed and available on maven?

**Comment by jcchavezs** [comment]
5.13.5 should be available on maven. Would you give it a try?

**Comment by llinder** [comment]
5.13.4 has finally been replicated to Maven Central. The whole release processes is really slow the last week or so. When we do get a successful release I would expect it to take 24-48 hours to show up in Maven Central until the Sonatype backlog starts to ease up.
