### ISSUE TITLE
Support for jakarta servlet specification 

### ISSUE THREAD

**Issue by CoderYellow** [openzipkin/brave#1337]
just api package change

**Comment by jcchavezs** [comment]
Up for a PR on this?

**Comment by CoderYellow** [comment]
> Up for a PR on this?

I am not farmilar with this project but I think is just a package name refactor, `javax` to `jakarta`, and the api should not change. FYI https://github.com/jakartaee/rest

**Comment by CoderYellow** [comment]
jetty, spring 6 has supported jakarta, do you have any plan for this

**Comment by reta** [comment]
@jcchavezs I am up to take it if you don't mind, have similar roadblock for Apache CXF and Jakarta support, sounds good?

**Comment by jcchavezs** [comment]
Sounds good to me.

**Comment by jcchavezs** [comment]
@reta did you have the time to look into this?

**Comment by reta** [comment]
> @reta did you have the time to look into this?

Picking it up this weekend, sorry about that, was on vacation
