### ISSUE TITLE
Add missing method in TracingConsumer to support Kafka 3.2.0+

### ISSUE THREAD

**Issue by frosiere** [openzipkin/brave#1338]
To allow supporting newer versions of Kafka, would it be possible to upgrade the _TracingConsumer_ by adding the following method

`void enforceRebalance(final String reason);`

This method has been added in Kafka 3.2.0.

 Source code of the Consumer interface with the new method can be found here
https://github.com/apache/kafka/blob/3.2.0/clients/src/main/java/org/apache/kafka/clients/consumer/Consumer.java#L264

My current project using Spring Boot 2.7.2, Kafka 3.2.1 and Brave 5.13.9 had the issue which has been fixed by adding this new method locally. No other issues have been detected when using Kafka 3.2.1.

Any feedbacks are more than welcome on this issue. I may eventually contribute by dropping a PR.

**Comment by jcchavezs** [comment]
Of course contributions are welcome. Ping @jeqo

**Comment by frosiere** [comment]
Question: if we upgrade the Kafka version in the Brave library to 3.2.1, will it still work with previous versions of Kafka?
I suppose the fact to not use @Override is for this reason?!
If it's confirmed, the fix is quite easy.

**Comment by jcchavezs** [comment]
@frosiere up for a PR on this?
