### ISSUE TITLE
Add @Priority annotation to jersey 2 client and server filters ?

### ISSUE THREAD

**Issue by janolaveide** [openzipkin/brave#134]
Would not all use-cases require that the filters trigger as early as possible for requests and as late as possible for responses ? In particular, when there are potentially time-consuming operations implemented in a request-filter (e.g. for authentication), I would like to be sure that the client send and server receive annotations are time-stamped before the other filters are executed.
https://jersey.java.net/documentation/latest/filters-and-interceptors.html (10.7) states that the lowest priority is executed first for requests and last for responses. I have achieved thus by subclassing the brave jersey filters, adding a @Priority(0) annotation, but are there good reasons this should not be done in the brave filters themselves ?

**Comment by jplock** [comment]
Would it also make sense to make the request interceptor @PreMatching with @Priority(0)?

**Comment by janolaveide** [comment]
I think it does, at least that is what I do in my subclass.

**Comment by adriancole** [comment]
if you two know what the best course is... pull request time? :P

**Comment by janolaveide** [comment]
Will do when I have time, just wanted to discuss it first in case I was missing something.

**Comment by adriancole** [comment]
Thanks, I'm just going to play the role of code reviewer :) I don't have any pre-canned insight on this one, but a couple people ack'ing the same thing is a signal we can move forward.

**Comment by jplock** [comment]
I'm on holiday until next week. If no one has submitted anything by then, I can take care of it next week.
