### ISSUE TITLE
[Feature] Brave is partly compatible with Spring 3.0. JMS uses javax while Spring 3.0 relays on jakarta

### ISSUE THREAD

**Issue by bademux** [openzipkin/brave#1352]
## Feature
Brave is partly compatible with Spring 3.0. JMS uses javax while Spring 3.0 relays on jakarta

## Rationale
https://docs.spring.io/spring-boot/docs/3.0.0/reference/html/dependency-versions.html#appendix.dependency-versions.coordinates
brave version is 5.14.1, but for JMS it uses javax package. It is incompatible with SpringBoot 3.0 expectation.
https://github.com/openzipkin/brave/blob/5.14.1/instrumentation/jms/src/main/java/brave/jms/JmsTracing.java#L34

related:
https://github.com/spring-projects/spring-boot/issues/33487

**Comment by reta** [comment]
Ah, yes, the Jakarta Servlets are supported [1], but not JMS, @shakuzen @jcchavezs I can take this one

[1] https://github.com/openzipkin/brave/tree/master/instrumentation/servlet-jakarta
