### ISSUE TITLE
Multiple SpanNameProvider instances

### ISSUE THREAD

**Issue by mikewrighton** [openzipkin/brave#138]
I have a question about the name providers. My application has both client and server components (in separate libraries) and both are providing bindings to SpanNameProvider, since I want different handling for each. This is, of course, resulting in a Guice binding conflict.

Is there a recommended way around this? Seems like it would be useful to allow multiple name providers within one application.

(I'm using brave-jaxrs2)

**Comment by adriancole** [comment]
I think the best way to address this right now, is to make a provider
method for the filters that use the span namers. in your provides
parameter, you can place a qualifier on each.

**Comment by mikewrighton** [comment]
Ah okay, so if I understand correctly I'll need to change the filter code to use @Named where the SpanNameProvider gets injected?

**Comment by adriancole** [comment]
yep Named or an annotation you make up that has Qualifier on it.

**Comment by brich200** [comment]
I'm working with brave-http and trying to understand how zipkin chooses between spanNameProviders when it is given two options (one from client side and one from server side). It appears to randomly select one of the spanNameProviders even when the same services are involved. Is there a way I can force the zipkin UI to choose the client side provider if both are present but still use the server side provider if client side wasn't present in a span?

**Comment by adriancole** [comment]
SpanNameProvider is a type in Brave, but that's controlled by the user
doing configuration. For example, if you were using jaxrs, the
BraveClientRequestFilter and BraveContainerRequestFilter types are
something that you can configure to specify how to name the client vs
the server side.

Brave sends a patch of a span to zipkin for each side. Both sides can
include a span name, or empty string for the span name. If you want to
defer to the other side, you'd specify empty string (or "unknown").
For example, if you want the server to prefer the client's name of the
span, you can have the server's SpanNameProvider return empty string.

Zipkin's UI doesn't resolve conflicts on span name, as conflicts
happen before the UI gets a list of spans. Technically, this conflict
can only occur when a client and server span share the same id:
zipkin-server merges by ID before returning the api response, as it is
unexpected to return duplicate ids.

Here's exactly where the preference happens:

https://github.com/openzipkin/zipkin/blob/master/zipkin/src/main/java/zipkin/Span.java#L197


Hope this helps.

**Comment by adriancole** [comment]
Brave 4.3 is out, which includes `HttpTracing` which configures things generically and avoids this problem as the client and server parser are different objects
