### ISSUE TITLE
TracingClientHttpRequestInterceptor.java in Brave 4 requires HttpTracing which is available starting brave 5

### ISSUE THREAD

**Issue by arung0wda** [openzipkin/brave#1380]
I was trying to instrument RestTemplate in spring and came across [this](https://github.com/openzipkin/brave/blob/4.13.x/instrumentation/spring-web/README).

However both the create methods of [TracingClientHttpRequestInterceptor](https://github.com/openzipkin/brave/blob/4.13.x/instrumentation/spring-web/src/main/java/brave/spring/web/TracingClientHttpRequestInterceptor.java#L29) are depended on HttpTracing class which is only available starting Brave 5.

Could you help with how I can instrument Rest template with brave 4 without having to include Brave 5?
I have to use Brave 4 due to legacy codebase and can't upgrade to Brave 5.

## Steps to Reproduce
Try instrumenting Rest Template with Brave 4.

## Expected Behaviour
Instrumenting Rest Template with Brave 4 should be possible without having to depend on Brave 5.

**Comment by codefromthecrypt** [comment]
Closing this issue as Brave 4 is no longer maintained, but HttpTracing was available in Brave 4 https://github.com/openzipkin/brave/blob/4.13.x/instrumentation/http/src/main/java/brave/http/HttpTracing.java, so you should be ok.
