### ISSUE TITLE
Brave and multi threading

### ISSUE THREAD

**Issue by Ryann-Luo** [openzipkin/brave#157]
Hi,

I'm new to distributed system tracing and now going through the code of Brave. I have some doubts about the topic of multi threading in Brave. I would be greatly grateful that someone could provide some hints.

First, in ServletHandlerInterceptor.java of brave-spring-web-servlet-interceptor module, the afterConcurrentHandlingStarted method sets the current span from the binder into the request, what's the purpose of this? In my understanding, in a async request, even if the task is put into the thread pool, the request still holds the span info, there might be no need to add currentspan in request. Thus, I would like to know the role of serverThreadBinder played in async http request. 

Second, in brave-core module, there are BraveCallable, BraveRunnable and BraveExecutorService. Where are they used? The README.md says they might be used in scenario where you start a new thread yourself from a request Thread, but is there any implementation of this scenario in this Brave project?

I know my questions are stupid, but it's hard to find hints to resolve them. Hopefully someone can help! Thanks!

**Comment by eirslett** [comment]
> Second, in brave-core module, there are BraveCallable, BraveRunnable and BraveExecutorService. Where are they used? The README.md says they might be used in scenario where you start a new thread yourself from a request Thread, but is there any implementation of this scenario in this Brave project?

This can be used for Hystrix calls, which sometimes starts requests in new threads, or in the Hystrix thread pool. Span state is stored in a ThreadLocal, so the state needs to be passed on into the Hystrix call.

**Comment by Ryann-Luo** [comment]
@eirslett Thanks for your reply. It helps a lot !~

**Comment by adriancole** [comment]
ps Brave 4.3 includes async tracing for servlet, okhttp and apachehc. You can also do custom things with CurrentTraceContext
