### ISSUE TITLE
migrate to zipkin-java'like deployment

### ISSUE THREAD

**Issue by adriancole** [openzipkin/brave#161]
Most impactful would be changing the group id from "com.github.kristofa" to "io.zipkin.brave". If we do, then we can use bintray instead of sonatype. This has the advantage of group access controls and nice things like auto-signing of jars. Most importantly, we can use the same process to release zipkin-java and brave.

**Comment by adriancole** [comment]
cc @abesto @eirslett @kristofa

**Comment by kristofa** [comment]
@adriancole I'm all for it. It is good to have consistency and it prevents I'm the only one who can make releases for brave.  It the release process described somewhere?

**Comment by adriancole** [comment]
I've extracted the maven sync plugin which @abesto and I worked on. Once this is in, we can switch brave to use openzipkin process https://github.com/openzipkin/brave/issues/161

**Comment by adriancole** [comment]
added a bintray package and requested it added to jcenter https://bintray.com/openzipkin/maven/brave/view

**Comment by adriancole** [comment]
so.. for releasing brave from OZ. We've the parts to do this now.
easiest way would be to just change the maven group id as opposed to trying to deploy to 2 different group ids
ex change it from `com.github.kristofa` to `io.zipkin.brave`
then brave 3.7.1 or whatever would require folks to update their maven config

**Comment by adriancole** [comment]
here's the change to turn this on! https://github.com/openzipkin/brave/pull/178

**Comment by adriancole** [comment]
http://oss.jfrog.org/artifactory/oss-snapshot-local/io/zipkin/brave/ has snapshots now

**Comment by adriancole** [comment]
pushed tag release-3.8.0 and seeing if it works!

https://travis-ci.org/openzipkin/brave/builds/131542806

**Comment by adriancole** [comment]
done! https://travis-ci.org/openzipkin/brave/builds/131561655

**Comment by kristofa** [comment]
Nice! 👍

**Comment by abesto** [comment]
Awesome sauce. 🎆 🍰
