### ISSUE TITLE
Error with Jersey2 application

### ISSUE THREAD

**Issue by anujkumarnag** [openzipkin/brave#163]
Hi,

I have integrated brave client and server filters to trace the logs. while executing the client program following error is coming:
A MultiException has 3 exceptions.  They are:
1. org.glassfish.hk2.api.UnsatisfiedDependencyException: There was no object available for injection at Injectee(requiredType=ServerResponseInterceptor,parent=BraveContainerResponseFilter,qualifiers={},position=0,optional=false,self=false,unqualified=null,5690042)
2. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of com.github.kristofa.brave.jaxrs2.BraveContainerResponseFilter errors were found
3. java.lang.IllegalStateException: Unable to perform operation: resolve on com.github.kristofa.brave.jaxrs2.BraveContainerResponseFilter

I am attaching the sample program both client and web app.
[zipkin-sample.zip](https://github.com/openzipkin/brave/files/239771/zipkin-sample.zip)
[Error.txt](https://github.com/openzipkin/brave/files/239772/Error.txt)

**Comment by fluidjeel** [comment]
I am facing similar issue as well

**Comment by adriancole** [comment]
There's no glassfish configuration module in brave, but this is clearly a
wiring problem. Please see the spring example in case it helps you solve
the problem:

https://github.com/openzipkin/brave/blob/fd3cdb921964a0d7164c29141fe6aac8099ae4cf/brave-resteasy3-spring/src/main/java/com/github/kristofa/brave/resteasy3/ContainerFiltersConfiguration.java

**Comment by anujkumarnag** [comment]
Thanks for the reply!! I will check the provided reference and see if I am able fix the issue.

**Comment by jfnavin** [comment]
I hit this same issue. 

The fix for me was to include a dependency on `brave-core-spring` in my project pom. This component includes a `com.github.kristofa.brave.BraveApiConfig` class that provides the missing bean dependencies.

e.g.
`pom.xml`:
```
<dependency>
         <groupId>io.zipkin.brave</groupId>
         <artifactId>brave-core-spring</artifactId>
</dependency>
```

Configuration class:
```
@Configuration
@ComponentScan(basePackages={"com.github.kristofa.brave"})
public class ZipkinConfig {
    ...
}
```

**Comment by adriancole** [comment]
Brave 4.3 includes a new brave-instrumentation-jaxrs2. can you retry?
