### ISSUE TITLE
does brave support async call? 

### ISSUE THREAD

**Issue by dragontree101** [openzipkin/brave#164]
i want to use async client, does brave can support async client? 
thanks!

**Comment by adriancole** [comment]
Here's a related issue https://github.com/openzipkin/zipkin/issues/1189

Most importantly, we need to capture what the scenario here is, and what problems are trying to be solved. Currently, as mentioned above, we can "fake" rpc by treating the producer activity as the client side of an RPC and the consumer activity as the server side. That will work for sure between now and such time an alternate method exists.

**Comment by adriancole** [comment]
async is via the "flush" method. Here's example: https://github.com/openzipkin/brave/tree/master/brave/src/test/java/brave/features/async

**Comment by dragontree101** [comment]
thanks very much!
