### ISSUE TITLE
in MySQLStatementInterceptor this class , why use 'static volatile ClientTracer clientTracer'?

### ISSUE THREAD

**Issue by whx4J8** [openzipkin/brave#172]
in the brave-mysql ,'MySQLStatementInterceptor'  this class.
I have some questions

`
// TODO: is static scope best? ex. preferred to thread local etc?
`
`
    static volatile ClientTracer clientTracer;
`

why use static volatile to store clientTracer object?
thank you very much

**Comment by adriancole** [comment]
As far as I can tell, the MySQLStatementInterceptor is installed as a query
parameter on the JDBC url, so its instantiation is outside the scope of
brave, hence it being accessed via a static.

If you know another way to address this, do tell!

**Comment by whx4J8** [comment]
@adriancole but why use volatile ? My doubts are here.

**Comment by adriancole** [comment]
My guess is that this is to ensure that the assignment of the
interceptor in MySQLStatementInterceptorManagementBean is visible to
other threads. I put the TODO there because I also had questions when
I came across this.

**Comment by whx4J8** [comment]
I've almost got it. 
thank you~~ 
: )
