### ISSUE TITLE
Rename SpanCollector to SpanReporter

### ISSUE THREAD

**Issue by adriancole** [openzipkin/brave#173]
Zipkin has adopted the term "reporter" to indicate the client side of a span transport, and "collector" for the server-side. By naming the brave side "Reporter" or "SpanReporter", we can more easily lock into architecture diagrams without confusion.

https://github.com/openzipkin/openzipkin.github.io/issues/23

Ex below:

![](https://cloud.githubusercontent.com/assets/59982/14770085/0ca67162-0a69-11e6-9971-f47854ffb9c1.png)

**Comment by kristofa** [comment]
Good to see more consistency. 👍

**Comment by adriancole** [comment]
we currently use native reporter from zipkin-reporter-java
