### ISSUE TITLE
Add support for OkHttp

### ISSUE THREAD

**Issue by tburch** [openzipkin/brave#174]
@kristofa what are you thoughts on adding a [OkHttp](https://github.com/square/okhttp) interceptor to the brave project? I'm happy to implement it. Seems like it'd be a good compliment to Http Client and Jersey.

**Comment by adriancole** [comment]
unsolicited 2p is that this would be a nice idea

use application interceptors to start and name a span, add "cs" "cr" etc
use network interceptor to log wire send, wire receive, etc

https://github.com/square/okhttp/wiki/Interceptors
https://github.com/openzipkin/brave/blob/master/brave-core/src/main/java/com/twitter/zipkin/gen/zipkinCoreConstants.java#L72

**Comment by kristofa** [comment]
Yes definitely. I think that would be a great contribution.

**Comment by eirslett** [comment]
+1 would be great!

**Comment by tburch** [comment]
Cool! I'll submit it soon. @adriancole I hadn't thought about the network interceptor, so I'll add that to what I have.

**Comment by tburch** [comment]
I created the OkHttp request/response interceptor and opened a PR (#175). It looks like none of the ws/wr annotations have been implemented, so I'll do that when I have some more time since it's going to be a little more work than just tacking on cr/s annotations.

**Comment by adriancole** [comment]
You are right that there arent any brave tracers yet doing wire or fragment annotations. Here are some breadcrumbs from finagle

https://github.com/twitter/finagle/blob/6e368706f5be0a85deea21eb566e8f9119fef295/finagle-core/src/main/scala/com/twitter/finagle/tracing/TraceInitializerFilter.scala#L192

ClientSendFragment etc exists in finagle, but I dont see it used. Possibly, it is used internally.

**Comment by adriancole** [comment]
brave-instrumentation-okhttp3 is latest news here (in brave 4.3)
