### ISSUE TITLE
MySQLStatementInterceptor Reports Service Name of Binary Annotation "sa" as "unknown"

### ISSUE THREAD

**Issue by tangrui** [openzipkin/brave#176]
The reported data is like this:

``` json
{
      "key": "sa",
      "value": true,
      "endpoint": {
        "serviceName": "unknown",
        "ipv4": "172.20.10.65",
        "port": 8089
      }
}
```

Since this annotation is reported by MySQLStatementInterceptor, so could this serviceName be hard coded as "mysql" but not 'unknown'.

**Comment by eirslett** [comment]
Or even "mysql: [name-of-database]" which is what we use at FINN.no internally. (We don't use this interceptor, we use our own)

**Comment by adriancole** [comment]
I think we've been encouraging lower-hyphen service names. much easier with
curl, too. mysql-database?

**Comment by tangrui** [comment]
But database name may contain hyphens too. E.g. my-fancy-db

It's better if the service name can be customised. Maybe via MySQLStatementInterceptorManagementBean initialization or providing a dummy property appended to the jdbc connection string. `?statementInterceptors=com.github.kristofa.brave.mysql.MySQLStatementInterceptor&serviceName=myService`, even though it is not standard.

**Comment by adriancole** [comment]
more hyphens aren't a problem, but good point. Do you want to try and raise
a PR to do this?

**Comment by eirslett** [comment]
Brave uses SpanNameProvider a lot, maybe we should have ServiceNameProvider as well?

**Comment by adriancole** [comment]
just that servicename provider is ambiguous. here's something similar
https://github.com/openzipkin/brave/blob/master/brave-core/src/main/java/com/github/kristofa/brave/ClientRequestAdapter.java#L50

**Comment by tangrui** [comment]
Create a pull request https://github.com/openzipkin/brave/pull/177.

**Comment by adriancole** [comment]
this should be sorted now
