### ISSUE TITLE
On Brave 4

### ISSUE THREAD

**Issue by adriancole** [openzipkin/brave#180]
We've had some feedback that we break api too much :)

Let's leave 3.7+ api stable, and move master to 4.0.0-SNAPSHOT. As a part of that, we can significantly flatten the packages to brave.X and use the zipkin model classes directly instead of wrapping them.

Here are some features for Brave 4:
* repackage into `brave.*` (and coexist with existing code tree)
  * this allows us to change the existing code base so that it might bridge easier.
* no more public everything
  * this will be designed like effective java which will make maintenance easier over time.
* instead of ClientTracer ServerTracer etc, use decorators on a single Span type
  * this simplifies state problems considerably
* Span will have a start/finish function can can be passed around explicitly
  * it can be noop when unsampled
* Allow a simple in-process propagation api for Span, which allows nesting, but don't require it
  * some frameworks will need to use implicit propagation, but some won't
* replace SpanId with TraceContext which carries identifiers even when unsampled
  * this allows brave to be a pass-through
* make B3 batteries included but optional w/Propagation
  * this allows people to use a new header at some point
* Add Client Server and MessageHandler/interceptor (#284)
  * This simplifies the current http interceptors using native types and not requiring http
* Update the [OpenTracing bridge](https://github.com/openzipkin/brave-opentracing)
  * This api fits into OT much more nicely than before, and hopefully will with future versions of OT.

Bridging to brave 3.x is frankly hard because of thread state management, and most interceptors are better off redone as new ones. The focus on interop will be trying to ensure that traces are continued in-process without breaking. This might require a bridge type.

**Comment by eirslett** [comment]
+1

**Comment by adriancole** [comment]
I think any major designs updates like a new interceptor model should be a part of brave 4 since deprecation and trying to portably wire in things you don't have constructor references for is a fools errand.

here's a writeup on new interceptors/handlers https://github.com/openzipkin/brave/issues/284

**Comment by adriancole** [comment]
cc @openzipkin/core @openzipkin/brave I will have something up this week. basically work trying to change all instrumentation seems shorter by actually fixing some of the root apis.

**Comment by devinsba** [comment]
A thought I've been having is would it make sense to make brave an OpenTracing implementation instead of just having the shim. OT doesn't seem completely mature but I don't see 4.x being an immediate release so that may not be an issue.

**Comment by adriancole** [comment]
@devinsba think about opentracing 2 :) There's no reason to make it possible to have a type conflict by introducing a third-party dependency in brave's core repo https://groups.google.com/forum/#!topic/go-kit/AHgWcvCBat0

**Comment by adriancole** [comment]
Bear in mind that brave is also used by HTrace and other non-OpenTracing libraries. Plus OT has deprecated apis even in the current version (unfortunately, the one we use is deprecated). It isn't a good fit for the core library.

**Comment by adriancole** [comment]
and so it begins https://github.com/openzipkin/brave/pull/300

**Comment by adriancole** [comment]
Took a long time and quite a bit of work to align internals. Should be around the bend shortly.

#300 has a new design which is similar to finagle, which has a concept of a span map. you can collaborate with a span by passing its key (as opposed to holding a direct reference to it). Using this, we can put 2 heads on the same span.

The first would be a "real span" object, the brave 4 api, which looks like this..

```java
try (Span span = tracer.newTrace().name("encode").start()) {
  // do some stuff
} // finishes on close
```

The second head would be a bridge to the old api. For example, AnnotationSubmitter could be ported to use recorder that underlies brave 4's span like so..

```java
recorder = Internal.instance.recorder(brave4Tracer);
...
public void submitAnnotation(String value, long timestamp) {
  Span span = currentSpan().get();
  if (span == null) return;

  // this is the new part!
  recorder.annotate(span.context(), timestamp, value);

  // it was this..
  //Annotation annotation = Annotation.create(timestamp, value, endpoint());
  //synchronized (span) {
  //    span.addToAnnotations(annotation);
  //}
}
```

**Comment by adriancole** [comment]
I've hit an important milestone in brave 4. It can now transparently implement brave 3.

Next steps are to polish api and unit tests, and particularly show off a very cool couple features (IMHO)
* you can join a span made with brave 3 and use it in brave 4 in the same process
  * This took the most work, and it allows you to use brave 3's in-process propagation with brave 4!
* you can take a brave 4 span and manually propagate it. just call span.finish to report it done.
  * This is the biggest win for those using async libraries

**Comment by adriancole** [comment]
updated the design, calling specifically out how to do custom sampling (which you could do in Brave 3 using the TraceData type)

### Custom sampling

You may want to apply different policies depending on what the operation
is. For example, you might not want to trace requests to static resources
such as images, or you might want to trace all requests to a new api.
Most users will use a framework interceptor which automates this sort of
policy. Here's how they might work internally.

```java
Span newTrace(Request input) {
  SamplingFlags flags = SamplingFlags.NONE;
  if (input.url().startsWith("/experimental")) {
    flags = SamplingFlags.SAMPLED;
  } else if (input.url().startsWith("/static")) {
    flags = SamplingFlags.NOT_SAMPLED;
  }
  return tracer.newTrace(flags);
}
```

**Comment by adriancole** [comment]
current status: interop works very well at this point.

For example, you can seamlessly shift between OpenTracing and Brave4's span model (using only static functions). You can also take a brave4 span and attach it to Brave 3's thread binders.

Only one internal hook was needed, which was to support `LocalSpan.finishSpan(duration)`. This hook is needed to read-back the span's timestamp (in order to create and end timestamp). Users will be unaware of this, but it does imply this hook needs to stick around until Brave 3 is no longer supported. This was an optimization choice.. instead of optimizing for `LocalSpan.finishSpan(duration)`, optimize for stateless completion where possible. comments exist in the corresponding code.

Next step is to put back in the propagation code, if not temporarily, just to prove that the abstraction works without internal hooks.

**Comment by adriancole** [comment]
current status:

* core and propagation apis are in place
* adapters and documentation exists for Brave 3 users
* opentracing bridge update in progress

next steps:

* get a "current span" api together
* re-implement instrumentation over the new api (#350)

**Comment by adriancole** [comment]
Brave 4.3 is syncing to Maven central now, and covers all the major points here with revamped instrumentation.
