### ISSUE TITLE
Need confirmation on brave zipkin working

### ISSUE THREAD

**Issue by anujkumarnag** [openzipkin/brave#187]
Hi,

I am trying to use zipkin to trace the inter micro service calls.
my applications are based on Jersey (1) 
I am doing following steps:
1) Zipkin services configured:
    - executing zipkin-collector-service
    - executing zipkin-query-service
    - executing zipkin-web
2) Configured brave to trace the application calls
    - Configured brave jersey implementation
       - initialized  com.github.kristofa.brave.jersey.ServletTraceFilter
       - configured ScribeSpanCollector in the ServletTraceFilter
       - added brave-jersey and brave-spancollector-scribe dependency
3) To verify the trace
     - I have configured request interceptors in my Jersey client
      
      brave = builder.spanCollector(collector).traceFilters(Arrays.<TraceFilter> asList(new   FixedSampleRateTraceFilter(1))).build();

      StringServiceNameProvider srvProvider = new StringServiceNameProvider("testClient");
      SpanNameProvider snapProvider = new DefaultSpanNameProvider();

      final Client client = ClientBuilder.newClient().register(new BraveClientRequestFilter(srvProvider, snapProvider, brave.clientRequestInterceptor()))
				.register(new BraveClientResponseFilter(srvProvider, snapProvider, brave.clientResponseInterceptor())`
the trace which I am getting from this client do not have the traces from server.

So I wanted to understand following

-  Is  it the RESTAPI client registered span collector will collect all of the trace from server side and push it to zipkin collector service or each of the application/server configured with brave filter will send their trace to zipkin collector service through there own span collectors?
- How the inter service call graph is generated in zipkin web UI? if each of the services will send their trace alone and not send the entire call graph? Or the client which consume the service will capture all of the call graph in its own span collector and push it to zipkin collector service?

Request you to please confirm on these concepts.

**Comment by kristofa** [comment]
Hello,

   * Every client and server configured with the required interceptors / filters will push trace information to the zipkin collector service through their own SpanCollector instances.
   * Zipkin web is able to generate the full call graph because eventually all information (spans) get together in the same back-end store.

I would advise you to read the [Architecture](http://zipkin.io/pages/architecture.html) and [Data Model](http://zipkin.io/pages/data_model.html) sections of the [zipkin.io website](http://zipkin.io) if you haven't done that yet.

I have no experience myself with using the jersey implementation. If you can't get the server side integration to work it might help if you make the code available.

**Comment by anujkumarnag** [comment]
Hi Kristofa,

Thanks for your reply!

I am attaching my sample Jersey application and modified brave-jersey along with this comment.

- To initialize the server side servlet I have updated the web.xml to directly register the filer
- Also to reduce the variable for troubleshooting the issue I have hard code the brave instance initialization and scribe span collector initialization in the brave-jersey filter itself.
  ```
 package com.github.kristofa.brave.jersey;
   @Singleton
   public class ServletTraceFilter extends BraveServletFilter {
	// create a servertracer
	private static Brave brave = new Brave.Builder("myservicename").spanCollector(new ScribeSpanCollector("localhost", 9410)).traceFilters(Arrays.<TraceFilter> asList(new FixedSampleRateTraceFilter(1))).build();
	private static SpanNameProvider spanNameProvider = new DefaultSpanNameProvider();

	public ServletTraceFilter() {
    	super(brave.serverRequestInterceptor(), brave.serverResponseInterceptor(), spanNameProvider);
      }
   }
```


On application startup the filter is getting registered and on hit the API url it is getting triggered but the traces are not getting to zipkin collector service and hence not coming up in web-ui.

Request you help to troubleshoot the issue.

Thanks for your support!!

[brave-jersey.zip](https://github.com/openzipkin/brave/files/316280/brave-jersey.zip)
[jersey-app.zip](https://github.com/openzipkin/brave/files/316281/jersey-app.zip)

**Comment by anujkumarnag** [comment]
Closing this and creating a new one with screen shot and sample application.
Now the traces are being logged and can be seen from web ui but the tree structure is not getting generated.
