### ISSUE TITLE
Add JDBC tracing support

### ISSUE THREAD

**Issue by ewhauser** [openzipkin/brave#201]
This issue is to discuss potential options for adding JDBC support to brave.  JDBC does not supply built in hooks for intercepting the execution of SQL calls, so a long held pattern for tracing JDBC calls has been to use a driver spy.  There a large number of these libraries in existence:

https://github.com/p6spy/p6spy
https://github.com/brunorozendo/log4jdbc-log4j2
https://github.com/arthurblake/log4jdbc

Out of these, p6spy seems to be the most attractive option:

* Apache 2 licensed
* Binaries available via Maven Central
* Zero dependencies
* Hooks available for attaching a generic event listener to JDBC actions (https://github.com/p6spy/p6spy/blob/master/src/main/java/com/p6spy/engine/event/JdbcEventListener.java, https://github.com/p6spy/p6spy/blob/master/src/main/java/com/p6spy/engine/logging/LoggingEventListener.java) where Zipkin traces could be added
* Seems actively maintained

The downside to using it seems to be that the user has to knowingly configure their JDBC connection string and supply a `spy.properties` file specific to brave.  Given the lack of hooks in JDBC, there really is not a way to avoid some level of end user configuration.

**Comment by adriancole** [comment]
Sounds reasonable.. how does this actually work, though? is it likely to interfere with other code (magic bytecode weaving etc?)

I like this better than framework-specific choices (like jooq), as there's just so many of them!

**Comment by ewhauser** [comment]
No byte code magic. The driver spy proxies the real JDBC driver. So instead of defining your connection string like:

```
jdbc:mysql://127.0.0.1/db
```

You would do:

```
jdbc:p6spy:mysql://127.0.0.1/db
```

**Comment by adriancole** [comment]
clever!

and how does it access state? I remember the mysql one had an issue where
it needed to read a static variable to collaborate with brave's state..

**Comment by ewhauser** [comment]
Are you talking about how to access the `Brave` instance?  I see that the MySQL one requires static injection of the `ClientTracer` (https://github.com/openzipkin/brave/blob/master/brave-mysql/src/main/java/com/github/kristofa/brave/mysql/MySQLStatementInterceptor.java#L25). Not really sure I see a way around this, although a [ServiceLoader](http://docs.oracle.com/javase/6/docs/api/java/util/ServiceLoader.html) might be a cleaner way to allow pluggable discovery.

**Comment by adriancole** [comment]
@ewhauser yeah I was thinking about this part.. it crops up whenever we are doing something with jdbc urls

**Comment by ewhauser** [comment]
We could do something like this where we utilize ServiceLoader:

```java
interface BraveLocator { 
  Brave locate()
}

class StaticBraveLocator implements BraveLocator {
  static void setBrave(Brave brave) { ... }
}

class BraveDiscovery {
  Brave find() {
    locator = serviceLoaders.sort().findFirst() // where StaticBraveLocator is last
    locator.locate()
  }
}
```

This would allow clients to provide pluggable methods of locating the Brave instance.

**Comment by eirslett** [comment]
FINN already instruments JDBC with Brave, using an interceptor for the Tomcat JDBC pool. @NegatioN knows the details

**Comment by ewhauser** [comment]
@eirslett: There are a bunch of vendor specific and framework specific ways of doing SQL tracing.  For instance, there are hooks in jooq, Hibernate, connection pooling libs, app servers, etc. that would all allow you to build JDBC tracing.  However, trying to support all of the different use cases would a significant amount of engineering effort.

The goal here is to provide a solution that works regardless of your implementation (or at least that of the underlying drivers that are supported by p6).

**Comment by ewhauser** [comment]
Not ready for a PR yet, but I've got an initial prototype of this available here:

https://github.com/ewhauser/brave/commit/3f37981432c7dd5e5657c3552649732e05e0e1af

The prototype depends on the latest `SNAPSHOST` of p6spy so that would need to get resolved before merging.

**Comment by adriancole** [comment]
PS on "how to locate brave"

This is probably fodder for a different PR, but we can think about how
finagle does it.

Finagle uses two contexts: one for finding the tracer(s) (local traceCtx)
and one for finding the current span (broadcast idCtx).

At bootstrap, a null-tracer is associated with the local context,
overridden lazily by service loader, though you can also override it at
runtime (via what feels like a thread-local).

In the case of JDBC, where users control the threadpools, we could probably
get by with a thread local approach.


private case class TraceCtx(terminal: Boolean, tracers: List[Tracer]) {
def withTracer(tracer: Tracer) = copy(tracers=tracer :: this.tracers)
def withTerminal(terminal: Boolean) =
if (terminal == this.terminal) this
else copy(terminal=terminal)
}
private object TraceCtx {
val empty = TraceCtx(false, Nil)
}
private[this] val traceCtx = new Contexts.local.Key[TraceCtx]

**Comment by adriancole** [comment]
PS on "how to locate brave"

This is probably fodder for a different PR, but we can think about how
finagle does it.

Finagle uses two contexts: one for finding the tracer(s) (local traceCtx)
and one for finding the current span (broadcast idCtx).

At bootstrap, a null-tracer is associated with the local context,
overridden lazily by service loader, though you can also override it at
runtime (via what feels like a thread-local).

In the case of JDBC, where users control the threadpools, we could probably
get by with a thread local approach.

```scala
private case class TraceCtx(terminal: Boolean, tracers: List[Tracer]) {
def withTracer(tracer: Tracer) = copy(tracers=tracer :: this.tracers)
def withTerminal(terminal: Boolean) =
if (terminal == this.terminal) this
else copy(terminal=terminal)
}
private object TraceCtx {
val empty = TraceCtx(false, Nil)
}
private[this] val traceCtx = new Contexts.local.Key[TraceCtx]
```

https://github.com/twitter/finagle/blob/fc321f804a22a695ec419902505c8509ffbd594d/finagle-core/src/main/scala/com/twitter/finagle/tracing/Trace.scala

**Comment by adriancole** [comment]
PS on "how to locate brave"

This is probably fodder for a different PR, but we can think about how
finagle does it.

Finagle uses two contexts: one for finding the tracer(s) (local traceCtx)
and one for finding the current span (broadcast idCtx).

At bootstrap, a null-tracer is associated with the local context,
overridden lazily by service loader, though you can also override it at
runtime (via what feels like a thread-local).

In the case of JDBC, where users control the threadpools, we could probably
get by with a thread local approach.

```scala
private case class TraceCtx(terminal: Boolean, tracers: List[Tracer]) {
def withTracer(tracer: Tracer) = copy(tracers=tracer :: this.tracers)
def withTerminal(terminal: Boolean) =
if (terminal == this.terminal) this
else copy(terminal=terminal)
}
private object TraceCtx {
val empty = TraceCtx(false, Nil)
}
private[this] val traceCtx = new Contexts.local.Key[TraceCtx]
```

https://github.com/twitter/finagle/blob/fc321f804a22a695ec419902505c8509ffbd594d/finagle-core/src/main/scala/com/twitter/finagle/tracing/Trace.scala

**Comment by adriancole** [comment]
ps just bumped the zipkin dep to get `TraceKeys.SQL_QUERY` https://github.com/openzipkin/brave/commit/d14ba2ec3f007759f14ffcc14d55228a41f23264
