### ISSUE TITLE
Provide hook for request adapters to supply client address annotation

### ISSUE THREAD

**Issue by ewhauser** [openzipkin/brave#205]
From a review of #204, it was mentioned that frameworks supplying the client IP should be setting the "CA" annotation on the server span.  With the current request adapter pattern, this is not possible because the interceptor adds the annotation.  This issue will track the work of exposing hooks for the frameworks add this information.  Original comment below:  

> The [ServerRequestInterceptor](https://github.com/openzipkin/brave/blob/master/brave-core/src/main/java/com/github/kristofa/brave/ServerRequestInterceptor.java#L49) makes the call to `setServerReceived()`.  Because of the way the [ServerRequestAdapter](https://github.com/openzipkin/brave/blob/master/brave-core/src/main/java/com/github/kristofa/brave/ServerRequestAdapter.java) interface is setup, there is not a hook to set the client address annotation prior to `setServerReceived()` being called.
> 
> If you think it makes sense, I can add an additional method to `ServerRequestAdapter` that allows implementors to optionally supply the client info so it can be used by `ServerRequestInterceptor`.  We could also use this to enhance the `HttpServerRequestAdapter` as well using the various methods to pull client IPs (i.e. [ServletRequest.html#getRemoteAddr()](http://docs.oracle.com/javaee/6/api/javax/servlet/ServletRequest.html#getRemoteAddr%28%29) and well known proxy headers such as `X-Forwarded-For`)

**Comment by adriancole** [comment]
all instrumentation now add client address (unless they have no means to)
