### ISSUE TITLE
Add service locator for Brave

### ISSUE THREAD

**Issue by ewhauser** [openzipkin/brave#206]
Some frameworks that we want to integrate with Brave instantiate control the instantiation of their objects and do not provide capabilities for injecting the Brave instance.  Examples of this include `brave-mysql` and `brave-jdbc`.  The service locator should provide the ability to provide the first instantiated instance of the Brave object and any subsequent instances.  

From @adriancole on #201:

> Finagle uses two contexts: one for finding the tracer(s) (local traceCtx)
> and one for finding the current span (broadcast idCtx).
> 
> At bootstrap, a null-tracer is associated with the local context,
> overridden lazily by service loader, though you can also override it at
> runtime (via what feels like a thread-local).
> 
> In the case of JDBC, where users control the threadpools, we could probably
> get by with a thread local approach.
> 
> ``` scala
> private case class TraceCtx(terminal: Boolean, tracers: List[Tracer]) {
> def withTracer(tracer: Tracer) = copy(tracers=tracer :: this.tracers)
> def withTerminal(terminal: Boolean) =
> if (terminal == this.terminal) this
> else copy(terminal=terminal)
> }
> private object TraceCtx {
> val empty = TraceCtx(false, Nil)
> }
> private[this] val traceCtx = new Contexts.local.Key[TraceCtx]
> ```
> 
> https://github.com/twitter/finagle/blob/fc321f804a22a695ec419902505c8509ffbd594d/finagle-core/src/main/scala/com/twitter/finagle/tracing/Trace.scala

**Comment by adriancole** [comment]
While this doesn't make a service locator, hopefully #379 will make the interaction pattern possible. Let me know if not.
