### ISSUE TITLE
Tracing microservices that use Kafka

### ISSUE THREAD

**Issue by jpiechowka** [openzipkin/brave#211]
Is there a documentation or guide on how to setup Brave to trace microservices that use Kafka to communicate? I would like to know how to configure it to work, some example would be perfect.

**Comment by adriancole** [comment]
this is a tricky one, but I have an experiment on this. I'll post it in a
bit. It requires you to use kafka keys for propagation.

**Comment by piechowka** [comment]
Perfect! Thank you very much for this @adriancole

**Comment by adriancole** [comment]
@jpiechowka how's it been going?

**Comment by jpiechowka** [comment]
It works well for me. But we decided to postpone using it on production right now. Priority is to implement tracing in our JavaScript front end and Java back end application.

**Comment by adriancole** [comment]
Now that Kafka 0.11 supports headers, we can likely formalize support for tracing using B3 (like many do for rabbit etc) http://www.mirrorservice.org/sites/ftp.apache.org/kafka/0.11.0.0/RELEASE_NOTES.html

**Comment by adriancole** [comment]
note that SPMC tracing would require consumers to use the incoming span ID as the parent (not share the trace ID as we do in normal and one-way RPC)

**Comment by adriancole** [comment]
https://github.com/openzipkin/brave/tree/master/instrumentation/kafka-clients is going out as Brave 4.6 thanks to @ImFlog
