### ISSUE TITLE
Documentation for how sample rate gets propagated

### ISSUE THREAD

**Issue by conorgriffin** [openzipkin/brave#214]
I can't seem to find anything that categorically states how sample rate gets propagated from client to server.

For example, if I have a single client `c1` and a single server `s1`.

Let's say `c1` is configured to sample 1% of requests like so:

```
HttpSpanCollector httpSpanCollector = HttpSpanCollector.create("http://localhost:9411/", new EmptySpanCollectorMetricsHandler());
Brave brave = new Brave.Builder(consumerQName.toString()).spanCollector(httpSpanCollector).traceSampler(Sampler.create(0.01f)).build();
CloseableHttpClient client = HttpClients.custom().addInterceptorFirst(new BraveHttpRequestInterceptor(new ClientRequestInterceptor(brave.clientTracer()), new DefaultSpanNameProvider()))
                            .addInterceptorFirst(new BraveHttpResponseInterceptor(new ClientResponseInterceptor(brave.clientTracer())))
                            .build();
```

So for 1% of requests, `c1` will sample the request and set the request headers.

Likewise, let's say `s1` is configured to sample 1% or requests like so:
```
@Bean
FilterRegistrationBean zipkinTracingServletFilter() {
    FilterRegistrationBean filterRegistrationBean = new FilterRegistrationBean();
    HttpSpanCollector httpSpanCollector = HttpSpanCollector.create("http://localhost:9411/", new EmptySpanCollectorMetricsHandler());
    Brave brave = new Brave.Builder(SERVICE_QNAME.toString()).traceSampler(Sampler.create(0.01f)).spanCollector(httpSpanCollector).build();
    filterRegistrationBean.setFilter(new BraveServletFilter(brave.serverRequestInterceptor(), brave.serverResponseInterceptor(), new DefaultSpanNameProvider()));
    filterRegistrationBean.addUrlPatterns("/*");
    return filterRegistrationBean;
}
```

So for 1% of requests, `s1` will sample the request.

However, I'm not clear on what happens if the 1% of client requests doesn't line up with the 1% of server requests.

i.e. - if `c1` decides to sample an outbound request to `s1` but `s1` doesn't decide to sample the same request then you won't get an end-to-end trace.  So does `s1` just trace any requests where it sees the request headers are set?

**Comment by adriancole** [comment]
So the documentation on Sampler says this:

/**
 * Sampler is responsible for deciding if a particular trace should be
"sampled", i.e. whether the
 * overhead of tracing will occur and/or if a trace will be reported
to the collection tier.
 *
 * <p>Zipkin v1 uses before-the-fact sampling. This means that the
decision to keep or drop the
 * trace is made before any work is measured, or annotations are
added. As such, the input parameter
 * to zipkin v1 samplers is the trace ID (64-bit random number).
 *
 * <p>The instrumentation sampling decision happens once, at the root
of the trace, and is
 * propagated downstream. For this reason, the decision needn't be
consistent based on trace ID.
 */

The "happens once" and "propagated downstream" parts are important. That
means that the client and the server don't make separate decisions. If a
client creates the trace, it should be propagating that decision downstream
(in the case of http via the X-B3-Sampled header). When a server reads that
header, it honors the decision.

Make sense?

**Comment by conorgriffin** [comment]
OK, and if the server is also acting as a client, it will propagate the trace state into its own client requests to the next service regardless of it's own sample rate?

**Comment by adriancole** [comment]
In-process, ServerClientAndLocalSpanState stores the sampled state and
any parentage. This is implemented with thread locals.

state.sampled() is checked before creating a new client span.

**Comment by conorgriffin** [comment]
OK, think I got it.  Thanks

**Comment by adriancole** [comment]
sure thing!
