### ISSUE TITLE
Add support for Spark Framework

### ISSUE THREAD

**Issue by jpiechowka** [openzipkin/brave#217]
[Spark](http://sparkjava.com) is very simple framework to create web applications in Java. It would be great to support it in Brave. Earlier, I posted an issue about tracing in spark here: [GitHub.com/openzipkin/zipkin](https://github.com/openzipkin/zipkin/issues/1235)

**Comment by adriancole** [comment]
to instrument the Spark framework, something like below would be needed:
https://github.com/openzipkin/brave/blob/fd3cdb921964a0d7164c29141fe6aac8099ae4cf/brave-spring-web-servlet-interceptor/src/main/java/com/github/kristofa/brave/spring/ServletHandlerInterceptor.java
maybe using this? https://github.com/perwendel/spark/blob/master/src/main/java/spark/Filter.java
Here are details on brave's hooks: https://github.com/openzipkin/brave/tree/master/brave-http

**Comment by adriancole** [comment]
@perwendel do you know anyone who might be interested in making spark traceable with zipkin natively?

**Comment by yichen** [comment]
Please count me in as well. Spark is very simple to use so we are adopting it for micro services at work.

**Comment by songxin1990** [comment]
Recently,I meet this problem too.Wingtips is a solution base on Dapper,not fit with Zipkin.Here is my solution.

**Comment by adriancole** [comment]
looks like picking up steam! anyone want to contribute an impl (or put one
in spark?)

**Comment by songxin1990** [comment]
@adriancole  just wait for a minute,I will finish this job,add a module for spark framework.

**Comment by songxin1990** [comment]
@adriancole  I just submit a pull request . If there is something wrong , let me know Thanks. : )

**Comment by adriancole** [comment]
this is in, and also polished for Brave 4.3, too. thanks @songxin1990!
