### ISSUE TITLE
Make sure that Brave and all dependencies are compatible with Java 1.6  

### ISSUE THREAD

**Issue by ivansenic** [openzipkin/brave#225]
At the moment classes in Brave are compiled with the target 1.7 which makes library not working on any JVM under 1.7. Now I understand that depending on Java 1.6 is limiting programming options in Brave itself, but with this you are turning away all the people that are still running on Java 1.6 or lower. And I am sure that there are numerous enterprise systems that still use old Java versions (I know several big systems still going with 1.5 :-1: ).

**Comment by adriancole** [comment]
This is a regression. I accidentally screwed this up. Will fix

**Comment by adriancole** [comment]
Here's the thing I broke https://github.com/openzipkin/brave/pull/131

**Comment by adriancole** [comment]
OK this requires extracting a jar in zipkin upstream with only the model and constants. This may be tricky due to Codec stuff.

**Comment by adriancole** [comment]
https://github.com/openzipkin/brave/pull/227 on the way!

**Comment by adriancole** [comment]
very sorry about breaking this. 3.10.0 is on the way to maven central now where this is fixed.
