### ISSUE TITLE
Migrate from SpanCollector to zipkin-reporter-java's Reporter

### ISSUE THREAD

**Issue by adriancole** [openzipkin/brave#228]
We started zipkin-reporter-java in efforts to stop the copy/paste re-use across libraries like Brave and HTrace. Once https://github.com/openzipkin/zipkin-reporter-java is stable, we should migrate towards it as it will end up better tested. This would imply moving from SpanCollector to zipkin-reporter-java's Reporter type.

**Comment by devinsba** [comment]
How imminent would you say this is @adriancole ? I have a partial implementation of a new span collector that I should be finishing up some time in the next month. Should I consider adding it to that project instead?

**Comment by adriancole** [comment]
I think the design will settle down in a week.

Thanks for the heads up. What does your collector do?

**Comment by devinsba** [comment]
I asked about it a while ago. It publishes to an Amazon SNS topic allowing
us to possibly fan out to multiple SQS queue for stream processing, etc.

**Comment by adriancole** [comment]
ahh ok. Will you have a server-side collector, too? It probably doesn't
make sense to host only side of a transport.

**Comment by devinsba** [comment]
Yeah. I've got an SQS collector also. Need to polish both up before creating pull requests. I'll create the reporter one in the other repo though since you should have that stable before I get back to it

Get Outlook for iOS




On Mon, Aug 22, 2016 at 8:36 PM -0400, "Adrian Cole" <notifications@github.com> wrote:










ahh ok. Will you have a server-side collector, too? It probably doesn't

make sense to host only side of a transport.



On Tue, Aug 23, 2016 at 8:33 AM, Brian Devins <notifications@github.com>

wrote:

**Comment by adriancole** [comment]
I think long-term, we'd probably want a repo in OpenZipkin called
zipkin-transport-aws or similar, which would have a zipkin.reporter.Sender
and zipkin.collector.Collector component. That way, people can use the
whole thing, vs being teased with one-side :)

Make sense to you? If you're open to it, I can create a repo for you and
add you as a writer.

**Comment by devinsba** [comment]
Yeah. I'm not sure I can get any put together just yet but that would be nice. Then I only have to fork one project

**Comment by felixbarny** [comment]
Is there a public WIP for this? That would help me implementing a reporter for [stagemonitor](https://github.com/stagemonitor/stagemonitor) :)

**Comment by adriancole** [comment]
Thanks for the interest.

zipkin-reporter-java 0.4.0 should be a interop-grade build at this point. I
can give a go at brave tomorrow unless someone beats me to it! I'll make
sure it gets on its way to maven central within the hour.

**Comment by adriancole** [comment]
here's the impl https://github.com/openzipkin/brave/pull/248

**Comment by bookoo-billy** [comment]
Looks like the master branch README.md needs to be updated for the migration from spanCollector to reporter.  Anyway I can help out with that?  I'm sort of new to this project and think some of the documentation could use cleaning up in general.

**Comment by adriancole** [comment]
@bookoo-billy I assume you are referring to brave-core/README.

sounds good, just be careful to use links as opposed to replicating the content on https://github.com/openzipkin/zipkin-reporter-java

I think the content for the readme could be lifted from javadoc, pasted for convenience here. Feel free to have a go!

```java

        /**
         * Controls how spans are reported. Defaults to logging, but often an {@link AsyncReporter}
         * which batches spans before sending to Zipkin.
         *
         * The {@link AsyncReporter} includes a {@link Sender}, which is a driver for transports
         * like http, kafka and scribe.
         *
         * <p>For example, here's how to batch send spans via http:
         *
         * <pre>{@code
         * reporter = AsyncReporter.builder(URLConnectionSender.create("http://localhost:9411/api/v1/spans"))
         *                         .build();
         *
         * braveBuilder.reporter(reporter);
         * }</pre>
         *
         * <p>See https://github.com/openzipkin/zipkin-reporter-java
         */
        public Builder reporter(Reporter<zipkin.Span> reporter) {
            this.reporter = checkNotNull(reporter, "reporter");
            return this;
        }
```

**Comment by adriancole** [comment]
things are cleaned up now, I think. We still publish the old collectors, but they are under an archive directory
