### ISSUE TITLE
How to use brave apache http interceptor

### ISSUE THREAD

**Issue by workmonitored** [openzipkin/brave#255]
The current apache http interceptor is talking about creating http client with an example but the example is not clear. This is a spring boot application where I have to intercept apache http client calls to add tracing information. Any help is appreciated.

Looks like the constructor has changed for the request interceptor. I have added a brave singleton for the app and used it to created a http client bean which is used in other parts of the project.However when spring tries to create a final response, I get an illegalaccessexception. This is a bit weird and might be due to conflicting dependencies? Will research more...

**Comment by adriancole** [comment]
did you come up with clarity on this topic (sharing your thoughts might help others)

**Comment by workmonitored** [comment]
It turned out fairly easy. However I left my prior workplace and it has been a while. The solution for spring boot is to expose a simple apacheHttpClient bean which then during creation will use the custom code to inject zipkin into the http headers. Spring already exposes zipkin where you can extract the existing trace info or create new one. For my purpose I just needed to pass the trace info when we were calling since our end points where we receive were written in spring so that worked out of the box for spring with zipkin integration.

**Comment by adriancole** [comment]
gotcha, so you ended up using spring-cloud-sleuth instead. thx for the feedback
