### ISSUE TITLE
Provide OSGi bundles during brave build

### ISSUE THREAD

**Issue by cschneider** [openzipkin/brave#256]
Currently the brave artifacts are no OSGi bundles. I would like to use brave in Apache Karaf but this makes it a lot harder.

If you are interested I can provide a pull request for some initial OSGi support.

**Comment by adriancole** [comment]
sounds fair. I recall this recently you thinking something similar here?

https://github.com/OpenFeign/feign/pull/450/files

**Comment by cschneider** [comment]
Yes. Basically adding the maven-bundle-plugin or bnd-maven-plugin to the parent and tuning it in the individual projects if necessary. I will go ahead and create a PR

**Comment by adriancole** [comment]
sgtm thanks
