### ISSUE TITLE
MySQLStatementInterceptor records many unexpected queries

### ISSUE THREAD

**Issue by theopengroup** [openzipkin/brave#259]
When use statementInterceptors to record the SQL queries, many unexpected queries are also recorded, such as "SET autocommit=1", "SELECT @@session.tx_isolation", and so on. 
Is there any good place to Intercept and record expected queries, where we can also easily get the SQL with values, get the ip address from jdbc url?

**Comment by adriancole** [comment]
I'd expect people to use p6spy moving forward as it isn't mysql
specific, but the point remains.

Are you saying there are new traces recorded for these, or are you
saying there are multiple child spans for things like SET autocommit?
I suspect the latter is somewhat intuitive as it would account for
latency in the trace.

**Comment by adriancole** [comment]
one way could be to have configuration which decides if a specific
operation should be an annotation vs a new child span. for example,
you could argue that set tx etc doesn't need the detail of a span.

**Comment by theopengroup** [comment]
Yes, there are multiple child spans for things like SHOW FULL TABLES FROM `xxx LIKE 'PROBABLYNOT', which are generated by c3p0.

**Comment by adriancole** [comment]
ping any advice on where to go from here?
