### ISSUE TITLE
Support for lazy evaluation of expensive binary annotations

### ISSUE THREAD

**Issue by AlejandroRivera** [openzipkin/brave#260]
It'd be nice if there was a way to add binary annotations to spans in such a way that the annotation value is only computed if the trace is being sampled.

For example:

```
localTracer.submitBinaryAnnotation("foo", computeExpensiveValue());
```

would become:

```
localTracer.submitBinaryAnnotation("foo", () -> computeExpensiveValue());
```

Without this feature support, we're forced to do:

```
if (Boolean.TRUE.equals(tracer.serverSpanThreadBinder().getCurrentServerSpan().getSample())) {
   localTracer.submitBinaryAnnotation("foo", computeExpensiveValue());
}
```

**Comment by adriancole** [comment]
@schlosna @eirslett @NegatioN @kristofa @ewhauser anybody else interested in this?

**Comment by NegatioN** [comment]
I don't think we have many computationally expensive values being traced at this point, but I wouldn't object to having something that solves that problem. 👍 
However I'm also curious about what some examples of these computationally expensive values are? On the top of my head I can't think of a use-case where that might happen for us in the near future.

**Comment by adriancole** [comment]
one I hear about often is address resolution, but also interested in the
motivation!

**Comment by AlejandroRivera** [comment]
For me, the need arose from having MongoDB queries as a binary annotation for the span.
The MongoDB query would be a BsonDocument (similar to JsonNode from Jackson), which could be a very big structure. To present it as a String, serialization needs to take place and that's the expensive operation I'd like to avoid unless absolutely needed.

**Comment by adriancole** [comment]
>
> For me, the need arose from having MongoDB queries as a binary annotation
> for the span.
> The MongoDB query would be a BsonDocument (similar to JsonNode from
> Jackson), which could be a very big structure. To present it as a String,
> serialization needs to take place and that's the expensive operation I'd
> like to avoid unless absolutely needed.
>
thx.. unrelated, but is any of this code on github? I'd like to see if for
vetting a different idea.

**Comment by AlejandroRivera** [comment]
I've extracted the relevant bits here: https://gist.github.com/AlejandroRivera/381cd2121462bd3d90f1e5253899c876
Hope it helps :)

**Comment by adriancole** [comment]
I think this design I'm working on should help address this issue https://github.com/openzipkin/brave/issues/284

**Comment by adriancole** [comment]
Brave 4.3 is syncing now and includes HttpTracing component. This lazy tags by default
