### ISSUE TITLE
How to use ServerRequestAdapter?

### ISSUE THREAD

**Issue by hongjn** [openzipkin/brave#262]
I have implemented the interface `ServerRequestAdapter`, but I found code below
`requestInterceptor.handle(new HttpServerRequestAdapter(new HttpServerRequest() {
...` 
in class `ServletHandlerInterceptor`.

This place use HttpServerRequestAdapter directly, I want to know how to use the interface `ServerRequestAdapter`.

Thanks.

**Comment by adriancole** [comment]
>
> This place use HttpServerRequestAdapter directly, I want to know how to
> use the interface ServerRequestAdapter.
>
The only purpose of the adapters is to provide data to client or server
interceptors.

https://github.com/openzipkin/brave/tree/master/brave-core#instantiating-brave-api

The client and server interceptors encapsulate common instrumentation
tasks, and are what various integrations like grpc, jaxrs, servlet etc are
composed of. In other words, you'd use ServerRequestAdapter as an input
when you are making something similar to brave-grpc (because whatever
library you are using isn't already supported in brave)

**Comment by hongjn** [comment]
What I want to do is adding extra infomation to the trace data, but I don't know how? Pls help me.
Thanks.

**Comment by dragontree101** [comment]
brave api  has `submitBinaryAnnotation` or `submitAnnotation`  could add extra information

**Comment by hongjn** [comment]
Thanks. @dragontree101 
Do you have some demos ?

**Comment by dragontree101** [comment]
you could read brave's example https://github.com/openzipkin/brave-resteasy-example

**Comment by hongjn** [comment]
@dragontree101 @adriancole 
I am using zipkin and brave in my production system, it is very wonderful.
What I need is to adding some extra key/value in trace data. I have read brave source several times, it seems that I must custom class like `ServletHandlerInterceptor.java` and `ServerRequestInterceptor`. I don't think it's a good way.

**Comment by dragontree101** [comment]
@hongjn  i think you must create key/value by yourself and send to zipkin by brave.  
in my company we use javaagent to create key/value and some other import data like `newrelic`.

**Comment by hongjn** [comment]
@dragontree101 

> send to zipkin by brave

how? can you show me the code, I am finding a good way. 
Thanks a lot.

**Comment by dragontree101** [comment]
i can't give you my code,  sorry :(
i only tell you that we send to zipkin by javaagent  
if i use javaagent i could create data what i want
and my english is not well, if use chinese maybe describe more clearly

**Comment by adriancole** [comment]
If you want to add more key/value data to a trace during a server
request, then you can use ServerTracer. There's no requirement to use
ServerRequestInterceptor, just that it handles common tasks for you.

**Comment by hongjn** [comment]
Thanks!
How to use ServerTracer? Do you have an example?

**Comment by adriancole** [comment]
here's one
https://github.com/henrikno/brave-jersey-guice-example/blob/master/src/main/java/no/slash/brave/example/TestResource.java#L51

**Comment by hongjn** [comment]
very thanks.
