### ISSUE TITLE
Can we package zipkin dependencies as OSGi bundles

### ISSUE THREAD

**Issue by thusithathilina** [openzipkin/brave#266]
It would be great if we can package zipkin dependencies as OSGi bundles.

**Comment by cschneider** [comment]
I am already running zipkin in OSGi. What dependencies are you missing?

**Comment by thusithathilina** [comment]
I mean all the zipkin components are packaged as jar (e.g. https://github.com/openzipkin/brave/blob/master/brave-core/pom.xml#L10). IMHO it would be great they can be packaged as OSGi bundles. Then we don't need to create separate OSGi bundle to use zipkin in OSGi environment.

**Comment by cschneider** [comment]
This is already the case. If you look at the resulting jar files they already contain OSGi meta data now.

**Comment by thusithathilina** [comment]
@cschneider Thank you for the info. I just downloaded the https://mvnrepository.com/artifact/io.zipkin.brave/brave-core/3.15.0 and checked the MANIFEST.MF. But it doesn't contain any OSGi headers.
It only contains following
```
Manifest-Version: 1.0
Archiver-Version: Plexus Archiver
Built-By: travis
Created-By: Apache Maven 3.3.9
Build-Jdk: 1.8.0_65
```
Did I do something wrong?

**Comment by cschneider** [comment]
Just use the newest one 3.15.1. There is still an issue with this released version though. It does not export the private package com.github.kristofa.brave.internal but this package is used in some other brave modules. We are currently trying to find a way to make this work nicely.
See #271 

So first start with the newest release 3.15.1 and if you hit problems try the newest snapshot by building from the source of master. Any feedback about possible problems in OSGi is highly welcome.

If you need an example to start with take a look at https://github.com/cschneider/brave-osgi-example .
Currently it is at the state of simple brave api working with the kafka and Urlconnection senders.

I am currently working on full REST and SOAP logging and will update the example once I get it working.

**Comment by adriancole** [comment]
@cschneider can you look at all the new things in brave and make sure they are OSGi ok?

**Comment by ConradGroth** [comment]
The MANIFEST.MF of all bundles looked good until version 4.10.0. Starting with 4.10.1 the MANIFEST.MF of **some** bundles is incomplete. I guess it has something to do with [commit 2fea453e253a92bbc127390736dbc8545f16d1b6](https://github.com/openzipkin/brave/commit/2fea453e253a92bbc127390736dbc8545f16d1b6#diff-600376dffeb79835ede4a0b285078036) because there were only two commits between 4.10.0 and 4.10.1.
Following bundles are still ok:
- brave
- brave-instrumentation-http
- brave-instrumentation-rpc
Following bundles are **not** ok:
- brave-context-log4j12
- brave-instrumentation-httpclient
- brave-instrumentation-servlet
- brave-instrumentation-spring-webmvc
- brave-spring-beans
I didn't check any other bundles.

**Comment by jorgheymans** [comment]
@ConradGroth did you check these bundles against the latest 5.x release of brave or only 4.10 ?

**Comment by cschneider** [comment]
I think in some modules the jar plugin does not process the generated Manifest.
Is there a reason why the maven jar plugin in the parent does not have:
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.1.0</version>
                <configuration>
                    <archive>
                        <manifestFile>${project.build.outputDirectory}/META-INF/MANIFEST.MF</manifestFile>
                    </archive>
                </configuration>
            </plugin>
I see that this config is present in some poms but not in others.

**Comment by jorgheymans** [comment]
it would be easy to try it out i guess, but i know nothing about OSGI. Are you saying that the modules that are OSGI compliant have above config and those that are not don't ?  

https://maven.apache.org/shared/maven-archiver/examples/manifestFile.html

**Comment by adriancole** [comment]
I guess the parent should be the one having the below, with a big comment why, huh :)

`<manifestFile>${project.build.outputDirectory}/META-INF/MANIFEST.MF</manifestFile>`

**Comment by adriancole** [comment]
oh I see.. I think due to the huge manifest files the plugin creates by default (and certain use of internal types), we only cherry-picked the important modules and created bnd files for each.

**Comment by adriancole** [comment]
I will backfill these.

**Comment by adriancole** [comment]
some refactoring needed as this is actually beyond tedious https://github.com/openzipkin/brave/pull/1009

**Comment by ConradGroth** [comment]
@jorgheymans I checked the 5.8.0 bundles.
