### ISSUE TITLE
com.github.kristofa.brave.internal.Nullable is internal but used by other brave modules

### ISSUE THREAD

**Issue by cschneider** [openzipkin/brave#268]
I can not install brave-http in OSGi as it refers to the package com.github.kristofa.brave.internal. It seems that is uses the Nullable anntoation.

So there are two ways to fix this:
1. export the internal package
2. move Nullable to com.github.kristofa.brave as it is used outside brave core

Option 2 is the cleaner solution but it requires bigger changes. What do you think?
I will provide a PR for solution 1 first as it is easy to do.

**Comment by adriancole** [comment]
Can you help me understand why we have to handle this at all? We don't
inspect the annotation at runtime, and nothing else does.

**Comment by adriancole** [comment]
the only thing that uses this is auto-value (at compile time)

**Comment by adriancole** [comment]
hoping OSGi is reasonable enough to accept source retention as a solution :)

https://github.com/openzipkin/brave/pull/275

**Comment by adriancole** [comment]
if Util is a problem, I'd almost rather use shade to copy the 2 checkNotNull methods to where they are used vs export the package internal only to support them. Internal is internal for brave code, and it is a shame there's no solution for this problem beside blanket exporting.
