### ISSUE TITLE
Manually logging binary annotations

### ISSUE THREAD

**Issue by conorgriffin** [openzipkin/brave#285]
I have a need to record a 'correlation ID' that comes in as an http header from an external client that is not instrumented with zipkin.  When the service that the external client is calling needs to make an outbound client call itself, I was thinking that I would record this correlation ID on the first span as a binary annotation.  But it's not clear to me how to record binary annotation and how they get delivered through whatever SpanCollector implementation I've chosen.  Can someone help me understand how I record this 'correlation ID' as a binary annotation and how it gets delivered alongside the rest of the span data from this host?

**Comment by adriancole** [comment]
interesting timing. right now, we have a design going on which directly affects this use case. should be up soon https://github.com/openzipkin/brave/issues/284

In the mean time, you'd have to know which library you are using and extend its `HttpServerRequestAdapter.requestAnnotations()` to also return the correlation id.

**Comment by adriancole** [comment]
Brave 4.3 includes a component `HttpTracing` which allows you to change any http tagging policy generically
