### ISSUE TITLE
Create Apache Karaf features for brave

### ISSUE THREAD

**Issue by cschneider** [openzipkin/brave#291]
The first step for using brave in OSGi is already done by making the brave jars bundles. Still it can be a lot of effort to install all the bundles in OSGi. At least on Apache Karaf we can make this a lot easier by maintaining a feature repo file. This lists the bundles for the modules of brave and allows to install them using just a few commands or config settings in karaf.

See the [feature file in my demo project](https://github.com/cschneider/brave-osgi-example/blob/master/bravetest/features.xml) for an example  for an example.

We can manage these feature files either in karaf or in the source project. I trypically prefer to have them in the source project as then users are not limited to a certain brave version that comes with the karaf version. It also makes sure users can leverage the newest brave version as soon as it is out.

Of course managing the feature file at brave is problematic as the core brave developer will not test on OSGi. So I plan to also supply pax exam based tests that install the features and make sure they work

**Comment by adriancole** [comment]
This issue was moved to openzipkin/brave-karaf#1

**Comment by cschneider** [comment]
The karaf feature will be created in its own repository. See https://github.com/openzipkin/brave-karaf
