### ISSUE TITLE
How to configure Zipkin URL/Port for brave ?

### ISSUE THREAD

**Issue by kavink** [openzipkin/brave#301]
Sorry, I could not figure out how to configure Zipkin URL/Port.  I followed documentation to include brave-jersey2 in my application as per the test case. https://github.com/openzipkin/brave/tree/master/brave-jersey2

I could not find instructions to configure the IP/Port of Zipkin for the library. Im guessing its some environment variable but finding it hard to find any mention about it. 

Please can someone help me ? i can then create a PR to update the README.

**Comment by adriancole** [comment]
Here's a paste of brave's javadoc.

/**
 * Controls how spans are reported. Defaults to logging, but often an
{@link AsyncReporter}
 * which batches spans before sending to Zipkin.
 *
 * The {@link AsyncReporter} includes a {@link Sender}, which is a
driver for transports
 * like http, kafka and scribe.
 *
 * <p>For example, here's how to batch send spans via http:
 *
 * <pre>{@code
 * reporter = AsyncReporter.builder(URLConnectionSender.create("http://localhost:9411/api/v1/spans"))
 *                         .build();
 *
 * braveBuilder.reporter(reporter);
 * }</pre>
 *
 * <p>See https://github.com/openzipkin/zipkin-reporter-java
 */



Brave is a library, not a framework, so it doesn't have things like
environment configuration bindings. Some use spring for this. If you look
at the example code, for example, it shows how to configure brave with
zipkin.

https://github.com/openzipkin/brave-webmvc-example
https://github.com/openzipkin/brave-webmvc-example/blob/master/src/main/java/brave/webmvc/WebTracingConfiguration.java#L36

**Comment by kavink** [comment]
Awesome! Thanks a lot!
