### ISSUE TITLE
How to get the span in my program

### ISSUE THREAD

**Issue by lijunyong** [openzipkin/brave#302]
I have a question,when I send a message by rest,how to get the rest span(get the rest traceId as the mq parentId) in mq program by ThreadLocalServerClientAndLocalSpanState,it's in brave package.

**Comment by adriancole** [comment]
In the current codebase, the only way to extract ids manually is to use
thread binders.

https://github.com/openzipkin/brave/blob/181a2f438e5142510cb72eefc723839bc525fe4d/brave-core/README.md#brave-and-multi-threading

I presume you are trying to make a messaging tracer and put the current
trace ids as message headers?

here's an example I played with though you probably don't want to use
binary for the headers. https://github.com/openzipkin/brave/pull/212

we will have a messaging solution in a couple weeks.

**Comment by lijunyong** [comment]
@adriancole It's not only a messaging tracer,it has rest and message tracer together,so I need get the rest span in message,then I konw the chain.

**Comment by adriancole** [comment]
ok let me know if you need more info

**Comment by lijunyong** [comment]
@adriancole how to get the rest span by BraveCallable or BraveRunnable,could you provide a example?thanks a lot

**Comment by adriancole** [comment]
brave.serverSpanThreadBinder().getCurrentServerSpan() will give you
the incoming span

brave.localSpanThreadBinder().getCurrentLocalSpan() will give you a
child-most span of that (or null if there are none)


There currently isn't an api to get whatever the most current span is,
so you have to do logic like check local first, then server.

In brave 4 we will have a single api.
https://github.com/openzipkin/brave/issues/180

**Comment by lijunyong** [comment]
@adriancole thank you very much, I can get the rest span,then set the traceid to message header,and get the rest and message chain.

**Comment by pradeep12vr** [comment]
@adriancole  I can see that brave offers binary annotations such as "cs", "cr", "ss" and "sr". but I don't see any documentation as to how to use them.

**Comment by adriancole** [comment]
please join https://gitter.im/openzipkin/zipkin for general q&a

github issues are for changes to brave

**Comment by songxin1990** [comment]
@pradeep12vr  cs represents client_send,cr represents  client receive,ss represents  server send,sr represents server receive . More details,you can read the source code of class  zipkin.Constants .

**Comment by adriancole** [comment]
Brave 4.3 is being synced now, and has extensive README and javadoc on how things work. Please re-open an issue if things aren't clear.
