### ISSUE TITLE
Proposal for Review: move Brave CXF integration under Apache CXF project

### ISSUE THREAD

**Issue by reta** [openzipkin/brave#313]
Hey Brave team,

You have done amazing job with Brave so far, and surely more to come in the future. What do you think about making Brave CXF integration an integral part of Apache CXF project? So you can focus on core Brave features while Apache CXF team could make Brave an alternative distributed tracing extension, along with Apache HTrace which is available at the moment. 

What do you think, team? Really appreciate your thoughts and opinions on that.
Thanks a lot!

Best Regards,
    Andriy Redko

**Comment by adriancole** [comment]
sounds very sensible and thanks for the offer! Action here would be to organize when a cutover would take place, making sure current users are aware etc.

cc @podsiedzik @cschneider

**Comment by cschneider** [comment]
I also support the move of the CXF integration to the Apache CXF project. I would keep the current integration in brave for some time even after the CXF one is complete but already mark it as deprecated. So people have some time to move over.

**Comment by reta** [comment]
@adriancole @cschneider The implementation for Brave integration in CXF has been completed. The documentation has been updated as well https://cwiki.apache.org/confluence/display/CXF20DOC/Using+OpenZipkin+Brave, including the migration steps (should be pretty straightforward).

I have also created this ticket https://issues.apache.org/jira/browse/CXF-7247 to natively support latest Brave 4.x API, it looks quite promising and concise.  

I think we could close this issue. @adriancole what would be the plan to deprecate `brave-cfx3` module? I would be happy to help with that.

Thanks.

**Comment by adriancole** [comment]
Hi! great news.

So, I think the next steps are to deprecate all public types in the CXF
module and put a header on the README saying that it is in apache now. We
can mention now, and also in the release notes of 4.1 that we'll eventually
stop publishing this variant (maybe in 4.2 or 4.3).

Maybe open a tracking issue for deprecate/removal of this, so that it is
more obvious? then, whatever follow-up work would be there.

Thanks so much for the help!
-A

**Comment by reta** [comment]
Thank a lot, @adriancole! 

Regarding deprecation, sounds like a great plan. To help you out guys, I can have a PR to update README (as you mentioned) and another one which will add @Deprecated annotation + comments, pointing out to appropriate Apache CXF API to migrate. Make sense?

Do you prefer to have an issue opened on GitHub's Brave repo or Apache CXF JIRA? I think Brave's one would be better place :)

Thanks!

**Comment by adriancole** [comment]
yeah the deprecation mostly impacts here, so an issue here will help. (ps be careful as there's a user named Deprecated! backtick to escape `@Deprecated`)

**Comment by reta** [comment]
Thanks a bunch for the hint, @adriancole ! Here we are: https://github.com/openzipkin/brave/issues/354. Could you please label the preferred `Brave` release you would like to see those changes coming? I will try to have the PRs submitted on time and against the right version. Thanks!

**Comment by adriancole** [comment]
you can deprecate at any time, we can drop in brave 4.1 or 4.2

users will need notes about what to do.. this should be sent to zipkin-user
google group as well I think

**Comment by reta** [comment]
Closing this guy in favor of https://github.com/openzipkin/brave/issues/354
