### ISSUE TITLE
brave-spring-web-servlet-interceptor should provide a way to start a ServerSpan in the Servlet filter chain

### ISSUE THREAD

**Issue by fakraemer** [openzipkin/brave#330]
We're using Spring MVC async support and thus were relying on ServletHandlerInterceptor to start and close the ServerSpan, but we're also using Spring Security which is configured in form of a Servlet Filter chain. The Spring MVC interceptor chain seems to be part of the Spring MVC servlet and is hence executed after the Servlet filter chain. As part of the Spring Security filter chain we were starting a client span to track an HTTP client fetching a public key from a remote. To retain the connection to the server span, we had to add a Servlet filter which starts the ServerSpan but relies on the ServletHandlerInterceptor to get the correct timings (including the work done in the Servlet filter chain) and have the connection to the ServerSpan (parent_span_id) in the client span we're starting in the Security filter chain. Here's the basic implementation:

~~~
public class BraveServerSpanReceivedFilter implements Filter {

    private static final String SERVLET_HANDLER_INTERCEPTOR_SERVER_SPAN_ATTRIBUTE = ServletHandlerInterceptor.class.getName() + ".server-span";
    private static final String ALREADY_FILTERED_ATTRIBUTE = BraveServerSpanReceivedFilter.class.getName() + ".FILTERED";

    private final ServerRequestInterceptor serverRequestInterceptor;
    private final SpanNameProvider spanNameProvider;
    private final ServerSpanThreadBinder serverSpanThreadBinder;

    public BraveServerSpanReceivedFilter(ServerRequestInterceptor serverRequestInterceptor, SpanNameProvider spanNameProvider, ServerSpanThreadBinder serverSpanThreadBinder) {
        this.serverRequestInterceptor = serverRequestInterceptor;
        this.spanNameProvider = spanNameProvider;
        this.serverSpanThreadBinder = serverSpanThreadBinder;
    }

    @Override
    public void init(FilterConfig filterConfig) throws ServletException {

    }

    @Override
    public void doFilter(ServletRequest request, ServletResponse response, FilterChain filterChain) throws IOException, ServletException {
        if (!Optional.ofNullable((Boolean) request.getAttribute(ALREADY_FILTERED_ATTRIBUTE)).orElse(Boolean.FALSE)) {
            serverRequestInterceptor.handle(new HttpServerRequestAdapter(new ServletHttpServerRequest((HttpServletRequest) request), spanNameProvider));
            request.setAttribute(SERVLET_HANDLER_INTERCEPTOR_SERVER_SPAN_ATTRIBUTE, serverSpanThreadBinder.getCurrentServerSpan());
            request.setAttribute(ALREADY_FILTERED_ATTRIBUTE, Boolean.TRUE);
        }
        filterChain.doFilter(request, response);
    }

    @Override
    public void destroy() {

    }
}
~~~

I was wondering if it would be possible to add support for starting a ServerSpan to the `brave-spring-web-servlet-interceptor` since I would imagine that this is a common problem. If it is not possible, could we at least expose the `com.github.kristofa.brave.spring.ServletHandlerInterceptor#HTTP_SERVER_SPAN_ATTRIBUTE` or offer a method to tell the interceptor to rely on an existing ServerSpan instead of creating one. Please let me know if I missed something obvious or there is a better solution.

**Comment by adriancole** [comment]
Thanks for the description. So are you saying you cannot currently order
the existing filter to go first?

**Comment by fakraemer** [comment]
@adriancole as far as I can see, the interceptor chain is executed as part of the Spring MVC servlet, and the Spring Security is a Servlet filter (hence executed before). I'm sure there are some options to configure Spring MVC differently (I'm no expert on these frameworks), but I guess unless this interceptor chain can be moved into a Servlet filter implementation the problem will remain. Maybe it's just best for us to wait until someone else runs into the issue, so feel free to treat this issue as fyi and close it.

**Comment by adriancole** [comment]
thanks for the explanation. not quite ready to close this as head's not completely around options that might be out there. there may be a way to get what we want.

**Comment by adriancole** [comment]
I think in this case you should use brave's servlet filter and not the web mvc one. see #396 for details on the general problem
