### ISSUE TITLE
the ServerSpan create method, I can't call

### ISSUE THREAD

**Issue by lijunyong** [openzipkin/brave#332]
The create method invisible in outside
``` 
static ServerSpan create(Span span) {
        return new AutoValue_ServerSpan(checkNotNull(span, "span"), true);
    }
```

**Comment by adriancole** [comment]
This is intentionally hidden and won't be un-hidden, especially as there's a new api for modifying spans. https://github.com/openzipkin/brave/tree/master/brave

**Comment by adriancole** [comment]
ps in case missed, here are the release notes. https://github.com/openzipkin/brave/releases/tag/4.0.0

if you have more usage questions on stuff, hop on gitter https://gitter.im/openzipkin/zipkin or on the user group https://groups.google.com/forum/#!forum/zipkin-user

we'll keep github issues for code changes

**Comment by lijunyong** [comment]
@adriancole But I want create my serverspan, how  to set in ThreadLocal

**Comment by adriancole** [comment]
What you are asking to do is intentionally unsupported, as it will break
the spans are recorded. Manually creating Brave 3 spans is not supported.

You can however get a reference to an existing Brave 3 server span and set
it later.
  * For example, when ServerTracer has created a span, you can save a
reference to that using the ServerSpanThreadBinder and re-attach it later

If you are using brave.Tracer api to create a span, I noticed it isn't
currently possible to convert this to a Brave 3 server span. If you want to
do this, let me know.

**Comment by lijunyong** [comment]
@adriancole I think you should open it,because it  is for others to use,for example I trace mq,I need set the span to currentServerSpan, when I receive message and send message both in the same method. I upgraded brave4,how to create ServerSpan and set to ThreadLocal.you are very nic,Thank you very much

**Comment by adriancole** [comment]
will update TraceAdapter and send a PR/release in an hour or two. good point

**Comment by lijunyong** [comment]
@adriancole Thanks a lot

**Comment by adriancole** [comment]
@lijunyong PTAL https://github.com/openzipkin/brave/pull/334

**Comment by lijunyong** [comment]
@adriancole get it

**Comment by adriancole** [comment]
>
> get it
>
you mean this will work for you? if so I will merge
