### ISSUE TITLE
Option to log traces to file only on demand.

### ISSUE THREAD

**Issue by kmaci3k** [openzipkin/brave#346]
I'm working on customization of brave in a way that each request had trace/span id (no matter if X-B3-Sampled header is set or not) but logging to file using SpanReported would be on demand (only when X-B3-Sampled header is set). 

Right now I was able to achieve that by using debug flag in Span (I set debug flag when X-B3-Sampled header is set). Would it be useful to have such feature in brave (logging to file only on demand) ?

If not, it would be nice if some classes/constructors were more accessible i.e. SpanFactory class is package private, LocalTracer constructor is also package private which makes it impossible to customize.

**Comment by adriancole** [comment]
This is the default behavior of the new brave.Tracer api. Even a NoopSpan
(span.isNoop() == true) has trace identifiers (via span.context())

https://github.com/openzipkin/brave/tree/master/brave

**Comment by adriancole** [comment]
ps NoopSpan is one that wasn't sampled

**Comment by kmaci3k** [comment]
Ok, so the only thing I need to do to have trace id in each span, no matter if X-B3-Sampled is set or not, is to exchange Brave for Tracer ?

I'm trying to find an equivalent of brave.serverRequestInterceptor().handle() in Tracer API. Is there something new, or I should convert Tracer to Brave and use the old API to handle request which was received by server ? I'm asking because when I send X-B3-Sampled header == 0, I can see that ServerRequestInterceptor does not generate and inject tracing headers and its behaviour is different than what you said or I misunderstood sth.

**Comment by adriancole** [comment]
@kmaci3k which libraries do you instrument currently (via serverRequestInterceptor or otherwise)?

I raised #350 which will eventually replace serverRequestInterceptor. It won't be ready for a couple weeks as I can't work full-time on it, and there are dependencies such as hooking into the "current span"

**Comment by kmaci3k** [comment]
Right now I have dependency on brave-core, brave-http and brave-apache-http-interceptors.

I can try to help with that but I will need some guidance what to start with.

**Comment by adriancole** [comment]
@kmaci3k so you are only using brave api directly and apache http client?

**Comment by kmaci3k** [comment]
Yes.

**Comment by adriancole** [comment]
cool that makes it a lot easier, as I have a fairly complete apache interceptor. if you can please hop on https://gitter.im/openzipkin/zipkin (though I will be signing off shortly). I'll ping you directly on follow-ups here as well.

**Comment by kmaci3k** [comment]
Ok.

**Comment by kmaci3k** [comment]
@adriancole Will new API has integration with SLF4J's MDC (adding current trace id to context of application logs) ?

**Comment by adriancole** [comment]
>
> @adriancole <https://github.com/adriancole> Will new API has integration
> with SLF4J's MDC (adding current trace id to context of application logs) ?
>
lifecycle hooks that could underpin things like SLF4J is being discussed
here https://github.com/openzipkin/brave/issues/150#issuecomment-274387954

**Comment by adriancole** [comment]
Brave 4.3 is being released now and always provisions span ids (even when not sampled)
