### ISSUE TITLE
Initiate deprecation of the brave-cxf3 extension in favor of Apache CXF one

### ISSUE THREAD

**Issue by reta** [openzipkin/brave#354]
Hey guys!

Following the proposal (https://github.com/openzipkin/brave/issues/313), Apache CXF now has a dedicated support of `Brave` as a distributed tracing provider. The next steps would be to communicate the change to community, deprecate `brave-cxf3` extension and eventually remove it from `Brave` distribution.

As the first steps to start with:
 - update `brave-cxf3` README file to raise the awareness about upcoming deprecations, outline the migration path
 - annotate relevant public `brave-cxf3` API as `@Deprecated`, document the replacement 

Thanks!

Best Regards,
    Andriy Redko

**Comment by adriancole** [comment]
sounds good to me.

**Comment by adriancole** [comment]
#372 deprecates this in version 4.1
