### ISSUE TITLE
if some span is in the same thread ,the spans ahead will lost ,only the last will be record

### ISSUE THREAD

**Issue by zengzonghou** [openzipkin/brave#355]
for example ,the service invocation is A ->B -C, in the situation that A->B is in the same thread with B->C,the trace A->B will lost。

from the Brave code,after excute B->C,the currentServerSpan and the currentClientSpan will be clear ,and so the trace A->B is lost

**Comment by zengzonghou** [comment]
in the class "InheritableServerClientAndLocalSpanState"
i modify the currentServerSpan and currentLocalSpan like this:
`
private final InheritableThreadLocal<Deque> currentServerSpan =
new InheritableThreadLocal<Deque>() {
@Override
protected Deque initialValue() {
return new LinkedBlockingDeque();
}
};

private final InheritableThreadLocal<Deque<Span>> currentClientSpan =
        new InheritableThreadLocal<Deque<Span>>() {
            @Override
            protected Deque<Span> initialValue() {
                return  new LinkedBlockingDeque<Span>();
            }
        };

private final InheritableThreadLocal<Deque<Span>> currentLocalSpan =
        new InheritableThreadLocal<Deque<Span>>() {
            @Override
            protected Deque<Span> initialValue() {
                return  new LinkedBlockingDeque<Span>();
            }
        };`
it can solve the problem that diffrent dubbo invocation in the same thread,i hope it would be added into next brave edition,

**Comment by adriancole** [comment]
thanks for the hint!

**Comment by adriancole** [comment]
Brave 4.3 is being released now which has a safer approach to thread local state (CurrentTraceContext). Please switch to that!
