### ISSUE TITLE
More interoperable propagation via extra stuff in TraceContext

### ISSUE THREAD

**Issue by adriancole** [openzipkin/brave#390]
Right now, you cannot use wider trace context propagation formats than B3 because there's no way to carry that data from the incoming request to any outgoing requests. For example, AWS X-Ray includes a timestamp in their trace ID format. If we lost this, we break traces.

Also, many folks have asked in various ways to carry things like request ids so that they can be accessed in custom-code or tagged in log files.

I'm resisting the term baggage as change proposed are data structure only, and "baggage" itself tends to have more implications on api. I'm intentionally punting any api changes.

Here are some use cases that could be supported by adding `List<Object> TraceContext.extra()` and `List<Object> SamplingFlags.extra()` for when there is extra stuff, but not a trace yet. I think this is the only change needed to support this, as everything else is existing apis.

Making a custom propagation handler for Amazon X-Ray
```java
@Override public void inject(TraceContext traceContext, C carrier) {
  for (Object thing : traceContext.extra()) {
    if (thing instanceof XRayTraceContext) {
      inject(traceContext, (XRayTraceContext) thing, C carrier)
      break;
    }
  }
}

// dumbed down, but for example
void inject(TraceContext traceContext, XRayTraceContext xrayTraceContext, C carrier) {
  setter.put(carrier, "X-Amzn-Trace-Id", xrayTraceContext.root() + ";Parent=" + HexCodec.toLowerHex(traceContext.spanId()) + ";Sampled=1");
}
```

Adding type-safe data to a root span
```java
// let's pretend there's a standard "debug-id" that many use regardless of trace format!
for (Object thing : span.context().extra()) {
  if (thing instanceof DebugTraceId) {
    span.tag("debug-id", thing.toString());
    break;
  }
}
```

Making custom propagated stuff visible *without* requiring people to use brave's api
```java
// Assume Sony defines a header format for pre-defined tags, and a propagation handler
// User code wants to use PlayStationContext.currentGame() which is controlled by them
// The below facilitates propagation without pinning anyone to Brave's api. 
// This means they can switch impl to any other means and no problemo. 
// IOTW zero, like zero lock-in. No lock in to B3 header format.
// No lock in to a specific version of a tracer api. This is a choice not a requirement.

class PlayStationAwareCurrentTraceContext extends CurrentTraceContext {
  --snip--

  @Override public Scope newScope(TraceContext currentSpan) {
    Scope scope = delegate.newScope(currentSpan);
    Object current = findPlayStationContext(currentSpan.extra());
    if (current == null) return scope;
    final Object previous = PlayStationContext.save();
    PlayStationContext.set(current);
    return () -> {
      scope.close();
      PlayStationContext.set(previous);
    };
  }
}
```

Details..

For example, I can easily create a decorating propagation system. Ex new `CustomPropagationFactory(Propagation.B3)` where the custom one parses wider trace ids such as Amazon X-Ray. However, there's no place to store it, so when the CurrentTraceContext code executes, it would neither see nor be able to propagate that data. The impact of this is that we cannot continue a trace in such a system without breaking it.

This is a similar problem to what @nbmorgan brought up about customizing context to include application-specific keys. For example, if one wanted to make pony-currentUser, they would need to add interceptors before Brave's, duplicate the effort of propagating it in-process, finally duplicate the effort of attaching it to the outgoing requests. This could also be solved by the same tool, ex CustomPropagationFactory, if there was a place to store this custom data.

We may at some point be able to leverage or implement a [baggage](https://github.com/JonathanMace/tracingplane) handler, but minimally, we need to be able to extra "extra" stuff into a read-only object, then allow injection of that stuff on the other side.

The api would need to be on TraceContext itself, and it is likely safest to use an Object as opposed to a map to describe that custom "stuff". That's because it may take the form of a data structure or binary content, which is not a Map. For example baggage buffers, or type-safe user data.

This discussion is further elaborated here, though I think the salient issue for Brave is being able to interop with other trace context formats. The fact that this also enables a limited use case of arbitrary propagation is a bonus  https://docs.google.com/document/d/1rq-oCR8gNOi2-G0GFhQJZgSZCmKkxL8jbMZCHhyj268/edit

**Comment by adriancole** [comment]
cc @devinsba @reta @llinder

**Comment by songxin1990** [comment]
interested in this，+1。

**Comment by llinder** [comment]
I've only recently started thinking about the implications of interoperating with X-Ray.  I like the idea of Object instead of Map as well and the method `List<Object> extra()` seems like a good fit.

**Comment by devinsba** [comment]
I came across an internal doc that has the ambition of defining an organization wide correlation ID spec that we would be expected to interact with.

My hope is that this work would support this use case.

The expectations:
- If the header is on a request, forward it along downstream
- If the header is not included, create a new value and forward that along down stream
- Attach the value as the same header on http responses as well

This data is a UUID as currently written so I could just use it as the traceID after stripping the `-`s but that only solves the problem if the shape of that correlation ID doesn't change, that could happen but I don't foresee the header name changing after it is put to use so I think a variable length field is safer from my point of view

**Comment by gregdurham** [comment]
interested in this as well, envoy expects a header to be passed through for correlation, and it would be nice to propagate this header as well with the rest of them.

**Comment by adriancole** [comment]
here's the implementation https://github.com/openzipkin/brave/pull/514

**Comment by adriancole** [comment]
here's a working example of extra field propagation #515 
you can use this to pass your favorite request ID or fields that some random reason means you need to or a trace that is incompatible with zipkin etc.  If this is popular, it could be built-in.
cc @llinder @devinsba @songxin1990  @gregdurham @jcchavezs @jkschneider @sirtyro @hyleung @takezoe

**Comment by adriancole** [comment]
going out now in version 4.9.0

**Comment by adriancole** [comment]
note: another api will soon be available to normalize access to correlation fields (called baggage in OpenTracing, tags in Census, and correlation fields in [w3c Correlation-Context](https://github.com/w3c/distributed-tracing/tree/master/correlation_context)) https://github.com/openzipkin/brave/pull/577

**Comment by takezoe** [comment]
@adriancole Thanks for information. The distributed tracing category looks to be evolving quickly!
