### ISSUE TITLE
Bootify spring instrumentation

### ISSUE THREAD

**Issue by adriancole** [openzipkin/brave#399]
It would be convenient to have spring boot magically configure rest template and spring MVC filter. For example, spring-boot-starter-web already includes spring-web and spring-web-mvc deps.

One way to do this is to make spring-boot an optional dep of the existing `brave-instrumentation-spring-web` and `brave-instrumentation-spring-web-mvc` packages. It could then add an autoconfiguration file which configures the filters (given an bean of type `HttpTracing` exists). In non-spring boot environments, this class wouldn't be loaded, so wouldn't crash or otherwise matter. 

The only downside is that if people have their own auto-configuration, they may need to exclude this. That said, this should be manageable via a `@ConditionalOnMissingBean` thing..

**Comment by adriancole** [comment]
another option would be to make an autoconfig directory and jars.

**Comment by devinsba** [comment]
I plan to do this some time in the next few weeks if no one beats me to it.
Whoever you are please let us know here if you do start working on it

**Comment by devinsba** [comment]
cc @TilinC since you are using spring-boot with brave

**Comment by devinsba** [comment]
I am going to try to start working on this this week. I'll link the PR here when I do

**Comment by jorgheymans** [comment]
This issue can be closed, sleuth now incorporates brave/zipkin natively.

**Comment by shakuzen** [comment]
> This issue can be closed, sleuth now incorporates brave/zipkin natively.

In the linked pull request there was some discussion about doing this for people using Spring Boot but not using Spring Cloud (Sleuth), or who are stuck on Spring Boot 1.x. That said, unless we're aware of users for this today, I think we're good to close this.
