### ISSUE TITLE
BraveHttpRequestInterceptor.create does not take the Brave v4 `Tracer`

### ISSUE THREAD

**Issue by tchang-clgx** [openzipkin/brave#405]
In order to add a TraceId and SpanId to request headers sent from the Apache HttpClient, we are adding the `BraveHttpRequestInterceptor` to the http client's interceptors.  We are using `brave-apache-http-interceptors-4.2.0.jar`.  

We want to use the `EmptySpanCollector`, but the `spanCollector(new EmptySpanCollector())` method on the `Brave.Builder` is deprecated, as it belongs to the Brave Core v3 API.  We would like to issue a feature request for the `BraveHttpRequestInterceptor` to take in a `Tracer` from the Brave Core v4 API, so that we don't have to use deprecated methods.

Below is an example of how we're using these components:

```
private static Brave brave = new com.github.kristofa.brave.Brave.Builder("EncryptionServiceClient").spanCollector(new EmptySpanCollector()).build();

[...]

CloseableHttpClient closeableHttpClient = HttpClients.custom()
                 .setDefaultRequestConfig(requestConfig)
                 .setConnectionManager(clientConnectionManager)
                 .addInterceptorFirst(BraveHttpRequestInterceptor.create(brave))
                 .build();
```

**Comment by devinsba** [comment]
A Brave v4 version of the Apache HTTP client has been created: https://github.com/openzipkin/brave/tree/master/instrumentation/httpclient

and an async version: https://github.com/openzipkin/brave/tree/master/instrumentation/httpasyncclient

**Comment by tchang-clgx** [comment]
@devinsba Thanks! Will this be included in the next release?

**Comment by adriancole** [comment]
>
> @devinsba <https://github.com/devinsba> Thanks! Will this be included in
> the next release?
>
Yep, Tiffany. Actually next release will be in a day or two, so please try
snapshot 4.3.0-SNAPSHOT  in the mean time

the snapshot repo is http://oss.jfrog.org/artifactory/oss-snapshot-local

**Comment by adriancole** [comment]
Brave 4.3 is being released now
