### ISSUE TITLE
Consider provided dep of JSR 305 for nullable things

### ISSUE THREAD

**Issue by adriancole** [openzipkin/brave#418]
There's a compelling case for us to delete Brave's nullable annotation in favor of JSR 305, particularly if we do so in a way that avoids boilerplate.

https://medium.com/@swankjesse/non-null-is-the-default-58ffc0bb9111

Note that making this a provided dep means users won't drag in any extra jar by default.

See https://github.com/square/okio/pull/307

**Comment by adriancole** [comment]
@devinsba @reta @schlosna @llinder @hyleung @sirtyro anyone else wdyt? If so, I'd like to change this before we formally announce brave 4.3

**Comment by reta** [comment]
@adriancole Sounds good to me, JSR-305 is the de-facto choice for that
