### ISSUE TITLE
Make brave-instrumentation-http a separate dep

### ISSUE THREAD

**Issue by adriancole** [openzipkin/brave#419]
brave.http has several classes and a faster change cycle than the rest of brave. It is only used for instrumentation. Should we make a separate jar?

**Comment by adriancole** [comment]
@devinsba @reta @schlosna @llinder @hyleung @sirtyro anyone else wdyt? If so, I'd like to change this before we formally announce brave 4.3

**Comment by sirtyro** [comment]
Seems a sensible move to me.

**Comment by reta** [comment]
Make a lot of sense, detaching the protocol(s) from the core sounds right.
