### ISSUE TITLE
Deploy less artifacts

### ISSUE THREAD

**Issue by adriancole** [openzipkin/brave#423]
Publishing to maven central takes a considerable amount of time, due to the large amount of artifacts we publish. The last sync was killed by circleci because it took over 10minutes to respond.

One way to reduce time is to publish less. For example, we can drop the long since deprecated brave-spancollector modules, and drop the test-only modules like brave-jersey2

**Comment by jorgheymans** [comment]
Outdated issue, please close.

**Comment by shakuzen** [comment]
Closing. We can open separate issues or pull requests to stop publishing anything else that makes sense.
