### ISSUE TITLE
[brave-instrumentation-mysql] bug

### ISSUE THREAD

**Issue by thunderyan** [openzipkin/brave#430]
Hi, there have a bug in project [brave-instrumentation-mysql-4.3.3] TracingStatementInterceptor.class line 39, `span.kind(Span.Kind.CLIENT).name(sql.substring(0, sql.indexOf(' ')));`, it will throw an Exception, because some SQL like 'commit' don't have character ' ', so sql.indexOf(' ') will return -1 and sql.substring will be exception.

**Comment by devinsba** [comment]
Thats a good catch, can you create a PR with a fix if you get a chance? Otherwise I'll try to get to it some time soon.

**Comment by thunderyan** [comment]
OK. Thanks. i waiting you fix this bug.

**Comment by adriancole** [comment]
https://github.com/openzipkin/brave/pull/434
