### ISSUE TITLE
Custom per url http sampler feature request

### ISSUE THREAD

**Issue by sirtyro** [openzipkin/brave#432]
After an HTTP sampler that will allow the specification of different sampling rates for particular path and method combinations which will then fall through to the default rate set in brave.Tracing

Idea being you can specify rules like:
- GET /api/person/ has a sample rate of 0.1
- POST /api/person has a sample rate of 0.5
- Otherwise, fall through to brave.Tracing sampler

Regex on the path would be a nice to have, would settle for an absolute value.

**Comment by adriancole** [comment]
https://github.com/openzipkin/brave/pull/437 = work in progress

**Comment by adriancole** [comment]
#437 has what's needed I think
