### ISSUE TITLE
Parameterized non http sampler feature request

### ISSUE THREAD

**Issue by sirtyro** [openzipkin/brave#433]
Looking for a way to have custom sampling rates set for traces that are started by a scheduled task, custom annotation or managed operation (JMX).

A possible solution would be that when we call tracer.nextSpan() we provide an opaque object which is used as the key to lookup (or create if it doesn't exist) an individual counting sampler and the desired rate.

We have our own annotation that we use to specify custom tracing start points in our code. So we would then be able to do something like @TraceThisMethod(sampleRate = 0.12) and pass in the instance of the annotation and the sampling rate from it.

Under the hook you would do something like a conditional lookup on the object.
samplerCache.get(target, target -> CountingSampler.create(rate));

You wouldn't need to fall back to Tracing.sampler() as it would create one instead (making the call to nextSpan with the parameters means you have short circuited the default sampler).

**Comment by adriancole** [comment]
https://github.com/openzipkin/brave/pull/439 has all of this I think
