### ISSUE TITLE
Kill switch feature

### ISSUE THREAD

**Issue by sirtyro** [openzipkin/brave#435]
It would be good to have a switch within brave that can be used to stop anything and everything related to tracing.

For our adoption, we need to provide some risk mitigation that if we're having any issues we can easily and safely stop tracing. We have a good way to signalling to our artefacts that they need to turn off brave. What we don't have is a good way to actually turn brave off.

At the moment, we're wrapping all our samplers and reporter with delegates that we can switch off, which will simply stop delegating. 

It would also mean that we can easily turn off tracing during a build, rather than what we do at the moment which is to have a test jar present with a marker class and our configuration has conditional beans meaning you get a no-op reporter for builds.

**Comment by adriancole** [comment]
so by turning off, this could be done in two ways (or more):
* whack-a-mole - ex have each instrumentation know how to pass-through. In this case they never invoke brave when kill-switch is on
* Disable all side-effects in the Tracing component - ex intercept and make span reporting, in-process (current trace context) and out-of-process propagation (ex B3) noop.

**Comment by adriancole** [comment]
One thing I like about whack-a-mole is it is easier to ensure no side-effects occur. OTOH, custom instrumentation may accidentally start making new traces. For this reason, it might not be great for what you are looking for.

**Comment by adriancole** [comment]
On propagation.. if we leave propagation on (even when kill-switch), this will propagate sampled=false downstream. By doing so, it would kill-switch implicitly anything downstream (including things in different languages).

So one thing to clarify is if kill switch should disable propagation or not. For example, if stopping sampling (by always returning false), and pausing span reporting (by dropping), it is a bit easier to reason with as it is the same as if you had configured no sampling in the first place.

Another q is how dynamic this needs to be. For example, kill switch presumably is temporary, so it would need a control to toggle on/off (perhaps on the Tracing component).

**Comment by sirtyro** [comment]
Ideally, yes, it would be dynamically controlled; through the Tracing component makes the most amount of sense as it is the entry point to everything.

**Comment by sirtyro** [comment]
In terms of the approach, I don't mind too much. It seems as though it would be simple enough to whack spans at the sampling and reporting stage, so that should be sufficient for now.

**Comment by adriancole** [comment]
In stagemonitor, they call this being "active" which is a dynamic parameter instrumentation inspect https://github.com/stagemonitor/stagemonitor/blob/master/stagemonitor-core/src/main/java/org/stagemonitor/core/CorePlugin.java#L63

**Comment by adriancole** [comment]
for our case, I think this is best as Tracing.isNoop()/setNoop() since in implementation, that's what would be happening

**Comment by adriancole** [comment]
here's the impl #445
