### ISSUE TITLE
XSS vulnerabilities

### ISSUE THREAD

**Issue by ghost** [openzipkin/brave#446]
There exist some vulnerabilities in the Zipkin UI. An issue has been raised for it, see https://github.com/openzipkin/zipkin/issues/1623

I'm raising the question about it here as I wonder if the input from brave should be sanitised also to try and avoid this? As we used brave to inject the bad data. Please see the zipkin issue for full context.

**Comment by adriancole** [comment]
zipkin-sparkstreaming is one way server side. Currently a custom reporter
or a custom http parser are the ways in brave. If exposing SpanCustomizer
to users, you can wrap to sanitize data

**Comment by jorgheymans** [comment]
Outdated issue, we have moved to Lens UI and #1623 was closed. Please close.
