### ISSUE TITLE
[Future] TracingHandlerInterceptor add blackList

### ISSUE THREAD

**Issue by xxweimei** [openzipkin/brave#456]
My web service has healthcheck api which is called per second.
After using brave and zipkin, zipkin database is blocked by a lot of healthcheck request.
Can you provide a configuration to implement a black list function ?

**Comment by adriancole** [comment]
This is already supported by httpTracingBuilder.serverSampler
https://github.com/openzipkin/brave/tree/master/instrumentation/http#sampling-policy.
You can exclude /health for any server library this way

**Comment by xxweimei** [comment]
It's very useful to me. Thanks
