### ISSUE TITLE
Add an API to retrieve a closeable copy of the current span. 

### ISSUE THREAD

**Issue by jakerobb** [openzipkin/brave#463]
Context: trying to implement brave-opentracing for opentracing-api 0.30.0. Work in progress at https://github.com/openzipkin/brave-opentracing/pull/43. 

As things stand right now, the bridge is functional. However, this is only possible because every time we call tracer.withSpanInScope, we save the SpanInScope in a cache internal to the bridge. Managing the contents of the cache leads to potential race conditions and memory leaks. 

To improve this situation, the bridge needs a way to ask Brave for the current scope _such that it can subsequently use the returned object to close the scope_. 

Right now, the only way to get a closeable span is to call tracer.withSpanInScope, but that option is inviable because it creates a _new_ scope, the closure of which leaves you back where you started.

**Comment by adriancole** [comment]
I don't want this feature to exist. This moves the problem of the OpenTracing api (which itself isn't popular) into brave.

**Comment by adriancole** [comment]
In brave (census etc), the lifecycle of a span is not conflated with scoping of it. The CurrentTraceContext api deals with an immutable datum, TraceContext, which is not a Span.

The withSpanInScope api is simply a helper, such that users don't have to say span.context(). The caller of withSpanInScope has a reference to the span, and so any local changes including finishing the span can be done.

ex.
```java
try (SpanInScope ws = tracer.withSpanInScope(span)) {
  return inboundRequest.invoke(); // downstream calls can use currentSpan
} finally {
  span.finish(); // current calls can use the span directly
}
```

Encouraging SpanInScope to be passed around routinely, discourages normal usage which is that it is closed in the same method it is opened on. Adding `SpanInScope.span()` goes towards that.

I'd like to have a test case in the other PR before we add any debt here to support it. There may be a way to accomplish something, but so far no tests have been written to help figure that out.
