### ISSUE TITLE
apache httpclient instrument doesn't support version 4.3.x

### ISSUE THREAD

**Issue by hzhaop** [openzipkin/brave#474]
https://github.com/openzipkin/brave/blob/04bd17a9595972bc4c452565e3bc47530c813080/instrumentation/httpclient/src/main/java/brave/httpclient/TracingHttpClientBuilder.java#L78

HttpRequest in apache doesn't have method getTarget,  it is supported since version 4.4.x.

**Comment by adriancole** [comment]
you are correct. I assume you can't upgrade to 4.4? or are you more mentioning the documentation error?

**Comment by hzhaop** [comment]
im mentioning the documentation error.

**Comment by adriancole** [comment]
thx fixed the docs in a3724dd
