### ISSUE TITLE
Add Propagation.supportsJoin()

### ISSUE THREAD

**Issue by adriancole** [openzipkin/brave#483]
B3 traditionally has client and server sharing span IDs. It isn't easy to tell if you should not, except guessing. For example the trace-context format does not send parent ID. Unless we have some sort of feature on Propagation or Extractor, we won't know if we should assume missing parent ID is account of format or that it is a client originated root span.

Since extractor is a single-method function, it is probably nicer to add "supportsJoin" or similar to Propagation.

Propagation is an interface and this would break implementors. However, I don't think there are many at the moment (as opposed to Extractor of which there are many). We could do a github search to verify but seems relatively safe.

Thoughts? cc @basvanbeek @devinsba @llinder

**Comment by devinsba** [comment]
The change seems reasonable, the Interface change won't affect us.

**Comment by llinder** [comment]
The change shouldn't effect us either.

**Comment by adriancole** [comment]
https://github.com/openzipkin/brave/pull/501 will handle it I think. lemme know if you have any q's on it.
