### ISSUE TITLE
show traceId and spanId in slf4j according brave.

### ISSUE THREAD

**Issue by cbcing** [openzipkin/brave#486]
i saw this docx, <https://github.com/openzipkin/brave/blob/master/context/slf4j/README.md>
and i write the flowing code in my configuration file(ZipkinBraveConfig.java)(spring boot):
```java
  @Bean
  public Tracing tracing() {
    val tracing = Tracing.newBuilder()
      .localServiceName("service1")
      .currentTraceContext(MDCCurrentTraceContext.create());
    tracing.reporter(reporter());
    return tracing.build();
  }


  @Bean
  public Sender sender() {
    val zipkinUrl = "my_url";
    return URLConnectionSender.builder().endpoint(zipkinUrl).build();
  }

  @Bean
  @DependsOn("sender")
  public Reporter<Span> reporter() {
    return AsyncReporter.builder(sender()).build();
  }
```

logback.xml:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>

    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <!-- encoders are assigned the type
             ch.qos.logback.classic.encoder.PatternLayoutEncoder by default -->
        <encoder>
            <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{traceId}/%X{spanId}] [%thread] %-5level %logger{36} - %msg%n</pattern>
        </encoder>
    </appender>

    <root level="info">
        <appender-ref ref="STDOUT" />
    </root>
</configuration>
```
but ...
it's not work !

The result is:
```
2017-09-05 14:21:50.262 [/] [http-nio-8081-exec-1] INFO  o.a.c.c.C.[Tomcat].[localhost].[/] - Initializing Spring FrameworkServlet 'dispatcherServlet'
2017-09-05 14:21:50.262 [/] [http-nio-8081-exec-1] INFO  o.s.web.servlet.DispatcherServlet - FrameworkServlet 'dispatcherServlet': initialization started
2017-09-05 14:21:50.275 [/] [http-nio-8081-exec-1] INFO  o.s.web.servlet.DispatcherServlet - FrameworkServlet 'dispatcherServlet': initialization completed in 13 ms
2017-09-05 14:21:51.264 [/] [http-nio-8081-exec-1] INFO  c.p.z.service1.ZipkinBraveController - tracing......
```
there is no traceId and spanId, i dont know why.

Someone can help me ?
Thanks.

**Comment by adriancole** [comment]
What you pasted looks a-ok. Did you try
https://github.com/openzipkin/brave-webmvc-example ?

**Comment by cbcing** [comment]
Thanks very much.
i solve it.

**Comment by tridipch** [comment]
I have a similar problem with log4j2.xml 
How did you resolve it?

**Comment by adriancole** [comment]
Log4j2 exists in the same example project
https://github.com/openzipkin/brave-webmvc-example/blob/master/servlet3/src/main/java/brave/webmvc/TracingConfiguration.java

https://github.com/openzipkin/brave/tree/master/context/log4j2

**Comment by tridipch** [comment]
Did that successfully with log4j2.properties, but not with log4j2.xml

**Comment by adriancole** [comment]
brave doesn't have any relationship between using properties vs xml
configuration. I would try to troubleshoot normally (ex look at other MDC
examples for log4j2) as I currently don't have a free moment to help with
this

**Comment by mkozeny** [comment]
Please cbcing, how did you solve this problem for slf4j?

Thanks M.!

**Comment by diversit** [comment]
@cbcing Having the same issue. How did you solve it?

**Comment by adriancole** [comment]
please come to https://gitter.im/openzipkin/zipkin for support. While we have examples in code it maybe that we don't have the right words in place to describe things. Chatting through it might help us make things better
