### ISSUE TITLE
[Feature Request] Ability to set many remoteServiceName for different DBs in p6spy instrumenter

### ISSUE THREAD

**Issue by hypnoce** [openzipkin/brave#487]
Hi,

the current implementation of the p6spy module allows to set a remoteServiceName. This is used globally by p6spy and uses the same option for all DB access.
If it is not set, [TracingJdbcEventListener.java#L75](https://github.com/openzipkin/brave/blob/c1fcfddc01358b3dd2acfbb11642567bc75f10ea/instrumentation/p6spy/src/main/java/brave/p6spy/TracingJdbcEventListener.java#L75) gets the catalog name and sets it as the remoteServiceName.
Therefore if the application needs to speak to more than 1 db, either they are all shown as the same service in tracing reports or they are shown distinctly using their catalog name, which is not always what we want.

First, what do you think of the ability to set a service name per DB instances @adriancole @felixbarny ?

An idea would be to add to the connection url a zipkinRemoteServiceName parameter that will be parsed by TracingJdbcEventListener and used if exists. This will override any global remoteServiceName set in spy.properties.
For mysql : 
` jdbc:mysql://localhost:5555/mydatabase?user=user&zipkinRemoteServiceName=authenticationDB`
For sqlserver : 
`jdbc:sqlserver://localhost:1433;databaseName=mydatabase;user=user; zipkinRemoteServiceName=authenticationDB`

Thanks

**Comment by hypnoce** [comment]
Hi,

the PR is here to provide an implementation idea of the feature. Let me know if you have any comment on the feature or the PR.

Thanks

**Comment by felixbarny** [comment]
So no changes in p6spy required?

**Comment by hypnoce** [comment]
Hum, the way p6spy is architectured there is not simple way today to set options for modules per database.

**Comment by adriancole** [comment]
actually might suggest change to zipkinServiceName as remote is
implied and this is the same as our mysql pattern
