### ISSUE TITLE
Thread specific Endpoint in ServerAndClientSpanStateImpl?

### ISSUE THREAD

**Issue by regunathb** [openzipkin/brave#50]
This comment is based on existing codebase in master. The Endpoint instance in ServerAndClientSpanStateImpl is shared across threads while other attributes like currentServerSpan, currentClientSpan and currentClientServiceName are stored on ThreadLocal instances.
For client spans submitted using the ClientTracer implementation, IMO the endpoint should point to the remote endpoint whereas it should point to the service/server endpoint for server spans submitted via ServerTracer. 
In a sample server/service trace that calls a number of client servers/services (in different threads and in parallel possibly), this single endpoint variable gets updated by a number of threads and messes it up.
Would you consider storing the Endpoint variable also on ThreadLocal? Or does it go against the original design of this class?

**Comment by regunathb** [comment]
I guess the difference in understanding is due to the fact that I would
like to capture the host name and port of the target service that the
client is calling.
In your example above for CS and CR, I would like to capture ip: service b
and port : service b.

As explained, I capture this information by submitting an annotation on the
ClientTracer. Please see attached screenshot (the KV pair of host,
localhost:-1). Here localhost is the host being called by the client and -1
is the port (this is a local JVM call and hence the value of -1. Will be
something more meaningful for say an outbound Http request).

Thanks for the reply.

[image: Inline image 1]

**Comment by kristofa** [comment]
Sorry for the delay in replying!

Can you explain why you want to have the server ip + port in the client endpoint?
The advantage of have client ip + port in client endpoint and server ip and port in server endpoint is that you can see and distinguish client host -> server host.

I just want to try to understand why you want this behavior.  I can't see any image in your previous comment.

**Comment by regunathb** [comment]
My bad. Did not see that the image was not getting added when I replied from email client. Here are two images: 1. Explains the request pattern. 2. shows the span details on Zipkin console with the annotation submitted via the ClientTracer.
![Request pattern](https://cloud.githubusercontent.com/assets/701583/6281311/f71152e4-b8e4-11e4-8a68-cef13b214acb.png)
![Span with annotation](https://cloud.githubusercontent.com/assets/701583/6281313/04877c3c-b8e5-11e4-9867-6b563930f380.png)

**Comment by kristofa** [comment]
I think it would be confusing to use server host + port when submitting client side annotations. 

This would change the host+port meaning for an annotation. Do you want to do this because you can't add brave/zipkin support in the servers client1, client2 and client3 are calling?

Why do you want to change the host as part of the annotations and why aren't you satisfied with a custom annotation like you do now?

**Comment by regunathb** [comment]
Given that Phantom is a proxy, there is value in knowing the destination
for the request i.e. the client server and port.
Custom annotations work fine and we are satisfied so long as this
information is captured as part of the trace and can be displayed, which we
can now.

Thanks

**Comment by adriancole** [comment]
In Brave 4.3 all http server instrumentation annotate the client address
