### ISSUE TITLE
instrumenting RabbitMQ via spring-amqp

### ISSUE THREAD

**Issue by jonathan-lo** [openzipkin/brave#508]
There's been some interest at my work with instrumenting rabbit interactions that are made using spring-amqp. @adriancole mentioned that there's been previous requests for this instrumentation channel e.g. openzipkin/zipkin#1428.

I can have a look at this if there's sufficient interest. Since spring-amqp has some nice hooks into the consume / produce lifecycle, this looks feasible.

**Comment by jonathan-lo** [comment]
The plan of attack I'm thinking is:
producer via RabbitTemplate - use the MessagePostProcessor hook to inject trace headers / annotate
consumer via RabbitListener - use SimpleRabbitListenerContainerFactory's adviceChain which allows us to specify an aspect to extract the trace headers and handle appropriately

**Comment by adriancole** [comment]
These types all are in the same maven dependency, right? If so
instrumentation-spring-amq sounds right. If any amqp works junit driven
intergration test might be easier as rabbit isnt java. Even if not is ok as
we can add the rabbitmq service to ci

**Comment by jonathan-lo** [comment]
Hmm you're right, whilst RabbitTemplate and RabbitListener is from spring-rabbit, the extension points are from the spring-amqp maven dep, so instrumentation-spring-amqp sounds reasonable.

Will have a play around with the integration tests, at the moment it seems the easiest path would be to add rabbitmq service to ci.

**Comment by liangxp** [comment]
I also want to trace rabbitMQ Message

**Comment by jonathan-lo** [comment]
should we close this now that @adriancole is working on a generic spring-messaging instrumentation?

**Comment by adriancole** [comment]
Well depends. The spring-messaging abstraction doesnt know if a queue is
remote, the topic name etc. It is a bit harder to get right.. Do you use
spring messaging to access spring amqp?

**Comment by jonathan-lo** [comment]
I see. My spike is using spring amqp's abstractions. So the value add here could be digging the exchange / routing key out of the MessageProperties

**Comment by adriancole** [comment]
your spike looks good. only question I have really is if there is another way apart from aop to handle the consumer side. I'm guessing instrumenting with spring-amqp (or spring-rabbit) could have an advantage of decoupling the incompatible rabbit 4.x from 5.x series as well https://github.com/openzipkin/brave/compare/master...jonathan-lo:master

cc @shakuzen

**Comment by skastenholz** [comment]
I would like to contribute a different way of implementing the listener advice https://github.com/skastenholz/brave/commit/0a721a67ef8b5f890bb0c8197d68d1521aa270cc:

```java
final Message message = (Message) methodInvocation.getArguments()[1];
final TraceContextOrSamplingFlags extracted = extractor.extract(message.getMessageProperties());
final Span span = tracer.nextSpan(extracted).kind(Span.Kind.CONSUMER).start();
try (SpanInScope ws = tracer.withSpanInScope(span)) {
  return methodInvocation.proceed();`
} finally {
  span.finish();
}
```
This turned out to work on my project and follows https://github.com/openzipkin/brave/tree/master/brave#setting-a-span-in-scope-manually.

What do you think?

**Comment by jonathan-lo** [comment]
@skastenholz Yep for sure my next step was to clean the implementation to pretty much the same as what you have there :)

So in my mind there's a couple more things to explore:
- a non aop solution as @adriancole mentioned above
- annotating extra info from publisher confirms?

**Comment by skastenholz** [comment]
@adriancole Regarding a non-aop approach for the AMQP listener I do not see any option after double-checking https://docs.spring.io/spring-amqp/reference/htmlsingle/#containerAttributes. Does this work for you or do you have an alternative in mind?

**Comment by adriancole** [comment]
@adriancole <https://github.com/adriancole> Regarding a non-aop approach
for the AMQP listener I do not see any option after double-checking
https://docs.spring.io/spring-amqp/reference/htmlsingle/#containerAttributes.
Does this work for you or do you have an alternative in mind?

Have to look closely, sometimes a wrapping delegate can avoid aop. Otoh as
aop is fairly routine in spring it might be fine.

Jon, do you want to raise a PR or do you want me to "harvest your commits"
or..

**Comment by jonathan-lo** [comment]
I'll PR.

From memory a wrapping delegate was non trivial since the most commonly used case for consumer side was annotation driven.
