### ISSUE TITLE
the currentTimeMicroseconds of DefaultClock is slightly inaccurate

### ISSUE THREAD

**Issue by cgfork** [openzipkin/brave#516]
The currentTimeMicroseconds of DefaultClock or Platform is not equal to the System.currentTimeMillis(). The delta > 1000us. System.currentTimeMillis() is the system time.  System.nanoTime() is the time of running Java Virtual Machine's high-resolution time. When the system time is changed (by NTP),  System.nanoTime() is not changed. So the currentTimeMicroseconds is inaccurate.  I think it is necessary to reset the start time when the system time changes.

```java
classs DefaultClock implements Clock {
        final Ticker ticker;

        DefaultClock() {
            ticker = new Ticker();
        }

        @Override
        public long currentTimeMicroseconds() {
            return ticker.nowMicroMillis();
        }
    }

class Ticker {

        private final AtomicReference<Marker> ref;

        Ticker() {
            ref = new AtomicReference<>(new Marker());
        }

        public long nowMicroMillis() {
            for (int i = 0; i < 3; i++) {
                Marker marker = ref.get();
                Marker currentMarker = new Marker();

                long microMillis = currentMarker.currentMicroMills(marker);
                if (Math.abs(currentMarker.startTs - microMillis) < 1000) {
                    return microMillis;
                }

                if (ref.compareAndSet(marker, currentMarker)) {
                    return (System.nanoTime() - currentMarker.startTick) / 1000L + currentMarker.startTs;
                }
            }

            return new Marker().startTs;
        }
    }

class Marker {
        final long startTs;
        final long startTick;

        Marker() {
            this.startTs = System.currentTimeMillis() * 1000;
            this.startTick = System.nanoTime();
        }

        long currentMicroMills(Marker old) {
            return (startTick - old.startTick) / 1000L + old.startTs;
        }
    }
```

**Comment by adriancole** [comment]
I think @llinder noticed this too at some point...

**Comment by adriancole** [comment]
note that in java 9 we can get an accurate clock by default, avoiding this (though there's still risk of the clock changing between start and finish):

```java
    return Tracing.newBuilder()
        .clock(() -> {
          Instant instant = java.time.Clock.systemUTC().instant();
          return SECONDS.toMicros(instant.getEpochSecond()) + NANOSECONDS.toMicros(instant.getNano());
        })
```

**Comment by adriancole** [comment]
cc also @shakuzen @jorgheymans

**Comment by llinder** [comment]
@cgfork I've noticed this problem as well.  We run NTP on our servers but we still see a lot of clock skew.  Originally I had planned on trying to force an NTP sync on startup before Zipkin starts. Your proposed approach of rechecking the time in the Clock implementation sounds even better. 
 The less I have to deal with forcing servers to do the same thing across distributed teams and owners the better :)

**Comment by adriancole** [comment]
Thx for feedback. I agree reseting every second is a good idea. It can
result in a span ending before it started due to ntp. Wondering if we can
rejig to use the same clock instance per trace.. i think we can..

**Comment by adriancole** [comment]
this has been fixed in the latest release
