### ISSUE TITLE
XRay Remote Service Name is always "Remote"

### ISSUE THREAD

**Issue by cemo** [openzipkin/brave#524]
I am in the process of customizing brave and putting into the production system but I came across a problem.

Despite of creating my interceptor with hardcoded labels, it always displays *remote* in the console. I could not find time to check it but seems there is a bug at there. I might give a try tomorrow to find culprit. 

![image](https://user-images.githubusercontent.com/44156/31743108-946c32ae-b462-11e7-8476-59bbd5938b6d.png)

**Comment by adriancole** [comment]
This issue was moved to openzipkin/zipkin-aws#58

**Comment by adriancole** [comment]
moved because the mapping logic is in zipkin-aws (the xray reporter converts the objects, including mapping names)
