### ISSUE TITLE
Could you support span decorator?

### ISSUE THREAD

**Issue by adriancole** [openzipkin/brave#529]
_From @tutufool on September 6, 2017 12:12_

Hi, 

I may have some common tags in my app which I'd like framework guys take care of it instead of app guys.
For example:
1. when span started, I need to auto add a tag to indicate on which thread it's started.
2. when span finished, I need to auto add a tag to indicate on which thread it's closed.

I've tried composite mode (since most of your class impls are final) to do wrappers.
It turns out having MySpanBuilder(wrap BraveSpanBuilder) to do decoration after startActive/startManual is OK.
But it's kind of hard for me to add a hook on finish. (since the finish() is conditionally executed in deactivate()).

So, I'm thinking whether you can provide an advanced overload builder method to use like:

BraveTracer.create(Tracing brave, SpanDecorator decorator);

while:

interface SpanDecorator{
 void afterStart(BaseSpan span);
 void beforeFinish(BaseSpan span);
}

Let me know if it's reasonable or you may have some other work around.

Thanks a lot!

Leon

_Copied from original issue: openzipkin-contrib/brave-opentracing#51_

**Comment by adriancole** [comment]
Thanks for the note. We've had some similar requests upstream just haven't
followed through (mainly waiting for more requests).

Might make sense to use a callback on brave's SpanCustomizer type as this
won't accidentally lead to someone messing up the lifecycle or being
tempted to.

ex onStart(SpanCustomizer span)

**Comment by adriancole** [comment]
_From @tutufool on September 7, 2017 6:59_

I guess the reason you propose SpanCustomizer interface is because it hides lifecycle method like finish().
However, BaseSpan does not contain lifecylcle method as well, and it's purely opentracing api.

If we use SpanCustomizer as callback input, then user is forced to know more about brave.
According to my experience on using brave-opentracing, the only brave thing I use is BraveTracer.
All other brave things are completely hide to me, and I only need to use pure opentracing api.

**Comment by adriancole** [comment]
>
> If we use SpanCustomizer as callback input, then user is forced to know
> more about brave.
> According to my experience on using brave-opentracing, the only brave
> thing I use is BraveTracer.
> All other brave things are completely hide to me, and I only need to use
> pure opentracing api.
>
Customization like this isn't an OpenTracing api, anyway, right? You are
talking about a custom hook. Also are you expecting users to interact with
this? seems pretty low-level if it is applying to all spans.

**Comment by adriancole** [comment]
_From @tutufool on September 10, 2017 10:30_

OK, then let's go with SpanCustomizer

**Comment by devinsba** [comment]
This thread is quite timely. I was going to make a similar request.

My requirement is a little different. In addition to the above, I also need to be able to add annotations onto the span at the time of closing.

How I've worked around this is I wrapped my reporter and I modify the outgoing span but this feels like an utter hack

**Comment by adriancole** [comment]
thx for piping up!

incidentally this should also support an old issue "default tags" https://github.com/openzipkin/brave/issues/357

and also someone doing stats even in noop spans (requested today by @markmaxey)

**Comment by adriancole** [comment]
cc also @hyleung @llinder @jkschneider @jcchavezs @marcingrzejszczak @narayaruna @garyd203 @jorgheymans @openzipkin/core


So, I'm thinking about how to make this useful... specifically a span listener which can be used to integrate with metrics. The important thing is that this is always on, even in noop case!

Remember that in noop case, often you have no tags because parsing of them was obviated!

For example, let's say you have a prometheus histogram like this:
```java
  static final Histogram http_request_duration_seconds = Histogram.build()
    .labelNames("path", "method")
    .help("Response time histogram")
    .name("http_request_duration_seconds")
    .register();
```

I'm assuming we want to end up with something like so..

```java
-- http customizer -- this is portable like our tag parser is..
@Override
public <Req> Listener listener(HttpAdapter<Req, ?> adapter, Req req) {
  // scope some tags based on this http endpoint.
  Histogram.Child forThisEndpoint = httpRequestDuration
          .labels(adapter.path(req), adapter.method(req));

  // return a listener that observes the duration
  return new Listener() {
    @Override public void finish(long startTimestamp, long finishTimestamp) {
      forThisEndpoint.observe(finishTimestamp - startTimestamp);
    }
  };
}
```

This implies http tracing middleware is doing something like a late call to `span.listener(theThingCreated)`

There are some gotchas here.. The above approach moves a *lot* of responsibility into brave. Brave will need to keep this listener attached and also record timestamps even when we aren't really tracing. This avoids duplicate measurements of time, which not only can reduce overhead, but also keep precision. The result is very little for a user to do, at the cost of more work in our recorder.

Another approach would be to have the caller manage figuring this out.. for example, they only get a parameter, such as the trace context, and it is their job to manage state. This is easier for us, but I'm really not sure how folks would hook in.

Anyway I can sketch something like this up, if it is worth straw-manning. Any other ideas?

**Comment by adriancole** [comment]
another approach would be to make a setting for "always record" similar to census. Then, recording duration into metrics would be based on a zipkin2.Span object which will always have a duration. Just that not all of them will be reported to zipkin, so we'd have something like a "onFinish(zipkin2.Span span)" hook which fires regardless of whether the span is reported to zipkin or not.

**Comment by jcchavezs** [comment]
I think creating an `SpanObserver` would make things easier:
1. You set up the spanObserver when creating the tracer `builder.withSpanObserver(mySpanObserver)`. If none is passed we pass a `Noop`.
2. When starting the span, despite it is noop or not we do `onStartSpan(span, startTime)`. startTime is going to be the time you created the span in case you want to register a log.
3. When finishing the span, `onFinishSpan(span, finishTime)`. finishTime is going to be the time you created the span in case you want to register a log.

Said that, there is no way you can make a decision on listeners calls as of tags are not propagated.

Advantages on this is that we delegate the responsibility to do stuff to the client. We don't do any calculation.

**Comment by adriancole** [comment]
So, JC I think what you've mentioned is similar to what I mentioned on
listener, but the design is a bit off as it isn't reflective of brave. I'll
try to clarify some of the points.

Not sure we want to use the word observer
<http://reactivex.io/RxJava/javadoc/io/reactivex/Observer.html> as it is
usually a subscription to a single observable (ex span). Depending on
scope, we might have a global listener.. also it is more like an event
listener anyway: Especially in brave, these events won't come from a span,
rather a side effect of using one, or a side-effect of expiration. There's
no way to subscribe to a span object because the span api is just a cover
type over the event system underneath. Ex span.start = record(context,
startTime). It is watching the events that will result in these callbacks,
the Span objects themselves are completely disposable etc. Long way of
saying that probably event listener is more accurate for what's going on.

Another thing to keep in mind about Brave (vs OpenTracing or some others)
is that there's no readback commands on span apart from its context.
This means a parameter of a brave.Span doesn't give you anything unless we
are talking about the exported type zipkin2.Span which is an immutable
struct (which may or may not have any data in it). This affects the
callback design a bit because either there's an implicit span (because a
listener is 1-1 with a span), or we pass arguments about it (ex the context
when it starts, and depending on what we have, more when it stops)

All these things said, If we go the way of a global span listener, most of
the things you mention are sortof the same :)


>    1. You set up the spanObserver when creating the tracer
>    builder.withSpanObserver(mySpanObserver). If none is passed we pass a
>    Noop.
>
> clarifying style to Tracing.Builder.spanListenerFactory or spanListener
depending on if we want to support span-based listeners (ex create a
listener given a span context), or just global (and pass something each
invocation). Latter is fine.


>
>    1. When starting the span, despite it is noop or not we do onStartSpan(span,
>    startTime). startTime is going to be the time you created the span in
>    case you want to register a log.
>
> I don't think we'll have anything except a span that we'll be talking
about in this type, so probably will drop the "Span" suffix. As mentioned
before (I think), likely the input parameter will be the trace context, not
the span as the span, especially on start, isn't useful for readback..
(also the thing about there being nothing important about the identity of
the span object, as the context is the actual key.. remember in brave you
can do Tracer.toSpan(context) to create a span)


>
>    1. When finishing the span, onFinishSpan(span, finishTime). finishTime
>    is going to be the time you created the span in case you want to register a
>    log.
>
> This is the interesting one.. if we have both start and finish timestamps,
someone can read this without them keeping state per trace context (which
can be expensive). The param should probably match the start one (context).

>
>
> Said that, there is no way you can make a decision on listeners calls as
> of tags are not propagated.
>
well we could make a secret method or something to get a span snapshot..
but yeah I agree this "global only" design has a limitation which is that
we don't know what tags have been assigned. OTOH we could add a callback
for tag added :P it wouldn't have timestamp, but the caller could
accumulate tags based on trace context... again it is duplicating work,
though.

> Advantages on this is that we delegate the responsibility to do stuff to
> the client. We don't do any calculation.
>
I agree with the pros and cons of this. It might be one of those things
where we need to implement two approaches to see the impact. In brave we
are already tracking quite a bit, but on the other hand adding listeners
can cement some design aspects. Probably best to get some concrete uses of
the listeners down so that we don't under or overshoot. Million thanks for
helping think through this.

**Comment by jcchavezs** [comment]
Thanks for the feedback @adriancole. First of all I do agree listener is a better name than observer as all this is about publishing events about the span (despite the fact it is 

The reason why I focused all this on Span is because:
1. All events we want to track are span based because
2. Context is immutable so the concept of **listening changes** sounds odd although it is true the Context is the main object.
3. Additional data like tags are not propagated in context.

---

Regarding local or global listeners I'd like to summarize my understanding on the pros-cons:

## a. Global Listener
Maybe I am not seeing the big picture but IMO, the main difficulty here is to decide what to listen and what to not to listen and probably that decision will be made out of reading back the information of the span (maybe?).
### Pros
- Can be set on tracing level, making it easy to implement.
### Cons
- If you need to make decisions about what to listen, it is pretty inconvenient as of you need to keep a list of spans/context you want to listen and verify whether the span is the list or not.

## b. Local Listener
I don't have too much experience with instrumentation but I don't think spans are being passed across layers so, can't you just add tags when you start the span? I guess no if the library is a dependency, so in that case the only way you can inject listeners is through the global listener.

### Pros
- No unnecessary overhead, only listen what you want. `Noop` for the rest.
### Cons
- Not possible to add listeners on instrumented libraries.

## c. Middleware-ish
What if we give access to the full span information before flush? Sounds like hacky way to do it, although you have full access to the information and the API allows you to interact with the span through and API.

-----
In any case I'd avoid the readback as of you can only access to the information that you populated in your thread/process, readback in a shared span does not give you all the information of the span.

PS: Regarding

> When finishing the span, onFinishSpan(span, finishTime). finishTime
is going to be the time you created the span in case you want to register a
log.
> This is the interesting one.. if we have both start and finish timestamps,

Here I meant *finishTime is going to be the time you **finished** the span in case you want to register a log.*

**Comment by adriancole** [comment]
Thanks for the feedback, and part of it is clearer which is that we
are getting quite abstract. I think we need to move concretely into
making something work or not.

@tutufool needs to add a tag when the span started and stopped,
suggesting which thread each occurred on
  * this doesn't need timestamps at all. It does require a means to
customize the span (spanCustomizer is our safe api for users to add
data)
@devinsba needs to add timestamp annotations at the time a span is stopped.
  * this could use the finish timestamp to avoid making new ones, and
still it would need spancustomizer as it is writing data

-- ps so far we aren't reading any data, just writing it..

@markmaxey was the latest and wanted to synchronize duration metrics
  * notably he wants to do this even if this is a noop span!
  * we don't currently know which if any data needs to be read (span
name etc) to do metrics, which makes this the hard part


The first two use cases are easily met with a global listener.

class SpanListener {
  onStart(SpanCustomizer span, long timestamp);
  onFinish(SpanCustomizer span, long timestamp);
}

It works because you aren't reading anything and just adding things.

you could even do it with less
onStart(TraceContext context, long timestamp);
onFinish(TraceContext context, long timestamp);

except this implies saving a reference to the tracer, so you can do
tracer.toSpan(context).annotate(timestamp, "foo")

Which means for the data adding thing, the first is really the better
design (you don't get into a race condition creating the tracer etc)

I think that the metrics in no-op use-case might be better done in a
different hook, or designed independently until its requirements
are made clear. wdyt?

**Comment by adriancole** [comment]
long chats with various folks.. span decorator (listener) is different than metrics export, significantly in terms of impact to library internals. This issue will stick with the listener thing, and a new one will open discussing "firehose mode", which can be used for metrics or anything else that needs 100% data (ex stream processing or short-term zipkin instance for support)

**Comment by adriancole** [comment]
https://github.com/openzipkin/brave/issues/557 forks the "firehose mode"

**Comment by obv-mikhail** [comment]
@adriancole are the current ScopeDecorators different from the span decorators proposed here?

**Comment by adriancole** [comment]
the outcome of this was FinishedSpanHandler. Since it includes the trace context, you can do quite a lot with it. this is documented in the brave/README.md

**Comment by obv-mikhail** [comment]
@adriancole what if I need to do something when a span is started? I need to edit MDC whenever a span is started. It is too late to do that once a span is finished.

**Comment by adriancole** [comment]
>
> @adriancole <https://github.com/adriancole> what if I need to do
> something when a span is started? I need to edit MDC whenever a span is
> started. It is too late to do that once a span is finished.
>
scope decorator is for this use case
https://github.com/openzipkin/brave/blob/bf2ddde7f29d030c79b308da30bec325ceb08c50/brave/src/main/java/brave/propagation/CurrentTraceContext.java#L153

Our current MDC support is built with this. It applies whenever a span is
current. Scoping of a span into MDC is something decoupled from when it is
started.

hop on https://gitter.im/openzipkin/zipkin if you want to chat more
