### ISSUE TITLE
propagate all http header attributtes

### ISSUE THREAD

**Issue by sstong123** [openzipkin/brave#534]
The below method can only propagation the http header attribute : "user-name" :

@Bean Tracing tracing(@Value("${zipkin.service:brave-webmvc-exampleA}") String serviceName) {
    return Tracing.newBuilder()
        .localServiceName(serviceName)
        .propagationFactory(ExtraFieldPropagation.newFactory(B3Propagation.FACTORY, "user-name"))
        .currentTraceContext(ThreadContextCurrentTraceContext.create()) // puts trace IDs into logs
        .spanReporter(spanReporter()).build();
  }

But in some case ,there are more than 1 header attribute in the request, how to propagation all header attributtes?

**Comment by adriancole** [comment]
There's no feature to propagate all headers. it is whitelist only (and
would take a lot of effort to make it blacklist)

**Comment by adriancole** [comment]
mind digging deeper into the use case here? maybe there's a way to get
what you want without passing all headers (there are request-specific
http headers, so for a lot of people propagating all headers would
interfere with downstream communication)

**Comment by sstong123** [comment]
For my case, whitelist is a bit difficult ,because there are many interfaces using different http headers to call downstream projects,and will add more http interface later. And I want the above **Tracing** bean to be as a jar file injected into other projects, so I can not always change whitelist after they are deployed.

**Comment by adriancole** [comment]
Curious.. why do you want to propagate all headers? Are you instead looking
to save the value of headers as tags in the span, or literally you want
"Content-Type: application/json" to override any later call's Content-Type
header?

**Comment by sstong123** [comment]
NOT save the value of headers as tags in the span!  just want the down systems  working,because I found if the header attribute is not in the whitelist ,the down systems can not get it.
In our code convention,some parameters are defined in the request  header,not in request body.

**Comment by adriancole** [comment]
OK I'm still trying to understand the use case, and sorry I haven't yet.
This is a tracing library. Usually propagation is used for request-scoped
variables. It is hard for me to imagine why every http header should be
propagated. Since we won't be supporting propagation of every header, I'm
trying to help you find a way to limit the scope from everything to
something more concrete.

**Comment by adriancole** [comment]
In other words, my question is what you are using this for? How is the
data used? Seems this isn't used for adding data to spans.. what are
you going to use this for? Is it looking up flags? or something else?

Knowing more might help us get closer to an alternative way to satisfy
your goals.

**Comment by sstong123** [comment]
OK,I want use the brave lib is to trace the **traceId** and **spanId** in log file.

e.g.:There are 2 systems: **A** and **B**
A call B from http protocol, e.g: A calls B's **getUsers** service(http://ip:port/B/users) ,but the paramters are defined in header,like:user-name,age,... If I want to log the  traceId and spanId in the A system,I should put the above **tracing** method in A's source code,correct?
The problem is here: after that,I find other paramenters like 'age' would be lost from B,so the B system can not work well,I want to find a easy way to propagate all the headers(because many interfaces have more headers).

**Comment by adriancole** [comment]
>
> A call B from http protocol, e.g: A calls B's *getUsers* service(
> http://ip:port/B/users) ,but the paramters are defined in
> header,like:user-name,age,... If I want to log the traceId and spanId in
> the A system,I should put the above *tracing* method in A's source
> code,correct?
>
so far so good.

> The problem is here: after that,I find other paramenters like 'age' would
> be lost from B,so the B system can not work well,I want to find a easy way
> to propagate all the headers(because many interfaces have more headers).
>
ok, so you have a header like "age: 37" and you later want to look it up
implicitly, like ExtraFieldPropagation.get("age")? (or have something call
that on your behalf) What are you doing with that data? Is this to
synchronize logs or is it business methods? What were you doing before
ExtraFieldPropagation came out? What are you planning to do differently
with this feature such that B system can work well?

**Comment by sstong123** [comment]
B's service saveuser:
@RequestMapping(value = "/saveuser", method = RequestMethod.POST)
	public String saveUser(@RequestHeader("user-name") String userNme,@RequestHeader("age") String age) {		
		return "OK";
	}
A's service serviceA:
  @RequestMapping("/serviceA", method = RequestMethod.POST)
    String home() {
    	return restTemplate.getForObject("http://ip:port/B/saveuser)", String.class);
    }

use http client call A's service serviceA put  "user-name" and "age" in the header,after send the request, the "age" will be lost from B

**Comment by adriancole** [comment]
> @requestmapping(value = "/saveuser", method = RequestMethod.POST)
> public String saveUser(@requestheader("user-name") String
> userNme,@requestheader("age") String age) {
> return "OK";
> }
>
use http client call A's service serviceA put "user-name" and "age" in the
> header,after send the request, the "age" will be lost from B
>
OK are all the apis you need to work with like this? (ex they have
requestheader annotations)
also, this example returns immediately.. I guess you have some other code
that you are substituting for "OK"? For example, where are you expecting to
read the "user-name" and "age" values?

**Comment by sstong123** [comment]
Yes,and I just write the sample code without any logic please ignore the method body, actually the age is null in B's service code(not propagated from A).

**Comment by adriancole** [comment]
ok a call from A to B will already work (passing the headers). The main
thing I'm trying to understand is what you plan to do with the data. For
example, do you only need the values declared on this interface propagated?
Or do you really need all headers? It could be easier to parse the
interface vs trying to propagate all headers.

**Comment by sstong123** [comment]
The above example is only one interface,so it easy to define the whitelist.
But in our systems, there are too many interfaces using different headers,and headers will be changed in the future(may add more attributes depends on the business), so I think it's better to propagate all of them from A to B instead of defining a whitelist in A.

**Comment by adriancole** [comment]
I'm going to close this issue as propagating all headers isn't a practical design, at least because headers like Content-Length etc will make no sense to forward across the graph. Open to a platform-specific way to annotate a header as something that should be propagated. Based on your code example, you could imagine `@Propagate @HeaderParam("user-id")` or something. However, it isn't likely we will ever propagate every header sent.

Closing this topic for now.. if it becomes popular to do otherwise, we'll revisit.
