### ISSUE TITLE
How to log the parentSpanId?

### ISSUE THREAD

**Issue by sstong123** [openzipkin/brave#537]
For log data analysis,also need to know the call chains,
but it seems the below config **parentSpanId** doesn't work:
%d{ABSOLUTE} [%X{traceId}/%X{spanId}/%X{parentSpanId}] %-5p [%t] %C{2} - %m%n

**Comment by adriancole** [comment]
I think others use log processing and need this, but I'd like to get a nod from at least 2 others before proceeding.

**Comment by adriancole** [comment]
looks like both cloudfoundry and finagle log parent span id in access logs. To be able to correlate alongside them, we'll need this

https://docs.cloudfoundry.org/concepts/http-routing.html#http-headers
https://github.com/openzipkin/brave/issues/150

I'll implement this across the board

**Comment by adriancole** [comment]
https://github.com/openzipkin/brave/pull/541
