### ISSUE TITLE
How do I use local span to follow the tracks of function calls ?

### ISSUE THREAD

**Issue by heavenyunyou** [openzipkin/brave#545]
We want to use local span to follow the function calls, but there's a problem: We cannot start a local span if there is a local span in current thread. If we do this, the new local span will replace the old one.

```
public static void startLocalSpan(String operation)
{
    brave.localTracer().startNewSpan(..., operation);
    // submit annotation and binaryAnnotation
}

public ststaic void finishLocalSpan()
{
    brave.localTracer().finishSpan();
}

public static void test()
{
    startLocalSpan("function test1");
    startLocalSpan("function test2");
    //Begin to call function test2
    test2();
    finishLocalSpan();
    finishLocalSpan();
}
```

So I want to know how can I use brave to follow the tracks of function calls. In particular, tracking nested function calls. 

Thanks!

**Comment by adriancole** [comment]
you'll want to look at
https://github.com/openzipkin/brave/tree/master/brave#local-tracing
and
https://github.com/openzipkin/brave/tree/master/brave#setting-a-span-in-scope-manually
(to set it in scope)

complete example:
https://github.com/openzipkin/brave/blob/master/brave/src/test/java/brave/features/sampler/AspectJSamplerTest.java#L81

**Comment by jorgheymans** [comment]
This is a question that was answered, issue can be closed.
