### ISSUE TITLE
JMS Tracing Example

### ISSUE THREAD

**Issue by andye2004** [openzipkin/brave#548]
This isn't a 'how do you do ....' type question but some people might think it looks like one :). Nor is it either a bug report or feature request so apologies for posting it here.

I have coded up an example of how to raise spans / propagate and join for JMS messaging and uploaded it [here](https://github.com/andye2004/brave-instrumentation-jms.git).

Reason I'm posting here is:

1. Hoping that some of the resident experts might comment on it, specifically how I've written the join code (in a method called attach).

2. To give an idea on a possible approach for JMS tracing to the many others asking about it on here.

It's probably worth mentioning that I have used 'brave.jms' as a java package name and 'brave-instrumentation-jms' as a maven artifactId, hopefully I'm not breaking any copyright rules but if this is an issue with the brave guys please let me know and I will update it accordingly.

Thanks for taking the time to look at this :)

andye2004

**Comment by adriancole** [comment]
closed by #764 thanks for being early to this!
