### ISSUE TITLE
Custom Kafka Topic

### ISSUE THREAD

**Issue by adriancole** [openzipkin/brave#549]
_From @Ajeeshreloaded on December 5, 2017 10:15_

Hi, Is it possible to configure custom Kafka topic name instead of default "zipkin" Kafka topic using Spring XML configuration?

```
<bean id="sender" class="zipkin2.reporter.kafka11.KafkaSender" factory-method="create">
    <constructor-arg type="java.lang.String" value="BrokerHost"/>
</bean>
```

_Copied from original issue: openzipkin/zipkin-reporter-java#80_

**Comment by adriancole** [comment]
We need an example of how to use a builder pattern in spring beans I guess. For example, this is KafkaSender.newBuilder().topic("foo")...build()

**Comment by adriancole** [comment]
we need to rebase our spring-beans over https://github.com/openzipkin/zipkin-reporter-java/pull/83

**Comment by jeqo** [comment]
Fixed by https://github.com/openzipkin/zipkin-reporter-java/pull/83
