### ISSUE TITLE
Feature Request: Kafka Consumer/Producer Interceptor implementation

### ISSUE THREAD

**Issue by dave-maldonado** [openzipkin/brave#552]
Hello, we're interested in instrumenting our Kafka Streams applications for distributed tracing with Zipkin and I came across your Kafka clients implementation. It would work great out the box for our applications but we have a hangup in instrumenting the [Confluent REST proxy](https://github.com/confluentinc/kafka-rest) since you cannot supply your own clients there.

What you _can_ do for the REST proxy (and any other Kafka application) is supply producer and consumer "interceptor" classes instead of clients [(see KIP-42)](https://cwiki.apache.org/confluence/display/KAFKA/KIP-42%3A+Add+Producer+and+Consumer+Interceptors). This works like your decorated clients by giving you access to the records and offsets going through consumers and producers.

Have you looked at providing an implementation based on interceptors instead of decorated clients? I'm pretty new to Zipkin in general but I'm willing to learn the ropes to help code this up.

Thanks!

**Comment by adriancole** [comment]
I don't think anyone has tried this. Feel free to give it a spin (noting
minimum client versions needed etc). Hop on
https://gitter.im/openzipkin/zipkin for advice.

Thanks for the offer!

**Comment by ImFlog** [comment]
I think this is mainly because we where aiming for 0.9 at the time and this feature appeared in 0.10.
Should we create a different instrumentation just for this (this could be our support for Kafka Stream) or should we remove 0.9 support on the current implementation ?
Personnaly not a big fan of the second option.

**Comment by adriancole** [comment]
Personally, I think we need kafka stream to be the use case, whether that's a separate module, or used in test classes for the interceptor approach. At any rate, I agree we shouldn't thrash by removing the current impl

**Comment by jeqo** [comment]
KafkaStreams has support for adding Clients using `KafkaClientSupplier` (https://kafka.apache.org/10/javadoc/org/apache/kafka/streams/KafkaClientSupplier.html). With current version (2.0) that supports Headers propagation, it will be _enough_ to instrument a Kafka Streams applications by only providing clients.

I also give a try to implement interceptors instrumented with Brave (https://github.com/jeqo/brave-kafka-interceptors), it duplicates most of the logic in `brave-instrumentation-kafka-clients` but also has to handle all the tracing instantiation (ie. sender, reporter,etc). Agree the would be useful have it as a separate module.

**Comment by ImFlog** [comment]
@jeqo agreed for Kafka Stream with the Supplier, it's better than using custom transformers and we should create the instrumentation for it.

For the interceptors maybe we should wait for the rule of Three ?

**Comment by jeqo** [comment]
@ImFlog yes. Working on that https://github.com/jeqo/brave/blob/kafka-streams/instrumentation/kafka-streams/src/main/java/brave/kafka/streams/TracingKafkaClientSupplier.java 

Once #753 is merged, I can create a PR for this and test it.

**Comment by jeqo** [comment]
Supported by https://github.com/openzipkin-contrib/brave-kafka-interceptor
