### ISSUE TITLE
localEndpoint should be nullable or not needed at all

### ISSUE THREAD

**Issue by bandrei** [openzipkin/brave#553]
Great job in putting this library together!  While prospecting the library for use, I was looking through the Brave configuration settings, and I'm a bit confused as to the need to set the localEndpoint when instantiating the tracer. What exactly is that localEndpoint trying to achieve, and why does it need to exist in the first place?

Is it because Zipkin needs to talk to the service? That would seems like a design flaw to me, since it creates a strong dependency to the environment in which zipkin is deployed.

**Comment by devinsba** [comment]
LocalEndpoint is configured because its a `Tracer` wide span property.
Spans are labeled with the service that they came from so that you can
search for spans from a specific origin

**Comment by adriancole** [comment]
Yep if you dont set anything your spans will come from an "unknown" origin.
This also makes service graph useless as it doesnt know any context about
the node being traced.

Maybe try one of the examples like brave-webmvc-example repo on github.
Sometimes this becomes more intuitive in practice. Feel free to catch us on
gitter openzipkin/zipkin with more questions as you get started.

**Comment by bandrei** [comment]
I see! So it's not really needed for communication but purely for labelling, so there is no criticality in putting accurate information there. Thank you!

**Comment by adriancole** [comment]
>
> I see! So it's not really needed for communication but purely for
> labelling, so there is no criticality in putting accurate information
> there. Thank you!
>
accurate info helps with clock skew correction, so if you can have accurate
info, supply it.
