### ISSUE TITLE
Why ClientRequestAdapter is set to @Deprecated

### ISSUE THREAD

**Issue by rangwea** [openzipkin/brave#555]
Why ClientRequestAdapter is set to @Deprecated ?

    This class ClientRequestAdapter  is set to @Deprecated,  and replaced by HttpClientParser?
    My app not only to use Http, but use gRpc, I can use ClientRequestAdapter, the base code don't modify.

**Comment by adriancole** [comment]
The entire package com.github.kristofa.brave is deprecated. We just added notes for things that have direct transition to the new apis. have a look here for things that are maintained https://github.com/openzipkin/brave/tree/master/instrumentation

**Comment by jorgheymans** [comment]
This is a question that was answered, issue can be closed.
