### ISSUE TITLE
Circular initialization in Propagation causes NPE

### ISSUE THREAD

**Issue by Logic-32** [openzipkin/brave#565]
The unit test
```
@Test
public void testNPE(){
	Propagation<String> bar = Propagation.B3_STRING;
	Tracing build = Tracing.newBuilder().build(); // NPE inside here
	System.out.println("hi");
}
```

Basically, it looks like, by referencing Propagation.B3_STRING _before_ ever creating a Tracing.Builder, B3Propagation.FACTORY will end up null.

My guess is that, because of where it is declared, Factory has yet to be initialized and it can't force the initialization.  Simply relocating B3_STRING down to below the Factory definition _may_ fix it.  Otherwise some larger refactoring will be needed.  FWIW, if I change Propagation.B3_STRING to Propagation.Factory.B3 it works fine (again, probably because Factory gets initialized properly).

This is actually wrecking a unit test of my own because it happens to do this between two different tests :\

**Comment by adriancole** [comment]
good find, thanks! https://github.com/openzipkin/brave/pull/566
