### ISSUE TITLE
Stop publishing brave-core/archive

### ISSUE THREAD

**Issue by adriancole** [openzipkin/brave#567]
I think it is time we stop publishing the brave-core apis in archive. camel is the only remaining user and it can be upgraded or stick with the same base code as we retrofitted brave-core to zipkin reporter2 recently. Building the archive directory is costly and maintenance causing. Also it makes it more confusing since there are two apis.

**Comment by jorgheymans** [comment]
:+1: 

Will ./archive also be moved outside of the source root somewhere ? I found it a bit of a pain to deal with when importing brave into an IDE.

**Comment by adriancole** [comment]
was planning to just delete it and leave it to version control (we could
make a branch for the last release that included it, though.. we did that
for the zipkin-server (the scala branch))

**Comment by adriancole** [comment]
@openzipkin/core this is imho a good idea, but a significant one to stop publishing the historical artifacts. I think it is time, and just pinging you in case you disagree.

**Comment by adriancole** [comment]
cc also @openzipkin/instrumentation-owners

**Comment by adriancole** [comment]
brave-core still uses an internal hook. I will try to scrub that before disconnecting the build (which will allow us to not maintain that hook forever)
