### ISSUE TITLE
Trace ids generate collisions pretty often

### ISSUE THREAD

**Issue by bandrei** [openzipkin/brave#575]
I have a Dropwizard service which uses Hystrix. I managed to hook Zipkin into the application, however when I look at the request logs I see traceId collisions that cover a timespan of over minutes and several requests.

I based my implementation on the thread here: https://github.com/openzipkin/brave/issues/195
I am not sure whether there is an issue with using Hystrix's concurrency strategy (i.e. the traceid is actually maintained at the Executor level across different requests), or whether the traceId generation is not random enough.

```
HystrixPlugins.getInstance().registerConcurrencyStrategy(new HystrixConcurrencyStrategy() {
                @Override
                public <T> Callable<T> wrapCallable(Callable<T> callable) {
                    Span spanInScope = tracing.tracing().currentTracer().nextSpan();
                    tracing.tracing().currentTracer().withSpanInScope(spanInScope);
                    return new TraceableHystrixCallable<T>(callable);
                }
            });
```

If I read the documentation correctly the `nextSpan()` call should create a new traceId if one doesn't exist already.

Also it might be important to note that I'm using `@Suspend` and `AsyncResponse` at the resources level, so linking the traceId that's generated on the incoming requests is likely to be lost because of this.

**Comment by adriancole** [comment]
Several requests is definitely too short for this to be a trace ID
generator collision problem. Maybe post the brave 4+ code you are using?
You can likely also tell by using normal dropwizard and hit with the same
amount of requests. I'm guessing this is instrumentation (possible
context-leak) problem just as we've not heard reports like this recently.

PS Are you using https://github.com/smoketurner/dropwizard-zipkin

**Comment by bandrei** [comment]
Additionally I have also set `traceId128Bit: true` but the problem still exists :/

**Comment by bandrei** [comment]
Yep, that's the one I'm using.

**Comment by adriancole** [comment]
there's no hystrix code there.. can you make a small repo or gist that can
reproduce the essence of the problem?

**Comment by bandrei** [comment]
I'll come back with an example, but it might take me a while.

**Comment by bandrei** [comment]
I'm closing this issue as it's no longer relevant. I believe the cause was the @ManagedAsync annotation around the http call which was probably not playing well with the tracing context thus resulting in the context leak.
