### ISSUE TITLE
BraveTracer#extract doesn't handle all 3 types of TraceContextOrSamplingFlags

### ISSUE THREAD

**Issue by tabdulradi** [openzipkin/brave#585]
`brave.opentracing.BraveTracer#extract` doesn't handle all 3 types of `TraceContextOrSamplingFlags`.
In line 184, only `result.context()` is called (which returns a value only if it's `type == 1`), ignoring the other 2 cases (`result.traceIdContext()` and `result.samplingFlags()`).

I am using BraveTracing with `AWSPropagation`, whose [Extractor does return a type 2 `TraceContextOrSamplingFlags`](https://github.com/openzipkin/brave/blob/master/propagation/aws/src/main/java/brave/propagation/aws/AWSPropagation.java#L353) if the header doesn't have a `Parent` information.

**Comment by adriancole** [comment]
This issue was moved to openzipkin-contrib/brave-opentracing#67
