### ISSUE TITLE
Get NoClassDefFoundError of ThreadLocalRandom  when using jre6

### ISSUE THREAD

**Issue by whg999** [openzipkin/brave#599]
when run in jre1.6.0_33，I got a exception:
Exception in thread "main" java.lang.NoClassDefFoundError: java/util/concurrent/ThreadLocalRandom
	at brave.internal.Platform.findPlatform(Platform.java:104)
	at brave.internal.Platform.<clinit>(Platform.java:27)
	at brave.Tracing$Builder.build(Tracing.java:271)

**Comment by adriancole** [comment]
Hi, are you using latest brave? I want to make sure before I debug
further. We aren't catching NoClassDefFoundError, though we do catch
ClassNotFoundException. NoClassDefFoundError hints at indirect class
usage.

**Comment by adriancole** [comment]
please also mention if there's anything interesting about your
classloader (osgi etc)

**Comment by whg999** [comment]
Thanks for you ack，I am using 4.14.1 with pure java application(no osgi/serverlet..):
Tracing.Builder builder = Tracing.newBuilder();
The exception code  is:
Platform jre9 = Platform.Jre9.buildIfSupported(zipkinV1Present);
when load Platform.Jre9 class, it required ThreadLocalRandom.

**Comment by adriancole** [comment]
Thanks. will fix asap. setting up jre 6 locally

**Comment by adriancole** [comment]
https://github.com/openzipkin/brave/pull/600
