### ISSUE TITLE
tracing across kinesis with camel-zipkin + brave

### ISSUE THREAD

**Issue by solidgains** [openzipkin/brave#610]
I have 2 spring-boot-camel apps. I am using the camel-zipkin library, which is using Brave under the hood.
My setup looks like this.
producer -> aws kinesis -> consumer

My goal is to have producer and consumer produce correlated spans I can view in zipkin. What's happening is that the producer is generating a unique trace id and span, and the consumer is producing a trace id and span. However, the consumer just creates a new trace and span id, it doesn't add a span to the existing trace. 

I inspected the headers getting passed to the consumer, and the trace/span headers are getting passed to the consumer. The consumer is just ignoring them and creating new on trace.

I tried swapping out kinesis for simple rest, and rest works. Tracing fails when I uncomment the code to communicate via kinesis.

in consumer app
`package com.example.config;

import org.apache.camel.builder.RouteBuilder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Configuration;

@Configuration
public class Routes extends RouteBuilder {

    @Autowired
    private KinesisProperties kinesisProperties;

    @Override
    public void configure() throws Exception {

        //from(kinesisProperties.getCamelUrl()).routeId("consumer").to("log:out");
        rest("/hello").consumes("application/json").produces("application/json")
                .post().route().transform().constant("Hello World").routeId("consumer").to("log:out");
    }
}
`

in producer app
`package com.example.kinesisproducer.config;

import org.apache.camel.builder.RouteBuilder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Configuration;

@Configuration
public class Routes extends RouteBuilder {

    @Autowired
    private KinesisProperties kinesisProperties;

    @Override
    public void configure() throws Exception {
        //rest("/demo").consumes("application/json").produces("application/json")
        //        .post().route().transform().constant("Hello World").setHeader("CamelAwsKinesisPartitionKey", constant("hello")).routeId("producer").to(kinesisProperties.getCamelUrl());
        rest("/demo").consumes("application/json").produces("application/json")
                .post().route().removeHeaders("CamelHttp*").transform().constant("Hello World").routeId("producer").to("http://localhost:8080/camel/hello");
    }
}
`

**Comment by solidgains** [comment]
Thanks, I'll put a ticket there. 

On a side note, would you be able to point me to some example code or docs that shows how to get the trace/span headers in the consumer and update them with the new span. I have a feeling it's fairly easy, but Im not sure which classes to use.

**Comment by jorgheymans** [comment]
Closing this, @solidgains  if you still have questions feel free to drop by on https://gitter.im/openzipkin/zipkin
