### ISSUE TITLE
brave bom

### ISSUE THREAD

**Issue by jorgheymans** [openzipkin/brave#619]
A brave bom would allow applications to easily force-align all versions of the brave instrumentation libraries used.
```
<dependency>
        <groupId>io.zipkin.brave</groupId>
        <artifactId>brave-bom</artifactId>
        <version>${brave.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
```

This could be especially useful for applications using brave via sleuth-starter, since it does not define all instrumentation libraries. Also, brave is probably going to crank out new versions more often than sleuth, so having to update just the bom version would be an easy way to track them.

@adriancole @devinsba unsure if we need different boms for brave instrumentation and zipkin reporters?

**Comment by adriancole** [comment]
If a bom can import a bom, probably having one for zipkin reporter makes
sense as there are a number of senders used there. Ex similar reason we
made spring-beans there

**Comment by jorgheymans** [comment]
sure, a bom can import other boms, for example in [spring-boot-dependencies](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-dependencies/pom.xml) , see [jackson](https://github.com/spring-projects/spring-boot/blob/3dea6fc645a6157447a2e98a036b01fcd2fcce00/spring-boot-project/spring-boot-dependencies/pom.xml#L587) and many others

**Comment by jorgheymans** [comment]
@adriancole is the release cycle of brave such that you always release everything together, ie doing the release prepare/perform dance from the [repo](https://github.com/openzipkin/brave) root ?
