### ISSUE TITLE
How should we name a span when the route is empty on status 200

### ISSUE THREAD

**Issue by adriancole** [openzipkin/brave#621]
I noticed with an OPTIONS request that the span name defaulted to "options" not including a matched template. This is due to no route being defined for that method (though the OPTIONS request was valid). How should be map this? "options not_found" as there's no route defined for this? or leave it as "options" relegating to the path to clarify it.

**Comment by basvanbeek** [comment]
I think the most common case for OPTIONS is that most people handle this in a generic middleware for CORS purposes and do not really have any routing distinctions.

I even question if in many cases tracing OPTIONS requests is just pure added noise.

**Comment by adriancole** [comment]
Good point. Maybe we dont have to solve particularly for this. At any rate
the span name "options" is fixed cardinality and no worse than before.

**Comment by adriancole** [comment]
so this will end up as default ("get")
