### ISSUE TITLE
Release 4.16.3 so sleuth has a non-snapshot bom

### ISSUE THREAD

**Issue by spencergibb** [openzipkin/brave#630]
We had to back sleuth out of today's (Mar 2, 18) spring cloud release train because there wasn't a release.

**Comment by devinsba** [comment]
If possible in the future you can ask in gitter for a release. There are a few of us with commit/release priviledges that are online during Adrian's night time.

Releasing `4.17.0` now

**Comment by devinsba** [comment]
Closed by 402773fdbcb700a941eb92e1701993bcbe617a11

Available as `4.17.0` in maven central

**Comment by adriancole** [comment]
thanks for helping!

I'll make release notes after we do a 4.17.1 (we should get the other bom
in place, the one for zipkin-reporter before announcing)
