### ISSUE TITLE
Support Trace Context format

### ISSUE THREAD

**Issue by adriancole** [openzipkin/brave#657]
Trace Context format consists of two headers `traceparent` and `tracestate`; `traceparent` holds roughly the same information as our TraceContext does. Notably, it misses the incoming parent id (parent is more like our spanId), but this is something we have worked around in amazon propagation already. `tracestate` includes a copy of any other trace state (like a cloud vendor), as well a copy of ours.

https://github.com/w3c/distributed-tracing

Currently, the left-most field of `tracestate` is documented but under contention. It currently is correlated with `traceparent`. This means you can tell the client's system by the name of the label, unless that label is generic.

```
// on incoming, extract the part of the tracestate that isn't ours and propagate it
// along with our potentially restarted state
lastSystem = tracestate.charactersUntilEquals();
myState, remaining = tracestate.removeMe();
if (myState exists) {
  if (lastSystem !== me) log("upstream was $lastSystem, resuming our last position");
  newChild(myState, remaining);
} else {
  log("upstream was $lastSystem, restarting trace");
  newTrace(remaining);
}
 // on outgoing add our state to whatever's remaining
tracestate = currentState + remaining; // ex remaining could be "" or ",r
```

The code above doesn't resemble our actual code, it is just a sketch. The code will be very very similar to AWSPropagation

**Comment by sanderino666** [comment]
Hi @adriancole, 

We just started using Spring Cloud Sleuth in our product and we need to support multiple cloud vendor which in turn leads to multiple implementations (AWS, Azure, GCP, Brave). We noticed this cool new spec: https://w3c.github.io/trace-context/ which will help us in not having to create multiple implementations. 

Since this is currently a draft, could you give us any insight in when this draft will be finalized and an implemention is available in Brave? 

Greetz

Sander

**Comment by adriancole** [comment]
abstractly speaking, what you say is correct. However, we dont usually
implement and maintain features based on abstract value. which provider are
you using which uses this format?

On Dec 11, 2018 5:07 PM, "Sander Wartenberg" <notifications@github.com>
wrote:

Hi @adriancole <https://github.com/adriancole>,

We just started using Spring Cloud Sleuth in our product and we need to
support multiple cloud vendor which in turn leads to multiple
implementations (AWS, Azure, GCP, Brave). We noticed this cool new spec:
https://w3c.github.io/trace-context/ which will help us in not having to
create multiple implementations.

Since this is currently a draft, could you give us any insight in when this
draft will be finalized and an implemention is available in Brave?

Greetz

Sander

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openzipkin/brave/issues/657#issuecomment-446125521>,
or mute
the thread

**Comment by adriancole** [comment]
work can carry-on here https://github.com/openzipkin-contrib/brave-propagation-w3c
