### ISSUE TITLE
what is mean brave.flush annotation?

### ISSUE THREAD

**Issue by rangwea** [openzipkin/brave#658]
![image](https://user-images.githubusercontent.com/12287570/37598499-52709bba-2bbd-11e8-835d-0f94d3028c4b.png)

My trace have a annotation like up. I want to know the meaning about this annotation.

**Comment by adriancole** [comment]
This means the tracing code never finished the client side of the span.
Usually this is a bug. What's tracing the client side?

**Comment by rangwea** [comment]
servlet. and i finish this span in my finally code block.

**Comment by adriancole** [comment]
servlet isn't a client. some client call likely caused the flush as looking
at lack of a client receive annotation.

please join https://gitter.im/openzipkin/zipkin for more as troubleshooting
here spams a lot of people
