### ISSUE TITLE
Is there an example to trace webservice(axis2) using brave?

### ISSUE THREAD

**Issue by unlimitbladeworks** [openzipkin/brave#659]
@adriancole 
hi~
I see there is brave-instrumentation-jaxrs2,Does it support the webservice(axis2)? can some provide an example?

**Comment by adriancole** [comment]
I know there is cxf support, but I've not seen or heard of a request for
axis beyond yours

**Comment by unlimitbladeworks** [comment]
Because our project is older, most of the clients are using the Axis2.....May I refer to the principle of cxf to write a axis2-zipkin client?

**Comment by adriancole** [comment]
yes you can look at this or another rpc client.
https://github.com/apache/cxf/tree/master/integration/tracing/tracing-brave/src/main/java/org/apache/cxf/tracing/brave

We likely won't do anything in the core repo until something is a bit more
explored (usually we wait for a few to request something)

Feel free to join https://gitter.im/openzipkin/zipkin for support meanwhile

**Comment by unlimitbladeworks** [comment]
Okey,thanks...
