### ISSUE TITLE
Add trace-context propagation helper for RxJava2

### ISSUE THREAD

**Issue by adriancole** [openzipkin/brave#664]
There are a number of issues on the sleuth project relating to RxJava2. Many of these have to do with TraceContext being lost during the library.  While automatic tracing of rxjava2 would be a potentially tricky task (with a lot of complexity on which threads to skip etc), continuing a trace context should be relatively straight-forward and prevent broken traces.

This issue could start a brave-context-rxjava2 whose only purpose is preventing people from breaking traces via a scheduler hook.

The propagation-only scheduler hook could be similar but smaller scoped than https://github.com/spring-cloud/spring-cloud-sleuth/pull/775

See similar issues about broken traces:
https://github.com/spring-cloud/spring-cloud-sleuth/issues/909
https://github.com/spring-cloud/spring-cloud-sleuth/issues/398

**Comment by adriancole** [comment]
WIP https://github.com/openzipkin/brave/pull/665

**Comment by asarkar** [comment]
couchbase-java-client is on RxJava [1.6.0-SNAPSHOT](https://github.com/couchbase/couchbase-java-client/blob/master/pom.xml#L31)

**Comment by adriancole** [comment]
@asarkar right.. seems https://github.com/couchbase/couchbase-jvm-core is where rxjava is defined, and yes it is still using rxjava 1.x

**Comment by adriancole** [comment]
@asarkar I think we need to qualify the "rxjava" issue with that couchbase driver. For example, the internals are a somewhat complex mix of a span stack and opentracing. Can you please make an example project on https://github.com/openzipkin/sleuth-webmvc-example that reproduces your problem? For now, I'm going to focus on things that are more simply rxjava in nature

**Comment by adriancole** [comment]
deferred the couchbase thing based on [more details here](https://github.com/spring-cloud/spring-cloud-sleuth/issues/914#issuecomment-378093528). I'd like to see this reproducible as at the moment it doesn't seem like something generically addressing rxjava hooks will fix.

**Comment by asarkar** [comment]
Little busy now, but I expect to be able to provide a reproducible problem by end of the week
