### ISSUE TITLE
Potential performance issue in StrictCurrentTraceContext

### ISSUE THREAD

**Issue by tutufool** [openzipkin/brave#667]
Hi,

My profiling indicates that StrictCurrentTraceContext.newScope() is a hot spot.

I guess it's caused by early Error creation:

return new StrictScope(previous, new Error(String.format("Thread %s opened scope for %s here:",
        Thread.currentThread().getName(), currentSpan)));

We should defer the Error creation when we really need it to avoid String.format(...)

I think a Callable<Error> would help.

Let me know your concerns.

Thanks

Leon

**Comment by adriancole** [comment]
hi.. sorry strict context should be probably more obviously marked as a
debugging tool, not for production. We made it for tests so that we capture
the calling stack trace. If we don't capture the calling stack trace (via
allocating an error), it is hard to figure out who leaked the code. So,
basically we use this while developing instrumentation, but wouldn't expect
people to use it in a performance sensitive place.

**Comment by tutufool** [comment]
While I expect this is an output of previous discussed issue:
https://github.com/openzipkin-contrib/brave-opentracing/issues/48

The problem is: a scope activate action must be paired with a close action.
If that scope is propagated to another thread via InheritableThreadLocal, then it might not be closed.

**Comment by adriancole** [comment]
> While I expect this is an output of previous discussed issue:
> openzipkin-contrib/brave-opentracing#48
>
> The problem is: a scope activate action must be paired with a close action.
> If that scope is propagated to another thread via InheritableThreadLocal, then it might not be closed.

CurrentTraceContext.Default.create() is not inheritable. The javadoc
mentions warnings around things and suggests this.

The Strict one literally says it is for development "Useful when
developing instrumentation as state is enforced more strictly."

**Comment by adriancole** [comment]
yep you have to manually change because when making brave 4 we wanted to
have same default as brave 3 which was inheritable

**Comment by tutufool** [comment]
OK, then I'll close this issue
