### ISSUE TITLE
resteasy no-arg constructor

### ISSUE THREAD

**Issue by rodislav** [openzipkin/brave#668]
Feature request

Please add no-args constructors to @Providers, since resteasy is incapable of handling classes without one, even though you can have @Inject for a constructor with args, it'll not work. And so far, when I try to use instrumentation-jaxrs2 with resteasy impl, it fails because it can find no-args constructor for `TracingFeature`

**Comment by rodislav** [comment]
I've created a change to test it and it worked just fine
https://github.com/rodislav/brave/commit/e2127301a302d2d321a7257de3395f553a54868d

@adriancole , can I add these changes in `4.18.3-SNAPSHOT` and create a pull request ?

**Comment by adriancole** [comment]
I am not very keen on this. Public ctors very much limit what can be done
later.

We do test with resteasy and this isnt the only way to accomplish the goal.
Can you please show in brief your project setup? Lets try to find a way.

**Comment by adriancole** [comment]
What i am most interested in, is how you are able to configure tracing and
not this, as almost no type of ours has a public ctor..

When thinking about tracing setup, if resteasy has this constraint and it
must be used.. maybe configuring the servlet filter instead of the
container one. The customizing filter in worst case can be wrapped in your
own public no args class. Hope it doesnt get to that and sorry you are
having trouble.. but yeah I dont want resteasy to change our class design
unless absolutely necessary.

**Comment by rodislav** [comment]
Hi, I totally understand your concerns, I'll create a small example and will add it to a subfolder in a branch, to not mess the main three

As I saw somewhere in specs of resteasy, it requires always an empty constructor and if a class (_for example: `SpanCustomizingContainerFilter`_)  is anontated with `@Provider` it'll try to instantiate it and will fail with NPE

I've tried to create beans with `.create()` with no luck

**Comment by rodislav** [comment]
I almost forgot, resteasy requires a no-args constructor, only if there's at least one other constructor with 1..N arguments! (_where N > 0_)

**Comment by adriancole** [comment]
do me a favor. when you figure things out? please cite them as in docs or
line of code in their github repo. Will help hunt down things later.

Meanwhile keep up the good detective work!

**Comment by rodislav** [comment]
sure, I'll do it, even though, this can take some time as I'm full with other tasks.

**Comment by adriancole** [comment]
ok with me. right now you are the only one noticing this, but if this
changes will ping you.

**Comment by rodislav** [comment]
Hello, I cannot reproduce the issue with `resteasy 3.5.0` and `wildfly 12` I've codded a example to show that it works, and as I see it the problem was that I was using wrongly the outdated `resteasy 3.0.24` from `wildfly 11`

but I'll confirm this part bit later with an actual example on my side then I'll post the results here and after I think we can close the ticket

// need a bit more time

**Comment by rodislav** [comment]
This issue can be closed, as the problem remains with older version of resteasy, the newes packages are working just fine. We'll upgrade all microservices on our side.
