### ISSUE TITLE
Allow for dynamic ServiceNames on the "server"

### ISSUE THREAD

**Issue by dguggi** [openzipkin/brave#68]
Hi,

this issue somehow relates to #50 and #18 

In order to avoid the "Service appears as ServiceA,ServiceB" issue, we have to override the serviceName on the client to match the server's serviceName (using setCurrentClientServiceName).

However suppose that we have a (server) application "app" which provides several fine-grained services as follows:
- greetingService
- userService
- etc.

In zipkin-ui I'd like to see services as "greetingService" and "userService" rather than "app". This seems currently impossible as we cannot override the endpoint's serviceName on the "server" side.

I got this working by adding the functionality (that is already available on "client-site") on the server (using setCurrentServerServiceName) and could also provide a pull request for this.

Another option would be to make the Endpoint also a ThreadLocal as already discussed in #50 

thank you,
daniel

**Comment by kristofa** [comment]
Ok. Understood. I guess this means you will have to write specific server side code that is specific for your case which supports submitting the service names of your choice? You can't use 'generic' implementations like the ones we have for resteasy, jersey,...

**Comment by dguggi** [comment]
indeed - I use a proprietary (remoting) framework (based on hazelcast). So therefore I have custom interceptors on the client-/server-side. On the server this looks something like this:

````java
serverTracer.setStateCurrentTrace(determineTraceId(), determineSpanId(), determinteParentSpanId(), determineSpanName());
serverTracer.setCurrentServerServiceName(determinteServiceName());
serverTracer.setServerReceived();
// execute logic...
serverTracer.setServerSend();
````

So actually I just need the same functionality on the server-side as on the client-side (setCurrentServerServiceName). This change would also be backward compatible.

Let me know if you want me to "pull-request" this (setCurrentServerServiceName) functionality.

ty, daniel

**Comment by adriancole** [comment]
In Brave 4.3, this is now possible, as you can customize span naming dynamically with `HttpTracer.serverParser`
