### ISSUE TITLE
Consider immediately flushing certain "extra fields" to a log layer

### ISSUE THREAD

**Issue by adriancole** [openzipkin/brave#682]
https://github.com/spring-cloud/spring-cloud-sleuth/issues/927#issuecomment-378900051 discusses the understood problem of a race condition when implementing `CurrentTraceContext` hooks for tools like MDC. Thanks to @dhoffi for elaborating this.

The overal problem is that logging isn't immediately flushed when you set a variable. To do that, you need to know the underlying impl, like MDC: Ex redundant looking commands happen here:
```java
    @SendTo(SourceChannels.OUTPUT)
    public void timerMessageSource() {
        MDC.put(BUSINESS_PROCESS_NAME, ...);
        ExtraFieldPropagation.set(sleuthTracer.currentSpan().context(), BUSINESS_PROCESS_NAME, ...);
    }
```

would be to leave out the other either by default:
```java
    @SendTo(SourceChannels.OUTPUT)
    public void timerMessageSource() {
        ExtraFieldPropagation.set(sleuthTracer.currentSpan().context(), BUSINESS_PROCESS_NAME, ...);
    }
```

or by a special command like "flush" which attempts to set the thing immediately
```java
    @SendTo(SourceChannels.OUTPUT)
    public void timerMessageSource() {
        ExtraFieldPropagation.flush(sleuthTracer.currentSpan().context(), BUSINESS_PROCESS_NAME, ...);
    }
```

Eventhough #577 will solve the problem permanently, we might be able to get a tactical win by establishing some hook for immediately flushing certain (or all) keys to the current trace context.

This would only work in implementations that don't rely on scopes internally. For example, `MDC.put("key", "value")` is fine, but `try (Scope scope = context.scope("key", "value")` would not.

This has some cleanup implications, but we might be able to manage them in how we implement the scope field for `ExtraFieldsPropagation`. This all is only possible because "extra field" support is in the core library, so we can consider special-case it.

**Comment by adriancole** [comment]
@dhoffi question: I assume you are ok if all extra fields are synced to MDC? or do you want to cherry-pick?

**Comment by dhoffi** [comment]
well as the strong recommendation is not to put too much data in Propagation, I think it would be fine if exactly the fields of `spring.sleuth.baggage-keys` and `spring.sleuth.propagation-keys` would be synced to MDC, wouldn't it?

**Comment by adriancole** [comment]
>
> well as the strong recommendation is not to put too much data in
> Propagation, I think it would be fine if exactly the fields of
> spring.sleuth.baggage-keys and spring.sleuth.propagation-keys would be
> synced to MDC, wouldn't it?
>
off the top of my head I don't know if these are the same :P will look into
it and thanks for mentioning your goal!

>

**Comment by frodonLD** [comment]
Hello...
Plz what about this feature? Do you have a workaround for now?

**Comment by adriancole** [comment]
haven't thought about this since last note. workaround currently is the first thing I wrote which is to use MDC.. It seems if you have access to brave's api you would have access to MDC also, right? what am I missing..

**Comment by frodonLD** [comment]
I'm currently working with reactor and I find simpler to use `ExtraFieldPropagation` only, to avoid to think about how and where to remove my fields from the MDC for each thread.

**Comment by adriancole** [comment]
I will try to figure out a solution with @anuraaga

**Comment by jcchavezs** [comment]
Maybe relevant. In my MDC library I do it the other way around, I add
something called "providers" to the logger where it reads tracing data and
include it in logs: https://github.com/jcchavezs/mdctx#providers

**Comment by adriancole** [comment]
> Maybe relevant. In my MDC library I do it the other way around, I add
something called "providers" to the logger where it reads tracing data and
include it in logs: https://github.com/jcchavezs/mdctx#providers

This is relevant, something log4j2 supports but not others in my recollection. Back when I worked on opencensus, I [helped review](https://github.com/census-instrumentation/opencensus-java/pull/1371) this which is similar https://github.com/census-instrumentation/opencensus-java/blob/2903747aca08b1e2e29da35c5527ff046918e562/contrib/log_correlation/log4j2/src/main/java/io/opencensus/contrib/logcorrelation/log4j2/OpenCensusTraceContextDataInjector.java

Main concerns are:
* framework specific (log4j2)
* can cause a lot more garbage as the implementation implies copying maps (maybe on each log entry!)
* relies on static initialization and static context lookup which is awkward in environments like spring

**Comment by adriancole** [comment]
actually the log4j2 thing doesn't require copying maps on read, just that above impl does https://logging.apache.org/log4j/2.x/log4j-core/apidocs/org/apache/logging/log4j/core/ContextDataInjector.html#rawContextData--

Anyway an optimized form in the log4j2 module can exist and for example skip any flush-through optimizations if such a plugin exists. something specific like this would deserve its own issue I think. thanks for the thought @jcchavezs!

**Comment by adriancole** [comment]
finally readying an implementation #1130

**Comment by adriancole** [comment]
documented here https://github.com/spring-cloud/spring-cloud-sleuth/wiki/Spring-Cloud-Sleuth-3.0-Migration-Guide
