### ISSUE TITLE
Spring Integration Instrumentation Request

### ISSUE THREAD

**Issue by melavoyraja** [openzipkin/brave#687]
I am using Spring 4.2 and Spring Integration 4.2, here is the flow that I am trying to trace Spring WebMVC Controller -> Outbound Gateway -> Direct Channel -> Transformer -> Direct Channel -> Inbound Gateway(handle request -- this is a SOAP service using Spring WS) and then response back through reply channel and then to controller. For underlying messaging propagation I am using AMQP(Spring-rabbit).

**Comment by jorgheymans** [comment]
@melavoyraja this should be covered mostly through spring-cloud-sleuth, nothing specific in brave that will be addressed. Issue can be closed.

**Comment by jeqo** [comment]
Closing this one. Spring Sleuth with Spring Integration docs: https://cloud.spring.io/spring-cloud-sleuth/reference/html/#spring-integration-and-spring-cloud-stream
