### ISSUE TITLE
Add tls support

### ISSUE THREAD

**Issue by bputt** [openzipkin/brave#691]
Feature Request

When setting up the zipkin endpoint, it'd be helpful to enable TLS

OkHttpSender.create("https://127.0.0.1:9411/api/v2/spans")

Ideally, we could pass in a jks/pkcs12 cert, password, and a CA bundle

**Comment by adriancole** [comment]
this would be a request to https://github.com/openzipkin/zipkin-reporter-java repo

regardless, you can use normal java args to override the keystore information, or use OkHttpSender.Builder.clientBuilder() to do this explicitly
