### ISSUE TITLE
why can't find AutoValue_*(e.g. AutoValue_NoopSpan) class under the package brave

### ISSUE THREAD

**Issue by xiashiwendao** [openzipkin/brave#692]
I get the master branch, but can't compile successful.
1. parent pom, the plug in net.orfjackal.retrolambda:retrolambda-maven-plugin:2.5.1 can't be download, I just comment it. 
2. special, brave project can't find the class "AutoValue_NoopSpan"; but in the brave-4.18.jar I can see the AutoValue_* class just under the brave package.

what's wrong?

**Comment by adriancole** [comment]
auto-value is a code generator. Is this causing you problems? https://github.com/google/auto/tree/master/value

**Comment by LijyCasey** [comment]
I've solved question 1 yesterday but I dont know why it happened. Here is my solution (use Eclipse,btw):
click window->preferences->maven->lifecycle mappings->open workspace lifecy clemappings metadata 
and add following codes in lifecycle mappings' metadata(if you never setting before ,it may create a new xml):
`<?xml version="1.0" encoding="UTF-8"?>
<lifecycleMappingMetadata>
    <pluginExecutions>
        <pluginExecution>
            <pluginExecutionFilter>
                <groupId>net.orfjackal.retrolambda</groupId>
                <artifactId>retrolambda-maven-plugin</artifactId>
                <goals>
                    <goal>process-main</goal>
                </goals>
                <versionRange>[1.3,)</versionRange>
            </pluginExecutionFilter>
            <action>
                <ignore />
            </action>
        </pluginExecution>
        
    </pluginExecutions>
</lifecycleMappingMetadata>`
save and click reload workspace lifecycle mappings metadata. maven ->update project Q1 resolved.

**Comment by adriancole** [comment]
Thanks for the help. PS we don't use auto-value anymore, so this is no longer relevant
