### ISSUE TITLE
Lost a span when instrumentation httpclient

### ISSUE THREAD

**Issue by GreedyPirate** [openzipkin/brave#701]
I want to instrumentation httpclient 4,4.X with brave,  here is my pom
```
       <dependency>
            <groupId>io.zipkin.brave</groupId>
            <artifactId>brave-instrumentation-httpclient</artifactId>
            <version>4.19.2</version>
        </dependency>
        <dependency>
            <groupId>io.zipkin.reporter2</groupId>
            <artifactId>zipkin-sender-okhttp3</artifactId>
		<exclusions>
		    <!-- version conflict  2.5.0-->
			<exclusion>
				<groupId>io.zipkin.zipkin2</groupId>
				<artifactId>zipkin</artifactId>
			</exclusion>
		</exclusions>
        </dependency>
	<dependency>
		<groupId>io.zipkin.zipkin2</groupId>
			<artifactId>zipkin</artifactId>
			<version>2.8.3</version>
		</dependency>
        <dependency>
                <groupId>com.squareup.okhttp3</groupId>
                <artifactId>okhttp</artifactId>
                <version>3.8.1</version>
        </dependency>
```
build CloseableHttpClient :

```
OkHttpSender okHttpSender = OkHttpSender.create("http://127.0.0.1:9411/api/v2/spans");
AsyncReporter<Span> spanAsyncReporter = AsyncReporter.create(okHttpSender);
Tracing tracing = Tracing.newBuilder()
			.localServiceName("back<->end")
			.propagationFactory(ExtraFieldPropagation.newFactory(B3Propagation.FACTORY,"user-name"))
			.currentTraceContext(new StrictCurrentTraceContext()) // puts trace IDs into logs
			.spanReporter(spanAsyncReporter).build();
HttpTracing httpTracing = HttpTracing.create(tracing);
CloseableHttpClient httpclient = TracingHttpClientBuilder.create(httpTracing).build();
```
this project called "back<->end", and it invoke two services, however, in once call， the zipkin web console trace did not show "back<->end" span，why？
￼
![1526097342120](https://user-images.githubusercontent.com/14834990/39953307-6845fbf6-5598-11e8-8c59-df3d407b34e7.jpg)

that is kind of weird￼, need your help @adriancole

**Comment by GreedyPirate** [comment]
I learn instrumentation httpclient 4,4.X from [brave-httpclient](https://github.com/openzipkin/brave/tree/master/instrumentation/httpclient), here is the test code
`
CloseableHttpClient client = TracingHttpClientBuilder.create(httpTracing).disableAutomaticRetries()
        .addInterceptorFirst((HttpRequestInterceptor) (request, context) ->
            request.setHeader("my-id", currentTraceContext.get().traceIdString())
        ).build();
`
I understand that I should build CloseableHttpClient by TracingHttpClientBuilder, but some variables confuse me，like httpTracing，and
`
RecordedRequest request = server.takeRequest();
takeSpan();
`
they ara in the  ITHttpClient class which from <artifactId>brave-instrumentation-http-tests</artifactId>
I also can not find how set service name and service address

**Comment by llinder** [comment]
Are you able to share the JSON output for this trace?   My suspicion is that the service "back<->end" is only instrumenting http client calls and the downstream service (aicar-engine??) is instrumenting the service endpoints.  When this is the case the client call and the downstream server call are collapsed into one span and the span name assumes the name of the downstream service.  If you click on the span where you are expecting to see "back<->end" it should show both a client send and server receive with the right names.

**Comment by GreedyPirate** [comment]
[trace.zip](https://github.com/openzipkin/brave/files/1999634/trace.zip)
@llinder i put it in a zip file and more info at below 
a interface in project back-end, i call it by postman, in my opinion, this roject did not record a span from outside request , skip it and when i call downstream service(aicar-engine) by httpclient framework, it begin works, it doesn't seem like be my fault when i instrumenting http client

**Comment by jorgheymans** [comment]
This is more of a question, please drop by on https://gitter.im/openzipkin/zipkin for more direct support. Issue can be closed.
