### ISSUE TITLE
Brave erased the browsing history without any user interaction

### ISSUE THREAD

**Issue by eTorAken** [openzipkin/brave#702]
Hello, I would like to report a bug. 

When I open the Brave "History" section, it only shows me the last 10 days browsing history.

I do not remember having cleared my history manually. I'm very frustrated as I was looking for a website I found a month ago.

Do you guys have the same problem?

I'm running 0.22.669 version on Windows 10.

**Comment by devinsba** [comment]
I believe this is the project you are looking for: https://github.com/brave
