### ISSUE TITLE
http.route lost in async response

### ISSUE THREAD

**Issue by xihw** [openzipkin/brave#715]
After upgrading Brave from 4.17.1 to 5.0.0, I can no longer see path(or say route) as part of the span name (see attached below). My service is a dropwizard service handling bunch of AsyncResponse calls.

Looking into the Brave code, I suspect this commit https://github.com/openzipkin/brave/commit/a02938f56caa7abcbfa27757e5a32221193cba77#diff-786c3cf4f7c96c394374144674cd860d changed the behavior. It constructs the route at the beginning(REQUEST_MATCHED) and set into containerRequest properties as "http.route", however when event is FINISHED that's another thread who is trying to fetch the property but it gets lost.

Anyone notices this ? Should we fix it by moving setProperty("http.route"...) to under "FINISHED" ?

**Comment by xihw** [comment]
![screen shot 2018-06-13 at 3 27 42 pm](https://user-images.githubusercontent.com/33913187/41382444-0b495144-6f21-11e8-93f2-3c7552070096.png)

**Comment by adriancole** [comment]
possibly. you can see in our tests a bunch of sample endpoints. can you
give a sample that breaks and is fixed by moving? worst case we have to do
the call twice or detect async to tell which state hook to use

**Comment by adriancole** [comment]
PS I innocently made this test case and jersey doesn't like it..

```java
  @GET
  @Path("asyncItems/{itemId}")
  public void asyncItem(@PathParam("itemId") String itemId, @Suspended AsyncResponse response) {
    new Thread(() -> response.resume(itemId)).start();
  }
```

This is same code as the non-templated thing, except jersey fails mysteriously.. sometimes, it returns the body as "H" as opposed to the input like "1" or "2". Other times, it fails like this:

```
java.net.ProtocolException: Unexpected status line: TTP/1.1 200 OK
```
Note the missing "H" !!! Also, this fails regardless of if the tracing filter is installed or not..

I will try another type of async path parameter reading test if I can figure one out.

**Comment by adriancole** [comment]
the above error was due to async not enabled in the servlet runtime!

https://github.com/openzipkin/brave/pull/718 should fix the underlying visibility problem
