### ISSUE TITLE
ThreadLocalSpan - Tomcat complains probable memory leak

### ISSUE THREAD

**Issue by melavoyraja** [openzipkin/brave#716]
I have just added a channel interceptor similar to https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/TracingChannelInterceptor.java for testing traces. All worked fine and when I stop the Tomcat it complains that there is a probable memory leak.

Spring Integration Version - 4.3
Spring Framework - 4.3
Tomcat - 7.5

```
created a ThreadLocal with key of type [brave.propagation.ThreadLocalSpan$2] 
(value [brave.propagation.ThreadLocalSpan$2@1d6e9581]) and a value of type 
[java.util.ArrayDeque] (value [[]]) but failed to remove it when the web application was 
stopped. Threads are going to be renewed over time to try and avoid 
a probable memory leak.
```

**Comment by jorgheymans** [comment]
Issue can be closed, corresponding PR was merged.
