### ISSUE TITLE
Can you support Oracle？

### ISSUE THREAD

**Issue by limx198918** [openzipkin/brave#719]
Can you support Oracle drive

**Comment by adriancole** [comment]
directly we have no means to support oracle drivers, due at least to licensing (both linking and testing). You can try brave-p6spy. I'm not sure, but it is possible you can instrument client connections to oracle through that.

**Comment by limx198918** [comment]
Thank you. Can you give me an example? It's best to combine Zipkin

**Comment by adriancole** [comment]
the instructions are here
https://github.com/openzipkin/brave/tree/master/instrumentation/p6spy
