### ISSUE TITLE
@Suspended AsyncResponse loses child async client span after upgrading to 5.1.0

### ISSUE THREAD

**Issue by xihw** [openzipkin/brave#722]
This happens after I upgrading brave from 5.0.0 to 5.1.0. Generally, our use case is:

A resource method with getSomething(@Suspended AsyncResponse response, ...) signature, and inside the method, we make an async call to other service(we propagate trace context with wrap(callable)).
So we expect a server span and a client span and client span being the child of the server span.

However, after the upgrading, client span is disconnected from the server span.

I debug it locally and am able to locate where it breaks. It's this line:
https://github.com/openzipkin/brave/commit/e301ec3338d1f63d0185d35cc4e997a664b57c7d#diff-786c3cf4f7c96c394374144674cd860dR136

I fixed it by closing the scope in "RESOURCE_METHOD_FINISHED" for "isSuspendDeclared" resource matched event.

Can it be fixed soon ?

**Comment by adriancole** [comment]
CurrentTraceContextTest seems to cover this. can you please add a test that makes it fail?

**Comment by xihw** [comment]
Hi @adriancole I updated the issue description above.
I have not come up with a complete fix yet because mvn install fails due to some tests failure. I'm not very familiar with brave code base. I can look into it more, but it would great if you could help or point me a direction!

**Comment by adriancole** [comment]
@xihw if I do what you say, our tests fail because of the note in the comments, that it isn't reliable. What happens is the scope leaks. We need another signal to figure out if we should delay closing until RESOURCE_METHOD_FINISHED

**Comment by adriancole** [comment]
regardless of if you can get maven to work, can you get the test to run in the IDE? maybe you can paste an example.. possibly we can re-scope the context in this case.

**Comment by adriancole** [comment]
wait  I think I got it!
