### ISSUE TITLE
brave-instrumentation-dubbo-rpc maven not found

### ISSUE THREAD

**Issue by wengwh** [openzipkin/brave#724]
brave-instrumentation-dubbo-rpc maven not found

why not deploy maven?

When will it be deploy？

**Comment by adriancole** [comment]
I was able to download
http://search.maven.org/remotecontent?filepath=io/zipkin/brave/brave-instrumentation-dubbo-rpc/5.1.2/brave-instrumentation-dubbo-rpc-5.1.2.jar
just now. check your proxy?

**Comment by wengwh** [comment]
@adriancole  i see the jar ，thank you
