### ISSUE TITLE
Potential NPE in TracingAsyncListener#adaptResponse

### ISSUE THREAD

**Issue by felixbarny** [openzipkin/brave#729]
I'm currently also in the process of writing instrumentation for the async servlet stuff and noticed a potential bug in brave.

Because the request and response objects are not supplied when adding the `AsyncListener` to the `AsyncContext` here
https://github.com/openzipkin/brave/blob/49b91c05bf50c0837dfa26d6246e4d07cbdb8453/instrumentation/servlet/src/main/java/brave/servlet/ServletRuntime.java#L77

`AsyncEvent#getSuppliedRequest()` must return `null` per specification

> If the AsyncListener to which this AsyncEvent is being delivered was added using AsyncContext.addListener(AsyncListener, ServletRequest, ServletResponse), the returned ServletRequest will be the same as the one supplied to the above method. If the AsyncListener was added via AsyncContext.addListener(AsyncListener), this method must return null.

This can lead to NPEs here:
https://github.com/openzipkin/brave/blob/49b91c05bf50c0837dfa26d6246e4d07cbdb8453/instrumentation/servlet/src/main/java/brave/servlet/ServletRuntime.java#L121-L124

The funny thing is that most application servers don't actually implement it that way and are happy to return a request when calling `AsyncEvent#getSuppliedRequest()`, no matter how the `AsyncListener` is added. I think it was WebSphere in one specific version which actually implements this according to the spec. Can't remember which one that was but if you are interested I can find it out.

**Comment by adriancole** [comment]
thanks we'll sort it!

**Comment by adriancole** [comment]
fix https://github.com/openzipkin/brave/pull/738 cc also @nicmunroe

**Comment by nicmunroe** [comment]
@felixbarny @adriancole thanks for pointing this out and pinging me on it. Previously I wasn't doing anything that required the request or response, but now that I'm diving into the wonderful world of tagging this suddenly became relevant. I probably would have missed this otherwise, so thanks!
