### ISSUE TITLE
Test flake on CircleCI: brave.grpc.ITTracingServerInterceptor

### ISSUE THREAD

**Issue by shakuzen** [openzipkin/brave#733]
Not always, but sometimes the CircleCI build fails like below. There isn't much to go on, but I did notice that this test will try to get an unused port using `PickUnusedPort.get()`. I wonder if that has anything to do with the sudden kill signal.

```
[INFO] --- maven-failsafe-plugin:2.20.1:integration-test (integration-test) @ brave-instrumentation-grpc ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running brave.grpc.ITTracingClientInterceptor
02:44:36,797 INFO  [main] grpc.ITTracingClientInterceptor$2 (ITTracingClientInterceptor.java:265) [125bc4a5d9f89e99/125bc4a5d9f89e99] - in span!
[INFO] Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.251 s - in brave.grpc.ITTracingClientInterceptor
[INFO] Running brave.grpc.ITCensusInterop
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 11.513 s - in brave.grpc.ITCensusInterop
[INFO] Running brave.grpc.ITTracingServerInterceptor
Received 'killed' signal
```

First noticed as https://github.com/openzipkin/brave/pull/725#issuecomment-401588696; The most recent occurrence of this was https://circleci.com/gh/openzipkin/brave/1413

**Comment by adriancole** [comment]
sometimes kill is a timeout. sometimes not. #737 should show if it was blocked getting a span reported

**Comment by adriancole** [comment]
haven't seen this in a while, tho no more circleci either
