### ISSUE TITLE
When  I  try to use Zipkin   tracing the JDBC  statement，It  remind me this 

### ISSUE THREAD

**Issue by Sef135** [openzipkin/brave#735]
Could not open JPA EntityManager for transaction; nested exception is java.lang.NoSuchMethodError: com.twitter.zipkin.gen.Endpoint.builder()Lcom/twitter/zipkin/gen/Endpoint$Builder;

by the way , I can't find   the  document of "how to trace mysql database  sql"  , is there  an example  to show how to use Zipkin ?

**Comment by adriancole** [comment]
usually it is best to use gitter for questions like this: https://gitter.im/openzipkin/zipkin

here's a try to help. If you look at brave, there is mysql tracing available there: https://github.com/openzipkin/brave/tree/master/instrumentation/mysql6

Please ask more on gitter! thanks

**Comment by adriancole** [comment]
https://github.com/openzipkin/brave-webmvc-example is an overview as well, including basic usage of zipkin
