### ISSUE TITLE
TCP Server Request Tracing

### ISSUE THREAD

**Issue by TiMusBhardwaj** [openzipkin/brave#742]
Is there any instrumentation which could help me TCP Server instrumentation.?
I am new to tracing, still on my learning curve.
So any suggestion is welcome.

**Comment by adriancole** [comment]
usually we don't trace at TCP layer for reasons including amplification.
For example the trace data could get really big. Usually we would trace
layers over that, such as messaging or RPC.

**Comment by adriancole** [comment]
ya focus on the layer that defines what a request is. this could end up as
a server or consumer span depending on if rpc or messaging in nature

**Comment by jorgheymans** [comment]
Question answered, thanks !
