### ISSUE TITLE
Connect traceID to RequestID

### ISSUE THREAD

**Issue by JaryZhen** [openzipkin/brave#746]
As Tracing System such as openzipkin used in micro service, It is necessary to connect traceID to RequestID. For that, I can easily checkout the details in log through the trace id.
I do not know Is it worthwhile to do so. How do you think?

**Comment by adriancole** [comment]
most add a span tag of the request id for correlation.

**Comment by jeqo** [comment]
Closing as question is answered. For further discussion https://gitter.im/openzipkin/zipkin
