### ISSUE TITLE
Client Auth Injector

### ISSUE THREAD

**Issue by crisbodnar** [openzipkin/brave#750]
**Feature Request**
Currently, there is no support for authentication. Minimal support could be provided by exposing a way to inject access tokens into the HTTP requests of the AsyncReporter. The users can then use their own proxies in front of the Zipkin Backends to verify that token. In the current state, a proxy is also needed for the client to add the authentication header to the request which is inconvenient. 

I am happy to send a PR for this feature if there is agreement on it.

**Comment by adriancole** [comment]
in the zipkin-reporter-java project, where code about this lives, there is
an okhttp3 "sender" which can already be configured for client auth in
however you define this term.

**Comment by crisbodnar** [comment]
Thanks!

**Comment by ankur-jain1-hp** [comment]
@crisbodnar How did u adopted the auth?

**Comment by crisbodnar** [comment]
@ankur-jain1-hp The sender mentioned by @adriancole can be configured to include an auth token which can be checked by a proxy in front of the Zipkin backend.
