### ISSUE TITLE
Feature request: Upgrade Kafka Clients API to 2.0.0

### ISSUE THREAD

**Issue by jeqo** [openzipkin/brave#752]
Latest version of Apache Kafka breaks compatibility by removing support for Java 7 and adding more methods to Kafka Consumers, which make it fail when using Kafka Clients brave instrumentation (e.g. `poll(Duration timeout)` is not implemented by `TracingKafkaConsumer`.

Kafka Streams v2.0 includes support for headers that could enable instrumentation for tracing but this can be discussed in other issue once this issue is resolved.

**Comment by jeqo** [comment]
I have a working branch: https://github.com/jeqo/brave/tree/kafka-clients-v2 but requires `kafka-junit` to be upgraded also (https://github.com/charithe/kafka-junit/pull/38)

**Comment by jeqo** [comment]
kafka-junit has been upgraded now :) https://github.com/charithe/kafka-junit/pull/38

**Comment by ImFlog** [comment]
Agreed with Adrian, but from what I see in @jeqo branch, it is already done this way by not using @Override on new methods.
Waiting for the PR ;)

**Comment by jeqo** [comment]
There you go https://github.com/openzipkin/brave/pull/753/

**Comment by jeqo** [comment]
Closing as #753 got merged. Thanks for your help!
