### ISSUE TITLE
TracingInterceptor should not override explicitly set headers

### ISSUE THREAD

**Issue by jntakpe** [openzipkin/brave#776]
If the header is already set in Request.Builder the TracingInterceptor#Setter should not override the previously set header.

An implementation could be :

```java
  static final Setter<Request.Builder, String> SETTER = new Setter<Request.Builder, String>() {
    @Override public void put(Request.Builder carrier, String key, String value) {
            if (carrier.build().headers(key).isEmpty()) {
                carrier.header(key, value);
            }
    }

    @Override public String toString() {
      return "Request.Builder::header";
    }
  };
```

or for complex use cases maybe it could be nice to be able to customize the Setter object.

**Comment by adriancole** [comment]
the setter is only used for propagation. Why are you requesting this?
Multiple propagation header values with the same name will likely break
downstream receivers.

>

**Comment by adriancole** [comment]
So the setter is used to ensure that the current client span (the ids data about the client request is being recorded against), that this is also set as the parent.

If your question is about somehow writing the wrong id (meaning recording data in one id, yet propagating another), we need to talk this through as it will break everyone.

**Comment by adriancole** [comment]
feel free to reply here or join https://gitter.im/openzipkin/zipkin to chat more

Cheers!

**Comment by jntakpe** [comment]
Hi @adriancole I'm requesting this because I need to write some logic when propagating headers to OkHttp. Some instance, I need to add username to MDC, so I use ExtraFieldPropagation to retrieve field from headers and I parse the Authorization header and use a MDCScopeDecorator to decorate MDC. The issue is that sometime the Authorization header needs to be set manually and should not be propagated automatically. For instance, during tests in want to use a specific value and if the header is set manually I don't want to override it.

**Comment by adriancole** [comment]
interesting. I would suggest "Authorization" is not a good thing to put in ExtraFieldPropagation as it exports it in a way that isn't likely secure.

Instead you can consider using an http parser to get your client id (still using headers), and tag it on the span. If you need to put it in MDC, you could make a custom ScopeDecorator for that ex https://github.com/spring-cloud/spring-cloud-sleuth/blob/713544703a57d4a862ed1953c2ad0a45cab2ed0d/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/log/Slf4jScopeDecorator.java

At any rate, custom stuff that separates in-process propagation from external propagation is something that will eventually happen #577

**Comment by adriancole** [comment]
another crude way is to formalize the userId as separate from its authorization context. For example, if you set the extra field "user-id" based on the header "authorization" which it co-propagates redundantly, it is safer I'd suspect and also eliminates tracing from interfering with auth flows.. just a thought.

**Comment by jntakpe** [comment]
Yeah using a formal userId field a nice way to solve the issue. We discussed this solution internally but choose to go ahead with the previous solution

**Comment by jntakpe** [comment]
@adriancole regarding the solution you proposed I was stuck because the ScopeDecorator#decorateScope method only take as parameter the a TraceContext so I concluded that the only way I had to access the username was to put it in the extra variable.

Is there any chance you make the TracingInterceptor#SETTER field customizable ?
Adding a method :
`public static Interceptor create(HttpTracing httpTracing, Setter<Request.Builder, String> setter)` should made the trick.

**Comment by adriancole** [comment]
this is more a wander of a topic. I don't expect us to expose what you are asking for directly as we'd need to warantee against bugs created by folks. Meanwhile you can customize the propagation factory to intefere with setters, though we wouldn't support any bugs that are caused by this.

```java
@Override public <C> Injector<C> injector(Setter<C, K> setter) {
  // here the setter parameter is what we provide.. you can monkey with this at own risk
  return delegate.injector((carrier, key, value) -> {
    setter.put(carrier, key, value);
  });
}
```

**Comment by adriancole** [comment]
https://gitter.im/openzipkin/zipkin for more chat.. thanks!
