### ISSUE TITLE
How can I monitor other logical methods in execution in netty http tracing?

### ISSUE THREAD

**Issue by yanfch** [openzipkin/brave#780]
Now there is only one span in ui.

**Comment by adriancole** [comment]
if you are using `NettyHttpTracing` there's currently only a server handler available. When `fireChannelRead` is fired, a span will be current, which means that you can connect this to something downstream with `Tracer.currentSpan`. If `fireChannelRead` results in something run on a netty executor, you might need to wrap that with `Tracing.currentTraceContext()`.

In any case you probably need to describe what precisely you are doing. this netty instrumentation is very low level, there are other netty based tools like ratpack and armeria which have more complete instrumentation
