### ISSUE TITLE
Only optionally remove ExtraFieldPropagation headers from Kafka ConsumerRecords

### ISSUE THREAD

**Issue by timtebeek** [openzipkin/brave#783]
This was originally posted here, but determined to be related to Brave rather than Sleuth; https://github.com/spring-cloud/spring-cloud-sleuth/issues/1083
The sample project uses Sleuth, but it's reproducible with just Brave as well: https://github.com/timtebeek/sleuth-kafkalistener/commit/eb68995605abdb1d9051b15cc5415e80f6b37cc4#diff-5af0c09fe0d657e3c92157a3a2dd42edR38

Short summary is:
- I'm using a `@KafkaListener` & `@Header`
- when I use `ExtraFieldPropagation` to propagate the value of `@Header`
- then `KafkaTracing` removes the propagated header, leading to `@Header` to fail with:
- > `org.springframework.messaging.MessageHandlingException: Missing header 'corporate_trace_id' for method parameter type [class java.lang.String]`

The offending line is: https://github.com/openzipkin/brave/blob/master/instrumentation/kafka-clients/src/main/java/brave/kafka/clients/KafkaTracing.java#L143
which removes all propagated headers, including the extra propagated headers.

I'd like to be able to have Brave propagate my internal company headers, while still being able to access them with `@Header`. Can an exception be made configurable?

**Comment by adriancole** [comment]
The primary reason headers are removed is to avoid something downstream from re-processing the trace. `ExtraFieldPropagation` is a bolt-on which makes the relationship of headers a bit murky.

I agree we don't need to drop "extra fields" right now, only the trace IDs. Let me think about if there is an easy way to change this without breaking something else.

**Comment by adriancole** [comment]
PS I think this is more a bug than a feature request

**Comment by adriancole** [comment]
https://github.com/openzipkin/brave/pull/784 fixes this

**Comment by timtebeek** [comment]
Awesome! Thanks a lot for the quick work! Sounds perfect! :)
