### ISSUE TITLE
brave Jersey integration

### ISSUE THREAD

**Issue by tliuliaison** [openzipkin/brave#81]
I’m trying to integrate Brave into this Gradle template https://github.com/Netflix/gradle-template/blob/master/build.gradle, and having trouble with some of the Spring and Jersey integration, I added Spring DispatcherServlet with brave package on the context path in web.xml; added SpanCollector and TracerFilters configuration class in source. When I ran it, I got a bunch of "Rejected bean name" in the trace:
org.springframework.web.servlet.mvc.annotation.DefaultAnnotationHandlerMapping - Rejected bean name 'org.springframework.context.annotation.internalConfigurationAnnotationProcessor': no URL paths identified
09:57:58.201 [Daemon] DEBUG org.springframework.web.servlet.mvc.annotation.DefaultAnnotationHandlerMapping - Rejected bean name 'org.springframework.context.annotation.internalAutowiredAnnotationProcessor': no URL paths identified
09:57:58.201 [Daemon] DEBUG org.springframework.web.servlet.mvc.annotation.DefaultAnnotationHandlerMapping - Rejected bean name 'org.springframework.context.annotation.internalRequiredAnnotationProcessor': no URL paths identified
09:57:58.202 [Daemon] DEBUG org.springframework.web.servlet.mvc.annotation.DefaultAnnotationHandlerMapping - Rejected bean name 'org.springframework.context.annotation.internalCommonAnnotationProcessor': no URL paths identified
09:57:58.203 [Daemon] DEBUG org.springframework.web.servlet.mvc.annotation.DefaultAnnotationHandlerMapping - Rejected bean name 'spanCollectorConfiguration': no URL paths identified
09:57:58.204 [Daemon] DEBUG org.springframework.web.servlet.mvc.annotation.DefaultAnnotationHandlerMapping - Rejected bean name 'traceFiltersConfiguration': no URL paths identified

**Comment by kristofa** [comment]
The jersey implementation was contributed by @henrikno. I never used it myself. So it would be good if he could help you out.

**Comment by kristofa** [comment]
@tliuliaison were you able to make progress on this one?
Based on [this StackOverflow post](http://stackoverflow.com/questions/2576939/spring-rejecting-bean-name-no-url-paths-specified) it looks like it has to do with your Spring configuration.

If no updates I'll close it.

**Comment by tliuliaison** [comment]
I ended up not using Spring. Please close it.

Thanks
Ting
