### ISSUE TITLE
[Bug] Spring Rabbit - Trace context is lost in ErrorHandler

### ISSUE THREAD

**Issue by skastenholz** [openzipkin/brave#815]
Hi, 

I am using Brave 4.19.3 and the Spring Rabbit instrumentation. Due to functional requirements I implemented a custom `org.springframework.amqp.rabbit.listener.ConditionalRejectingErrorHandler` in order to handle message conversion exceptions and registerred it at the `org.springframework.amqp.rabbit.config.SimpleRabbitListenerContainerFactory` instance:
```
@Override
public void handleError(Throwable t) {
	if (t instanceof ListenerExecutionFailedException
		&& ExceptionUtils.indexOfThrowable(t, MessageConversionException.class) != -1) {
		// business logic without trace context
		throw new ImmediateAcknowledgeAmqpException(t);
	} else {
		super.handleError(t);
	}
}
```
Also the later is decorated with `brave.spring.rabbit.TracingRabbitListenerAdvice` by following https://github.com/openzipkin/brave/tree/master/instrumentation/spring-rabbit#message-consumer.

The test scenario is as follows: An unparseable message is sent and because of the occuring message conversion exception the custom ConditionalRejectingErrorHandler is invoked. Before that the TracingRabbitListenerAdvice injected the trace context. However, at the point the ConditionalRejectingErrorHandler is called the trace context is not set: `brave.Tracing.current().currentTraceContext().get()` returns null while debugging the above code snippet. My expectation would be, that the trace context is available in the ConditionalRejectingErrorHandler.

In a first analysis I found out that TracingRabbitListenerAdvice and ConditionalRejectingErrorHandler are invoked in the same thread. Therefore, I conclude it should not be a threading issue.

Do I have got the right assumptions and do you have got some hints how to investigate the issue further?

Thank you very much in advance!

**Comment by adriancole** [comment]
sorry if this is a bug to explore it would be best to reproduce it in `ITSpringRabbitTracing` also the version mentioned is very old. to talk more please use gitter https://gitter.im/openzipkin/zipkin
