### ISSUE TITLE
[help] How write trace json into log file with log4j

### ISSUE THREAD

**Issue by GreedyPirate** [openzipkin/brave#817]
i intend to use LoggingReporter which use jul to log span
```
static final Logger logger = Logger.getLogger(Tracer.class.getName());
//....
enum LoggingReporter implements Reporter<zipkin2.Span> {
  INSTANCE;
  @Override public void report(Span span) {
	// jul logger
    logger.info(span.toString());
  }
}
```

i want to write `span.toString to` a log file, log collector, like flume will collect, and  i followed [brave-webmvc-example](https://github.com/openzipkin/brave-webmvc-example/blob/master/webmvc4/pom.xml), and configure log4j.xml like this 

```
<appender name="zipkinFile" class="org.apache.log4j.DailyRollingFileAppender">
      <param name="File" value="${user.home}/logs/zipkin.log" />
      <param name="Encoding" value="UTF-8" />
      <param name="Append" value="true" />
<layout class="org.apache.log4j.PatternLayout">
   <param name="ConversionPattern" value="%m%n"/>
</layout>
  </appender>

  <!-- zipkin trace logger -->
  <logger name="brave.Tracer" additivity="false">
      <level value="INFO" />
      <appender-ref ref="zipkinFile" />
  </logger>
  <root>
  	  <appender-ref ref="zipkinFile" />
  </root>
```

however there are some irrelevant log instead of trace logs, just println on IDEA console, catalina log window

**Comment by adriancole** [comment]
the log reporter you see is just for play like demo. Usually people use https://github.com/openzipkin/zipkin-reporter-java

If you really need your json in logs you can make a version of the same with your own logger. You'll notice it is very little code.
