### ISSUE TITLE
Mongo Java Driver instrumentation

### ISSUE THREAD

**Issue by shakuzen** [openzipkin/brave#818]
MongoDB client instrumentation was recently [requested on Gitter](https://gitter.im/openzipkin/zipkin?at=5bd6e26ac08b8b30678e2b1d), and my department would benefit from having this as well, since we use MongoDB as a data store for some of our applications.

We also use Sleuth, so if it supported Spring Data in general (as was requested in https://github.com/spring-cloud/spring-cloud-sleuth/issues/788) or Spring Data MongoDB, that would work too. Brave, I think, will want to instrument the driver itself so it can be used outside Spring applications.

Mongo Java Driver: https://mongodb.github.io/mongo-java-driver/
Spring Data MongoDB: https://spring.io/projects/spring-data-mongodb

**Comment by rekaparathalwar** [comment]
👍

**Comment by adriancole** [comment]
@koji do you have anything for this? ;)

**Comment by adriancole** [comment]
sorry I meant @kojilin

**Comment by kojilin** [comment]
Not yet. AFAIK Currently mongo driver's CommandListener is called by mongo driver's thread, so I think that's why we still modify driver directly or wrap span start/finish outside mongo.
