### ISSUE TITLE
Consider adding "traceSampled" field to our default logging stuff

### ISSUE THREAD

**Issue by adriancole** [openzipkin/brave#821]
I helped review the census specs done by @sebright and think they are good. https://github.com/census-instrumentation/opencensus-specs/blob/master/trace/LogCorrelation.md

They match what we add to the logging context, adding 'traceSampled' which is boolean. I know sleuth has a similar value and it is helpful to know if a trace query is likely to work (even if you have secondary firehose reporting this can be a false negative).

Should we add it? Should we add it by default? One problem is we already add "traceId" "spanId" and "parentId" and each adds cost https://github.com/openzipkin/brave/blob/master/brave/src/main/java/brave/internal/propagation/CorrelationFieldScopeDecorator.java

I've long thought that "parentId" is the least valuable as this only helps in scenarios where you are literally recreating traces in your logging system (correlation only needs "parentId" "spanId"). Still some folks only use the "traceId".

I would like some input about people using logging expressions in real life and if they use "parentId" and if they would use "traceSampled" or not.

**Comment by bigmac44** [comment]
We'd use the traceSampled if only to keep our log format the same between microservices that use spring sleuth (which adds the appName, traceId, spanId, and exported values to the default logging expression) and other applications that use sleuth directly.

**Comment by adriancole** [comment]
I'll go ahead and add this. Using the term "sampled" as we use it consistently everywhere and "traceSampled" nowhere. This makes documentation and code linking most consistent.

**Comment by adriancole** [comment]
hmm one issue is we haven't decided if "true" or "false" is the correct value for this, considering b3 is 1 or 0. We need to think this through more.

**Comment by b-devinssuresh-cvet** [comment]
I would also use this. I have an app that can't use sleuth that would use this to keep our logs in line
