### ISSUE TITLE
LookupKey not used in PendingSpans any longer?

### ISSUE THREAD

**Issue by tutufool** [openzipkin/brave#822]
Starting from 5.3.2, I see LookupKey not be used for lookup.
Instead, the TraceContext will be used directly as lookup key which should work according to the impl of RealKey.

Does that mean we can safely remove internal class LookupKey?

I got a little confused when tracking the code from 4.X to 5.X :)

**Comment by adriancole** [comment]
this was attempt to use less allocations. I think there is still lookup key
needed to avoid instantiating a trace context just to find your parent.

**Comment by tutufool** [comment]
However, I didn't see any code reference on LookupKey except for test case.

and the getOrCreate() method call below directly:

PendingSpan result = delegate.get(context);

**Comment by adriancole** [comment]
if that is true.. possible! delete it and run the build except without that
test case. might be dead code.

if so please pull request

**Comment by tutufool** [comment]
OK, I'll do the PR

**Comment by tutufool** [comment]
Hi, Adrian

I still feel we should use LookupKey for get and remove operation.

Otherwise, when hash collision happens, we're actually comparing with TraceContext instance and RealKey instance which will ever equal to each other.

See:
https://github.com/openzipkin/brave/blob/release-5.1.4/brave/src/main/java/brave/internal/recorder/PendingSpanRecords.java#L189

And ConcurrentHashMap: line 940:
if ((ek = e.key) == key || (ek != null && **key.equals(ek)**))


From my understanding:
"equals" of RealKey: serves for "put" operation.
"equals" of LookupKey: serves for "get" and "remove" operation.

Could you double check it?

And here's comments for Lookup key:

/**
   * Lookup keys are cheaper than real keys as reference tracking is not involved. We cannot use
   * {@linkplain TraceContext} directly as a lookup key, as even though it has the same hash code as
   * the real key, it would fail in equals comparison.
   */

**Comment by adriancole** [comment]
@tutufool the order is controlled which is why this test passes. You can look at the equals impl in LookupKey https://github.com/openzipkin/brave/blob/30440de855fb69ecae2f95a5f74f3cbe74285347/brave/src/test/java/brave/internal/recorder/PendingSpansTest.java#L74

Probably best to try to get a test to fail, then there's something to change

**Comment by tutufool** [comment]
My fault and you're right.

I saw some of the "equals" logic has been moved from lookupKey to TraceContext itself.

old:
https://github.com/openzipkin/brave/blob/release-5.1.4/brave/src/main/java/brave/propagation/TraceContext.java#L276

new:
https://github.com/openzipkin/brave/blob/release-5.5.0/brave/src/main/java/brave/propagation/TraceContext.java#L420

Sorry about that!

**Comment by adriancole** [comment]
yeah that was a hack to save an allocation I think :P I'm glad you are becoming an internals expert.. we can use more!

**Comment by adriancole** [comment]
is this issue still needed?

**Comment by tutufool** [comment]
Not needed, close it.

**Comment by adriancole** [comment]
@tutufool PS are you interested in doing a site doc for us? Right now, we don't have anyone in china and I think it would help people to relate. You have a lot of experience, so maybe your site is also interesting :) https://cwiki.apache.org/confluence/display/ZIPKIN/Sites

you can chat with me on gitter if you like as well

**Comment by tutufool** [comment]
just ping you on gitter
