### ISSUE TITLE
Add "http.url" tag to HTTP client generated spans

### ISSUE THREAD

**Issue by AurelienPassion** [openzipkin/brave#827]
Hi.

I would like to add a default "http.url" tag on spans generated by HTTP client instrumentation with the requested URL.

This information is very useful when calling "external" applications.

This is simple and I should issue a pull request soon.

Aurélien

**Comment by adriancole** [comment]
made notes on your pull request. next time, chat with us on gitter first ok? sorry about the effort you spent. https://gitter.im/openzipkin/zipkin
