### ISSUE TITLE
Extra propagated Kafka Header converted to byte[] value

### ISSUE THREAD

**Issue by timtebeek** [openzipkin/brave#829]
Hi! A while ago I posted https://github.com/openzipkin/brave/issues/783 where extra propagated headers with Apache Kafka were not available for use in something like: 
```java
    @KafkaListener(topics = "demo-topic2", groupId = "demo-group2")
    public void listen(@Header("corporate_trace_id") String corporateTraceId){ ... }
```
This was thankfully resolved and proven to work when unpacking Kafka headers; as demonstrated here: https://github.com/timtebeek/sleuth-kafkalistener/blob/master/src/test/java/com/github/timtebeek/sleuth/kafkalistener/TracingKafkaListenerTest.java#L77

However, when adding a web controller before the kafka send (mostly because I'm unsure how else to have Brave adopt my header value in a test), my Kafka header value is suddenly converted to a String containing a list of number, comma separated, that together make up the `byte[]` that corresponds to my header value. So `abc` becomes `65,66,67`.

Demonstrated here: https://github.com/timtebeek/sleuth-kafkalistener/commit/70f79de5dd9f26c9c65934bb9d8bd56716d34704

Sorry for the possibly confusing test setup; this matches my actual use and demonstrates the issue; I'm unsure how to create a fully minimal test that replicates the same.

Can you have a look and possibly direct me to a workaround/fix?

**Comment by adriancole** [comment]
spring-kafka is a layer above kafka, which brave instruments. At kafka's layer of abstraction, there are only byte array values. So, you would expect to always see byte arrays.

spring-kafka is a variant of spring-messaging which allows users to configure `KafkaHeaderMapper` which can convert byte arrays to something else. In your demo, this type ends up as `DefaultKafkaHeaderMapper` (invoked by `MessagingMessageConverter`.. both in spring-kafka), which has no special handling for the key "corporate_trace_id".

I don't know why that's the case, but in any rate it isn't something the kafka client layer which is the only thing defined in brave can affect. You might want to ask spring-kafka support for more advice.

**Comment by timtebeek** [comment]
In case anyone stumbles upon this in the future; It's been fixed in Spring Kafka 2.2:
https://github.com/spring-projects/spring-kafka/commit/214316839b2e309151094301016e7fd66d2c08c4

**Comment by garyrussell** [comment]
Just to close this out...

@timtebeek  when you previously set the header yourself...

```java
    public void testHeadersNotStripped() throws Exception {
        String corporateTraceId = UUID.randomUUID().toString();
        Message<String> message = MessageBuilder
                .withPayload("bar")
                .setHeader(KafkaHeaders.TOPIC, Constants.TOPIC2)
                .setHeader(CORPORATE_TRACE_ID, corporateTraceId)
                .build();
        template.send(message);
        await().untilAsserted(() -> assertThat(listener.getMessageTraces().get("bar")).isNotNull());
        TraceDiagnostics traceDiagnostics = listener.getMessageTraces().get("bar");
        assertThat(traceDiagnostics.getCorporateTraceId()).isEqualTo(corporateTraceId);
    }
```

The template uses a message converter, and a `DefaultKafkaHeaderMapper` to map the headers. This mapper converts all the headers to JSON; it also adds an additional header `spring_json_header_types` which is a (JSON) map of header names to header types. On the receiving side, the headers are converted back to their original types. Any headers that don't appear in the name:type map are left as `byte[]`. Hence the change in behavior you saw. The 2.2 version performs a conversion when it sees the `@Header` parameter is of type `String`.

**Comment by adriancole** [comment]
nice loopback on this folks! well done
