### ISSUE TITLE
ZipkinSpanCollector via corporate proxy

### ISSUE THREAD

**Issue by rhart** [openzipkin/brave#84]
Sorry for asking questions via an issue but I couldn't find a mailing list or forum to ask on.

I'm using ZipkinSpanCollector to submit spans to a Zipkin Collector, but I need to go via a corporate proxy.  Do you have any idea where I can set the proxy settings?  I've had a look at `ZipkinCollectorClientProvider` which creates a `TSocket` but can't see anything obvious.  My Thrift knowledge is more than a little lacking

**Comment by kristofa** [comment]
Hi @rhart, I just found out that there is a `TSocket` constructor which takes a `java.net.Socket`.  And a `java.net.Socket` has a constructor that allows configuring a proxy.  So I would guess that is the way to go.

Currently this is indeed not configurable when instantiating `ZipkinSpanCollector`. I would advise you to try to change the `ZipkinSpanCollectorParams` class to add proxy host + port config entries and next support those in `ZipkinCollectorClientProvider`.  

If this works for you it would be great if you can contribute the changes via a pr.

**Comment by rhart** [comment]
Sure, happy to submit a PR.  

Trying this out but I think my corporate proxy is not supporting socks.  I'm trying to find out for sure and get that opened up.  When it's working I'll submit what I have.

**Comment by kristofa** [comment]
@rhart no progress on this one?
If no answer I'll close it. A pr is always welcome at a later stage.

**Comment by rhart** [comment]
Sorry for keeping this hanging around.  I'm still battling to get socks supported on my corporate proxy.  I'll close the issue and submit a PR when I've confirmed my change works.
