### ISSUE TITLE
Provide `remoteServiceName` and `remoteIpAndPort` in SpanCustomizer

### ISSUE THREAD

**Issue by ScienJus** [openzipkin/brave#840]
What kind of issue is this?

 - [x] Feature Request.

In my case, i have implemented the service discovery via java sdk, then i want to setting the remote service of the client call in HttpClientParser and GrpcClientParser.

I found that Span already supports `remoteServiceName` and `remoteIpAndPort` after https://github.com/openzipkin/brave/pull/747/commits/97ecf2f79bdfc07b6fff6e6458dce7edd30ddef2, is it possible to provide the same method in SpanCustomizer?

**Comment by adriancole** [comment]
for now use `tracer.currentSpan()` Though I think we will add the ability to change the remote service name I'm not sure if you will get better IP/port info than we already give..

**Comment by adriancole** [comment]
Another workaround is FinishedSpanHandler as you can change any data there

**Comment by ScienJus** [comment]
Ok, I have added some extra tags via `HttpClientParser`/`GrpcClientParser` before, so I would think that I can also handle `remoteEndpoint` here. I will try the solution you said.
