### ISSUE TITLE
about dubbo support?

### ISSUE THREAD

**Issue by 1991wangliang** [openzipkin/brave#848]
是不是目前 brave-instrumentation-dubbo-rpc还不支持通过ExtraFieldPropagation传参？

**Comment by adriancole** [comment]
ExtraFieldPropagation is added in the Tracing object, not dubbo directly. So, if you configure it there, dubbo should take it. I think dubbo gets Tracing object from `ExtensionFactory` or spring.

Please come to gitter for more questions https://gitter.im/openzipkin/zipkin

**Comment by 1991wangliang** [comment]
i was created ExtensionFactory and created spring bean of Tracing.but i get params was null. that's my coding.https://github.com/1991wangliang/sleuth-webmvc-example
