### ISSUE TITLE
HttpClientRequestAdapter sends sampled header through as true/false rather than 0/1

### ISSUE THREAD

**Issue by wjam** [openzipkin/brave#85]
As commented in commit b71d7434399c4b77e8ee4dc45715553ca5782711, the sampled header should be 0 or 1 rather than true or false for it to be compatible with the Zipkin spec.

In `com.github.kristofa.brave.http.HttpClientRequestAdapter`, the sampled header gets set to true or false rather than 0 or 1.

**Comment by adriancole** [comment]
care to raise a pull request with a fix and a test case?

**Comment by kristofa** [comment]
This is merged. Closing.
