### ISSUE TITLE
NoSuchMethodError: zipkin2.Endpoint$Builder.port(I)Lzipkin2/Endpoint$Builder

### ISSUE THREAD

**Issue by shl1988012** [openzipkin/brave#855]
I am using spring-cloud-sleuth-zipkin with spring boot. when I start my service, it occer error:
Error creating bean with name 'tracer' defined in class path resource [com/cisco/oneidentity/common/boot/tracing/sleuth/TracingConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [brave.Tracer]: Factory method 'tracer' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tracing' defined in class path resource [com/cisco/oneidentity/common/boot/tracing/sleuth/TracingConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [brave.Tracing]: Factory method 'tracing' threw exception; nested exception is java.lang.NoSuchMethodError: zipkin2.Endpoint$Builder.port(I)Lzipkin2/Endpoint$Builder.

my dependencies:
`<parent>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-parent</artifactId>
	<version>2.1.1.RELEASE</version>
	<relativePath />
</parent>`
`<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-starter-sleuth</artifactId>
	<version>2.0.2.RELEASE</version>
</dependency>`
`<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-sleuth-zipkin</artifactId>
	<version>2.0.2.RELEASE</version>
</dependency>`
`<dependency>
	<groupId>io.zipkin.brave</groupId>
	<artifactId>brave</artifactId>
	<version>5.5.0</version>
</dependency>`
`<dependency>
	<groupId>io.zipkin.reporter2</groupId>
	<artifactId>zipkin-sender-okhttp3</artifactId>
	<version>2.7.12</version>
</dependency>`

AND my tracingConfig 

`@Bean
    public Tracing tracing(){
        return Tracing.newBuilder().localServiceName("zipkin_test")
                .spanReporter(sender()).build();
    }

    @Bean
    public AsyncReporter sender(){
        Sender sender = OkHttpSender.create("http://localhost:9441");
        return  AsyncReporter.create(sender);
    }`

could u help me solve this problem? thanks a lot @adriancole

**Comment by devinsba** [comment]
This issue probably belongs in Sleuths issue tracker, but I know one of the answers you will receive is that Sleuth 2.0 is not compatible with Boot 2.1
