### ISSUE TITLE
disable report json into catalina log

### ISSUE THREAD

**Issue by deepakshivanandappa** [openzipkin/brave#858]
hello everyone!! 
We recently adopted OpenZipkin/Brave library into our application - our application is a Spring based web application ( not on Spring Boot yet ) ;
We are not taking advantage of complete OpenZipkin/Brave implementation, we are only leveraging its parentId and traceId to log for tracing calls between multiple services; We are not interested in reporting part of OpenZipkin; So with that, we are seeing for each individual Http request call a Report - JSON getting logged into tomcat's Catalina.out - we dont need this report Json printing into catalina log as its creating a lot of I/Os and memory - any suggestions, how to tune or avoid that reporting json not log ?

**Comment by adriancole** [comment]
spanReporter(Reporter.NOOP) if I am not mistaken
