### ISSUE TITLE
[BUG][brave-instrumentation-jms] removes existing message properties (OracleAQ)

### ISSUE THREAD

**Issue by nomeez** [openzipkin/brave#860]
Hi there
I did a trial with brave-instrumentation-jms in my spring-boot app which uses Oracle AQ as JMS Implementation.
When I send a message, the b3 tracing header is submitted to the db successfully. But all other message properties I set, where gone.
What I found, was when sending the message the message properties are filtered and there is an exception in https://github.com/openzipkin/brave/blob/master/instrumentation/jms/src/main/java/brave/jms/PropertyFilter.java#L86 when setting the properties again.

oracle.jms.AQjmsException
JMS-110: Property JMSXDeliveryCount not writable

I guess JMSXDeliveryCount  is an oracle specific message property, which can't be modified on client side at all. I've read the comment in the code, with the link to the jms documentation, and I wonder if it is really necessary to clearProperties() before I can set new ones. Or if this ist just true on the consumer side.

**Comment by adriancole** [comment]
this bit was about the JMS spec itself which iirc says you have to replace
all properties on mutation. it seems there is a spec or interpretation gap.

we should prioritize a solution that isnt special cased for Oracle
explicitly. perhaps a "leave alone" list of message properties?

**Comment by nomeez** [comment]
A "leave alone" list was also my first idea, But I think that would not work, as clearProperties() would not respect that list.

[[JMS Spec: Message Properties Section](https://docs.oracle.com/javaee/6/api/javax/jms/Message.html)]
"_When a client receives a message, its properties are in read-only mode. If a client attempts to set properties at this point, a MessageNotWriteableException is thrown. If clearProperties is called, the properties can now be both read from and written to._"

My interpretation of this is, that this is only relevant when consuming a message.

I kind of question the whole filtering part for existing B3 Message Properties, when we produce a new message anyway. But I probably don't have the big picture here.

**Comment by adriancole** [comment]
iiuc you suggest that when sending a message we don't clear, right? (basically only clear on incoming message, not outbound)

**Comment by adriancole** [comment]
PS we should cross-reference with apache camel, I think, as some logic we decided was similar to theirs.

**Comment by MikeWinter** [comment]
This may not be specific to OracleAQ: I'm seeing lost properties using Spring Cloud Sleuth (for instrumentation) operating over ActiveMQ. In this case, properties are lost on byte-oriented messages, but not text messages, due in part to the clearing and re-adding of those properties.

If you feel it warrants it, I'm happy to open a separate issue. That said, from what I can see, this may be a problem with how the Apache ActiveMQ client library handles writing properties when the message body is read-only.

**Comment by adriancole** [comment]
can you enlist someone in camel like @WillemJiang to help? I can't imagine they don't have this problem. Basically, if there's some heuristic that is spec conventional, that's easy for us to do here. What's not we can try to make possible.

I think above you mentioned something earlier then I asked "when sending a message we don't clear, right?" For example, if the spec is different about what we do receiving a message vs clearing it, I think we could make a change like that.. however, if that still doesn't help the oracle case (ex if the problem also exists in receiving messages), then we may have to look at our code (which was derived from camel ) to see if it is an error in interpretation in our side... a problem on both sides, and considering whatever that is, how to move forward.

Can you help clarify? we are in the middle of ASF move so it is easier for me to review concrete proposals that don't special case a vendor library, vs something that would require trying self etc.

**Comment by WillemJiang** [comment]
In the camel world when we deal with the jms message, we have to do some [transformation](https://github.com/apache/camel/blob/master/components/camel-jms/src/main/java/org/apache/camel/component/jms/DefaultJmsKeyFormatStrategy.java) between the message header key and JMS properties. I'm not sure if it relates to the issue that you hit.

**Comment by Stmated** [comment]
Any update on this? What are the workarounds? To use an ActiveMQTextMessage instead with Base64 body?
I am thinking of cloning the code and writing a fix, but I am afraid that any fix would involve reading and writing the whole byte array, essentially holding it twice in memory, making it quite inefficient.

**Comment by adriancole** [comment]
can anyone give a test case that fails? this will help.

from above:
```
iiuc you suggest that when sending a message we don't clear, right? (basically only clear on incoming message, not outbound)
```

I want to make sure the approach discussed is valid so knowing workaround good, but even more important is to recreate the problem. I think we all want to get out of bouncing-ball mode. right now just need a way besides me doing shotgun code.

**Comment by adriancole** [comment]
@Stmated to try to make this into action.. is it ActiveMQStreamsMessage or ActiveMQBytesMessage you are working around with the ActiveMQTextMessage. Is it safe to assume the workaround is on the send side, and it is on the receive side that you get problems?

basically if someone can turn description to code, I'd be happy to help

**Comment by adriancole** [comment]
@WillemJiang PS this is the topic here https://github.com/apache/camel/blob/b9a3117f19dd19abd2ea8b789c42c3e86fe4c488/components/camel-jms/src/main/java/org/apache/camel/component/jms/JmsMessageHelper.java#L56

I think @jeqo and I spoke about if we only use idempotent header formats (ex b3 single) there's not much risk anyway as you are literally overwriting and then there's no clear (such as you might need if restarting a trace with normal B3, as you'd have to unset the parent ID)

**Comment by adriancole** [comment]
I'm actually ok with shotgun after having looked at this closely. We are saved by the bell because our injected format is single-header anyway. We currently know a couple people get busted. Worst case, we bust others, and then they roll back and we hear from them.

https://github.com/openzipkin/brave/pull/965

**Comment by adriancole** [comment]
going out in 5.6.11

**Comment by nomeez** [comment]
Sorry for the epic delay, but I only now found time to update my projects to the latest library und verify the whole thing with my setup. I can confirm it works now and no headers get lost anymore.
Thanks for the awesome work.

**Comment by adriancole** [comment]
epic thanks for the loopback and letting us know!
