### ISSUE TITLE
Renaming Kafka/JMS Tracing Headers

### ISSUE THREAD

**Issue by ryan-beckett** [openzipkin/brave#861]
Hi, I have a functional requirement to rename the trace header field names, (i.e. X-B3-TraceId => trcId), is there an eloquent way of doing this. I'm posting this here as I've haven't gotten an answer on StackOverflow. Our solution for JMS was to port the Sleuth code supporting JMS and gutting the rest. We're thinking of doing this for Kafka, but only as I last resort. Any thoughts?

**Comment by adriancole** [comment]
Tracing takes a Propagation.Factory which is how these things are
controlled. It will affect kafka as well.

If it is not special to kafka you would make something like our B3 one. If
it is special to kafka you'd make a decorating variant. when it returns an
injector or extractor.. you would check the type of the carrier and handle
accordingly. Ex if the carrier is a kafka one you do something different.

https://github.com/openzipkin/brave/blob/master/brave/src/main/java/brave/propagation/Propagation.java#L114

**Comment by ryan-beckett** [comment]
Thanks for your response Adrian. I settled on decorating my Kafka Producer/Consumer using a delegate pattern. Luckily, my decorator gets called after TracingProducer and before TracingConsumer, allowing me to modify the key names.
