### ISSUE TITLE
grpc instrumentation error

### ISSUE THREAD

**Issue by oburgosm** [openzipkin/brave#862]
When an error occurs in a grpc service, the span is not finished correctly.

It's related with this issue: https://github.com/grpc/grpc-java/issues/1552

The solution could be something like this, in class `brave.grpc.TracingServerInterceptor#ScopingServerCallListener`:

```
@Override public void onHalfClose() {
      SpanInScope scope = tracer.withSpanInScope(span);
      try { // retrolambda can't resolve this try/finally
          delegate().onHalfClose();
      } catch (RuntimeException | Error e) {
          span.error(e);
          span.finish();
          throw e;
      }  finally {
        scope.close();
      }
}
```

**Comment by devinsba** [comment]
Makes sense to me and the impl looks ok from a quick look. Would you have time to throw that in a PR with a unit test?
