### ISSUE TITLE
[BUG][brave-instrumentation-httpclient] TracingCachingHttpClientBuilder breaks http client caching

### ISSUE THREAD

**Issue by amccarthy-atlas** [openzipkin/brave#864]
TracingCachingHttpClientBuilder's override of decorateMainExec fails to add a CacheExecution to the http client execution chain. This prevents http caching from working.

Here is a [Wiremock](https://mvnrepository.com/artifact/com.github.tomakehurst/wiremock/2.20.0) test that reproduces the issue:

```java
public class TracingCachingHttpClientBuilderTest extends ITHttp {

    @Rule
    public WireMockRule wireMockRule = new WireMockRule();

    private HttpTracing httpTracing= HttpTracing.create(tracingBuilder(Sampler.NEVER_SAMPLE).build());

    // Tracing builder breaks caching:
    @Test 
    public void tracingCachingHttpClientShouldCacheResponse() throws Exception {
        String path = "/test/123";
        HttpClient httpClient = new TracingCachingHttpClientBuilder(httpTracing).build();

        stubFor(get(urlEqualTo(path))
                .willReturn(aResponse()
                        .withStatus(200)
                        .withHeader("Content-Type", "text/plain")
                        .withHeader("Cache-Control", "max-age=600, stale-while-revalidate=1200")
                        .withBody("Hello")));

        HttpGet httpGet = new HttpGet("http://localhost:8080" + path);

        httpClient.execute(httpGet);
        httpClient.execute(httpGet);

        verify(exactly(1), getRequestedFor(urlEqualTo(path)));
    }

    //Vanilla Apache builder is ok.
    @Test
    public void cachingHttpClientShouldCacheResponse() throws Exception {
        String path = "/test/123";
        HttpClient httpClient = CachingHttpClients.createMemoryBound();

        stubFor(get(urlEqualTo(path))
                .willReturn(aResponse()
                        .withStatus(200)
                        .withHeader("Content-Type", "text/plain")
                        .withHeader("Cache-Control", "max-age=600, stale-while-revalidate=1200")
                        .withBody("Hello")));

        HttpGet httpGet = new HttpGet("http://localhost:8080" + path);
        httpClient.execute(httpGet);
        httpClient.execute(httpGet);

        verify(exactly(1), getRequestedFor(urlEqualTo(path)));
    }
}
```

A simple fix like:

`return new TracingMainExec(httpTracing, super.decorateMainExec(exec));`

will lead to a span being started even when the request is served from the cache. If that's not desirable, then you'll probably need to subclass TracingMainExec, and avoid sending a span if HttpCacheContext.CACHE_RESPONSE_STATUS = CACHE_HIT.

**Comment by devinsba** [comment]
Hi @amccarthy-atlas, this is an interesting find! Would you be able to spike a PR with your proposed fix and those tests included? Thanks

**Comment by amccarthy-atlas** [comment]
Sure. What should we do if the response is served from the client's cache? Some options:

1. Add a tag, e.g. http.served_from_client_cache=true/false, that indicates that the response was served from the cache
2. Create a regular http client span (i.e. no cache tag)
3. Do not create a span

IMHO option 1 has the most utility. What rule do the other integrations follow?

**Comment by adriancole** [comment]
I would create a child span but not mark it as a client span (kind = CLIENT)

**Comment by amccarthy-atlas** [comment]
What is the rationale for not setting the kind to Client? Is it because there is an expectation that every (successful) Client span has a corresponding Server span? 

If the kind shouldn't be client, then what should it be? None of the others seem to fit. In the existing flow, TracingProtocolExec calls tracer.nextSpan(), which will create a new child span if a trace already exists - **is this the child span that you were referring to?** If so, then the HttpClientHandler will set the kind to Client at the same time as it starts the span. The kind cannot be set to null again at some point in the future (e.g. because we discovered that the response was served from the cache).

**Comment by adriancole** [comment]
client is a remote span. span.kind clarifies the remote endpoint. so it
wouldnt make sense to pretend something we know is served locally is
actually remote.

it is possible that the code needs to be refactored to accommodate this.

**Comment by adriancole** [comment]
the implementation wasn't obvious so I spiked one here https://github.com/openzipkin/brave/pull/865
