### ISSUE TITLE
Question About rabbitmq instrumentation

### ISSUE THREAD

**Issue by wuyupengwoaini** [openzipkin/brave#870]
https://github.com/openzipkin/brave/blob/f1313e4d30176587df6b583830039f90e72baf78/instrumentation/spring-rabbit/src/main/java/brave/spring/rabbit/TracingMessagePostProcessor.java#L38-L63

I view the source and find TracingMessagePostProcessor is one of the beforePublishPostProcessors in RabbitTemplate  and it execute before send message .So the start and end time is the same,so the message 
send span's duration is always  zero ,so I think it shuold not ommit the time of sending message beacuase of the network time.

So,I want to know why it does so?  Is it a bug or there is something that I don not know?

**Comment by adriancole** [comment]
for modeling purpose we always create a CONSUMER span separate from any
processing one. CONSUMER is different than SERVER as in messaging transit
can be quite long and also multiple  consumers can process same message.
The duration of a CONSUMER is supposed to be time spent pulling off wire
etc. with this library we dont know how long poll took so we fake it. There
is some games also played here to ensure the same clock instance is used
for the consumer and listener span.

**Comment by wuyupengwoaini** [comment]
It is the logic part of PRODUCER instead of CONSUMER,so I really can not get you

**Comment by adriancole** [comment]
easier to do question/answer in chat https://gitter.im/openzipkin/zipkin let's move there please
