### ISSUE TITLE
HTTP response with 1xx status gets error tag 

### ISSUE THREAD

**Issue by dkroehan** [openzipkin/brave#874]
Hi!

I use Zipkin in a Websocket API and stumbled over the issue that a server response with http status code **101** is falsely tagged as error.

The issue occurs in the handshake request in which the server responds with
`HTTP/1.1 101 Switching Protocols
`
For an example, see: https://en.wikipedia.org/wiki/WebSocket#Protocol_handshake

The issue is in `brave.http.HttpParser`:
```
  @Nullable String maybeStatusAsString(int statusCode, int upperRange) {
    if (statusCode != 0 && (statusCode < 200 || statusCode > upperRange)) {
      return String.valueOf(statusCode);
    }
    return null;
  }
```

The Javadoc states the current behaviour and recommends overriding the method. 
In my opinion the implementation should take into account the **HTTP/1.1** spec of **Informational 1xx** status codes.

I fixed it in my project by using the following HttpServerParser implementation:

```
public class ErrorHttpServerParser extends HttpServerParser {

    @Override
    protected void error(Integer httpStatus, Throwable error, SpanCustomizer customizer) {
        if (error != null) {
            errorParser().error(error, customizer);
        } else if (httpStatus != null && isErrorStatus(httpStatus)) {
            customizer.tag("error", String.valueOf(httpStatus));
        }
    }
    
    private boolean isErrorStatus(int statusCode) {
        //statusCode may be 0 (implies absent value), see {@link brave.http.HttpParser}.
        return statusCode == 0 || statusCode >= 300;
    }
}
```

**Comment by adriancole** [comment]
you are right. originally, we only recorded http.status_code when it was non-success or info. Looks like we made a mistake and conflated that classification into error. will fix right away as it will cause a damaging amount of false errors even if people can override it particularly in upgrade cases like http/2 etc.

**Comment by adriancole** [comment]
going out immediately as 5.6.3 Thanks for the detailed report
