### ISSUE TITLE
End-to-end doc/example

### ISSUE THREAD

**Issue by adriancole** [openzipkin/brave#89]
It would be great to have an example that fully configures brave against a zipkin collector. For example, given a zipkin collector running via docker or something, the README of `brave-zipkin-spancollector` would show how you use and verify it, or we'd have an end-to-end example that does that.

cc @benidroe

**Comment by adriancole** [comment]
This would be an alternative to looking up lines in source files like https://github.com/openzipkin/brave/blob/master/brave-zipkin-spancollector/src/main/java/com/github/kristofa/brave/zipkin/ZipkinSpanCollector.java#L62 and https://github.com/openzipkin/brave/blob/master/brave-core/src/main/java/com/github/kristofa/brave/Brave.java#L55

**Comment by kristofa** [comment]
Indeed a good idea. I'll try to get something up and running soon.

**Comment by leonlibraries** [comment]
I'm looking forward to

**Comment by adriancole** [comment]
https://github.com/openzipkin/brave-resteasy-example is pretty close, I think

**Comment by adriancole** [comment]
if it isn't, please log an issue there or here with what would make it better!
