### ISSUE TITLE
how to start a new child span in another thread to send http request with restTemplate

### ISSUE THREAD

**Issue by Xuguozong** [openzipkin/brave#891]
I used follow codes to start a new child span in another thread to send http request with restTemplate,restTemplate was configured in the TracingConfiguration class. But the traces in the zipkin seem not correct.
     
      @Override
      public void run() {
          try {
                Span newSpan = null;
                try(Tracer.SpanInScope spanInScope = tracing.tracer().withSpanInScope(span)) {
                      newSpan = tracing.tracer().nextSpan().name("another thread span");
                      restTemplate.getForObject(endpoint, String.class);
          } finally {
              if (newSpan != null){
                  newSpan.finish();
              }
          }
      }
  }

--------------
restTemplate was configurated in TracingConfiguration.java, it seems the new thread started a new trace to call the http request rather than inherited the outter thread's trace context.

**Comment by adriancole** [comment]
best way is to use ScopedSpan exactly like this example https://github.com/openzipkin/brave/tree/master/brave#in-process-tracing

We don't do support with github issues so please use gitter for follow-up questions Thanks! https://gitter.im/openzipkin/zipkin

**Comment by Xuguozong** [comment]
ok,thank you!
