### ISSUE TITLE
if brave-instrumentation-mysql support Database Connection Pool

### ISSUE THREAD

**Issue by xiepeng-github** [openzipkin/brave#909]
when I use liberty to config jndi Database Connection Pool。i dont know where to config ?statementInterceptors=brave.mysql.TracingStatementInterceptor&zipkinServiceName=myDatabaseService。
if brave-instrumentation-mysql support Database Connection Pool

**Comment by adriancole** [comment]
this configure is in the jdbc url. please use gitter for more questions https://gitter.im/openzipkin/zipkin
