### ISSUE TITLE
com.github.kristofa.brave.spring.ServletHandlerInterceptor ignores X-B3-Sampled header with value "1"

### ISSUE THREAD

**Issue by oliver-schoenherr** [openzipkin/brave#91]
Since Version 3.0.0-rc-1 the brave Clients sends "1" instead of "true" as value of X-B3-Sampled, but the ServletHandlerInterceptor does not enabled tracing for this requests.

**Comment by kristofa** [comment]
@oliver-schoenherr Thanks for reporting! I'l try to change that code to use the new interceptors instead of using `ServerTracer` before making the 3.0.0 release. This will avoid code duplication.

You can off course also submit a pr for this! :)
