### ISSUE TITLE
Span not reporting http status 200 ok for successful api request

### ISSUE THREAD

**Issue by virendraagarwal** [openzipkin/brave#919]
We are using Brave API for Tracing.
We found one issue when a API request is successful its span data does not include http.status_code tag as 200 in case of error it is tagging the error.

After debugging this method returns null in case status code is between 200 to 399
Class Name : HttpParser

@Nullable String maybeStatusAsString(int statusCode, int upperRange) {
    if (statusCode != 0 && (statusCode < 200 || statusCode > upperRange)) {
      return String.valueOf(statusCode);
    }
    return null;
  }

Upper range hardcoded as 299 for success and 399 for error 
Looks like an issue as multiple status codes will be missing through this implementation.
Can you explain it in detail.

Thanks

**Comment by adriancole** [comment]
hi! incidentally you must be using an older version of brave as that code has changed. Can you verify you still have a concern?

https://github.com/apache/incubator-zipkin-brave/blob/master/instrumentation/http/src/main/java/brave/http/HttpParser.java#L160

**Comment by virendraagarwal** [comment]
@adriancole we are at version 5.6.1 and i see code is same in both versions could you please point me changes in two files to me it looks like that only error code are mentioned in status 
this is the comment in 5.6.3 
/** The intent of this is to by default add "http.status_code", when not a success code */

**Comment by adriancole** [comment]
@virendraagarwal there are a lot of comments in this code. as we use issues for changes to the code, and gitter for q/a.. is it possible for you to move this conversation to chat? that would reduce the amount of email notifications followers of this repo receive.

https://gitter.im/openzipkin/zipkin
