### ISSUE TITLE
Id conversion from long to hex in headers

### ISSUE THREAD

**Issue by pbetkier** [openzipkin/brave#92]
`HttpServerRequestAdapter`, with `HttpClientRequestAdapter` and `ServletHandlerInterceptor` doing the other way round, represents ids (longs) as strings when putting them into headers by transforming them into hex strings. The javadoc for `IdConversion` explains that it's for compatibility with zipkin / finagle. Do you know the reason behind designing the communication protocol this way in those technologies, transforming to hex strings even though they do keep ids as longs in their internal structures?

As a user of brave alone I see it as a minor inconvenience – it may result in wtfs for unaware people trying to manually send requests with trace headers or viewing request headers during debugging.

What do you think of making the conversion customizable? We could introduce an interface for id conversion with its default implementation being the zipkin compatible one. Brave clients not requiring such compatibility could provide their implementation, e.g. doing a direct conversion without hex mapping, in brave builder.

If you agree this idea is worth extending the brave API then I could prepare a PR for this feature.

**Comment by kristofa** [comment]
I'm not sure why this conversion is done to be honest but it was indeed introduced in brave for compatibility reasons. 

Also, `zipkin-web` currently uses the hex encoded trace ids. For example to access a specific trace the url looks like: `.../traces/f876506975d9b522?serviceName=name`. So if you use `zipkin-web` it might be worth sticking to the hex encoded ids to improve interoperability and also log the hex encoded ids in your application?

I prefer to stick to the 'zipkin compatible way' for now. I agree that if we talk about next iterations of the  tracing specification as part of the openzipkin initiative we should put the hex encoding in question. 

By the way: in which technology stack are you integrating brave? Do you use one of the existing integrations or are you writing a new one?

**Comment by eirslett** [comment]
Hex is shorter to encode in ascii, while long is shorter to encode in binary. I guess that's why.
If you use the firebug plugin, the trace encoding will be done for you.

**Comment by adriancole** [comment]
Zipkin's web process reads the ids as longs and converts them to hex,
probably to be copy/pasteable. Ops guides tend to say copy/paste the id
from the header into the UI. I recall @jpinner mentioning that longs cause
confusion as they can be negative and sometimes people lose time when they
don't copy the negative sign.

**Comment by pbetkier** [comment]
Oh, I wasn't aware that `zipkin-web` uses hex representation as well, I thought it uses longs and wanted to be consistent with it. It does make perfect sense to expose ids as hex in headers and logs then. Hex is indeed easier for humans to work with.

@kristofa We're integrating brave for Spring and for JAX-RS currently. We're using our own integrations though since we had them already – we used them for correlation ids and tracing with brave is simply a step forward for us. Maintaining our own integrations makes such evolutions more or less transparent for our developers. So we're only using `brave-core` and `brave-http` right now, and just starting with `brave-zipkin-spancollector`.

**Comment by kristofa** [comment]
@eirslett @adriancole Thanks for the additional input!
@pbetkier Thanks for the background info. I'll close this issue.
