### ISSUE TITLE
brave-instrumentation-p6spy : avoid some span to be exportable

### ISSUE THREAD

**Issue by chsi13** [openzipkin/brave#932]
Hi.

I trace db statements with p6spy and spring cloud sleuth. It exports connection , query and fetch spans...Is it possible to only export to zipkin query statements ???

**Comment by adriancole** [comment]
this is possible in latest release. please use gitter for questions next time!

https://github.com/openzipkin/brave/tree/master/instrumentation/p6spy#filtering-spans
