### ISSUE TITLE
Handling retries in async apache http client

### ISSUE THREAD

**Issue by RestfulBlue** [openzipkin/brave#948]
Hey there, currently we was using instumentation for apache async http client. it works just fine, but lately we was starting using it with some secured endpoint. In such case client at first perform request without credentials, which will emit span with 401. After client get 401, he send additional request with credentials, and second request has 200 status code. But sadly - only first one is reported by instrumentation :( 

I think this problem will also be reproduced if one of the retries strategies will be used

**Comment by adriancole** [comment]
each http request should be a new span (with different span IDs). Right
now, our instrumentation tests don't cover things with follow-up requests.
This includes implicit retries and redirect handling. I know @llinder is
working on a related topic in ratpack-zipkin

**Comment by RestfulBlue** [comment]
ok, thanks! wrapped apache client and make it work :)
