### ISSUE TITLE
http request specific propagation

### ISSUE THREAD

**Issue by adriancole** [openzipkin/brave#949]
While setting up propagation per request is more expensive in terms of overhead, having the option to can be helpful.

For example, this could...
* prevent adding headers on outbound requests known to be uninstrumented (ex elasticsearch or health checks)
* change the header format of specific outbound (ex use b3 everywhere except into the cloud)
* prevent propagation of extra fields when the outbound request is to a semi-trusted party (trusted on trace ID, but not user ID)

An example impl could be HttpTracing.clientPropagation which employ the http adapter to make generic decisions on which mechanism to use ex based on `httpAdapter.path(request)`

When I mention there is more overhead, what I mean is that how we select which propagation mechanism is appropriate could mean reading headers or other data which could allocate strings along the way. Moreover, the Injector objects take resources to make, and we may not always be able to cache the computation result. Even if we did that could be lock causing and cause more code (as we have no dependencies). However, a careful design could be made for common cases such as muting etc.

cc @openzipkin/brave @kojilin

**Comment by adriancole** [comment]
this could also be used for sites who dont use log correlation. when that is the case they can propagate down b3=0 instead of the full trace id string. I think once netflix asked about this

**Comment by anuraaga** [comment]
As a user, I've always found it unintuitive, yet understandable, that no-op still propagates some overhead. Keeping it at the minimum of `b3=0` seems great.

**Comment by adriancole** [comment]
In 5.8, this can be done via a custom PropagationFactory. all HTTP instrumentation have standard `HttpServerRequest` and `HttpClientRequest` types. This means you can make your own `Injector<HttpClientRequest>` and do what you want with it, including masking properties.
