### ISSUE TITLE
Implement tracing for KafkaStream#flatMap

### ISSUE THREAD

**Issue by AlexPiermatteo** [openzipkin/brave#952]
Hi guys, first of all thank you very much for you work since it makes the tracing of our Kafka Stream application way simpler to implement and it works great :)
I'm just struggling now to find a nice way to track some work I do inside a `.flatMap` transformation in Kafka Stream. 

**Example Scenario**
I Basically would like to have something like that:
```
 final KStream<Object, SpecificRecord>[] branchedStreams = builder.<Object, GenericRecord>stream(sourceTopic)
        .transform(kafkaStreamsTracing.flatMap(("myFlatMap", (k, v) -> ...))
        //some other stuff maybe..
        .branch(predicates);
```

Unfortunately you support "only" transformation like `map/peek/filter/foreach` but no 'flatMap'..is it there a reason for it? could it be implemented in case?

Thank you very much in advance :)

**Comment by jeqo** [comment]
@AlexPiermatteo thanks!

Currently we support the latest `flatTransform()` [introduced in Kafka Streams 2.2.0](https://www.apache.org/dist/kafka/2.2.0/javadoc/org/apache/kafka/streams/kstream/KStream.html#flatTransform-org.apache.kafka.streams.kstream.TransformerSupplier-java.lang.String...-)

You can check and example of how to use it here: https://github.com/openzipkin/brave/blob/master/instrumentation/kafka-streams/src/test/java/brave/kafka/streams/ITKafkaStreamsTracing.java#L703-L705

Let us know if this fit in your use-case.

**Comment by AlexPiermatteo** [comment]
Hi @jeqo!! thank you very much for the fast answer :) 
Yes this is exactly what I needed :D, somehow I fully missed those examples in the tests about the `flatTransform()`.

**Comment by jeqo** [comment]
Thanks @AlexPiermatteo I'll be closing the issue now.

**Comment by jcchavezs** [comment]
@AlexPiermatteo did you sort your problem out?
