### ISSUE TITLE
when i use brave-instrumentation-dubbo-rpc, i find some error

### ISSUE THREAD

**Issue by zhaojigang** [openzipkin/brave#953]
## Describe the Bug
hi, when i use brave-instrumentation-dubbo-rpc, i find some error.
there is my demo: [https://github.com/zhaojigang/dubbo-demo](https://github.com/zhaojigang/dubbo-demo)

* dubbo-demo-provider implements DemoService
* dubbo-demo-provider2 implements  HelloService
* dubbo-demo-consumer invoke DemoService and HelloService one by one

i think this invoke only can generate one traceId, but two.

![image](https://user-images.githubusercontent.com/14085645/61939321-94b7c380-afc5-11e9-977b-b97f147a2915.png)

**Comment by zhaojigang** [comment]
and dependency picture is incorrect
![image](https://user-images.githubusercontent.com/14085645/61939685-5f5fa580-afc6-11e9-9763-0c3170a71051.png)

**Comment by adriancole** [comment]
I would recommend using log integration such as brave-context-slf4j to narrow down the problem. For example, looking at the client and server logs with trace/span ids may make it easier to diagnose vs running a demo. We have unit tests in this project, if there's a bug, they would need to be expressed as a unit test eventually.

please join https://gitter.im/openzipkin/zipkin to do troubleshooting as we don't do troubleshooting in issues. If there's a bug that would have a fix in this repo, we can re-open this.
