### ISSUE TITLE
if set spring.sleuth.enabled=false, my spring boot can't work

### ISSUE THREAD

**Issue by VitZhou** [openzipkin/brave#954]
## Describe the Bug
The following candidates were found but could not be injected:
	- Bean method 'springRabbitTracing' in 'TraceMessagingAutoConfiguration.SleuthRabbitConfiguration' not loaded because @ConditionalOnProperty (spring.sleuth.messaging.rabbit.enabled) found different value in property 'spring.sleuth.messaging.rabbit.enabled'
	- Bean method 'springRabbitTracing' in 'TraceMessagingAutoConfiguration.SleuthRabbitConfiguration' not loaded because Ancestor org.springframework.cloud.sleuth.instrument.messaging.TraceMessagingAutoConfiguration did not match

**Comment by adriancole** [comment]
this project isn't sleuth. please try their chat https://gitter.im/spring-cloud/spring-cloud-sleuth
