### ISSUE TITLE
Kafka Streams extra field propagation

### ISSUE THREAD

**Issue by timtebeek** [openzipkin/brave#956]
**Feature:**
I'd like to use `ExtraFieldPropagation` with Kafka Streams, (mostly) to set field values based on message details, such that they become available in Zipkin and our log MDC (through Sleuth).

**Rational**
`ExtraFieldPropagation` is part of Brave, and I could see other users expecting this to work.

**Example Scenario**
Without this integration one can attempt to set extra fields, but they are not propagated yet. This is somewhat confusing and unexpected. My unsuccessful attempts thus far had used:
```java
KStream<String, String> numbersStream = builder.stream("numbers");
numbersStream.transformValues(kafkaStreamsTracing.peek("set", (k, v) -> {
	ExtraFieldPropagation.set(tracer.currentSpan().context(), "messageid", v);
	log.info("set for {} -> {}", k, v);
}))
.transformValues(kafkaStreamsTracing.peek("get", (k, v) -> {
	String value = ExtraFieldPropagation.get(tracer.currentSpan().context(), "messageid");
	log.info("got: {} for {} -> {}", value, k, v);
}));
```
But this results in the following log lines:
```
[kafka-streams-log-correlation,08516934550150511522640890549786,a1856e8c1acf9d47,true] 31504 \
    --- [-StreamThread-1] StreamsConfig: set for extra-propagation-IjD0xhR0ld -> 7
[kafka-streams-log-correlation,08516934550150511522640890549786,4cd66730012a3af8,true] 31504 \
    --- [-StreamThread-1] StreamsConfig: got: null for extra-propagation-IjD0xhR0ld -> 7
```
You'll notice that both log lines are from separate spans; with the extra field set in the first not present when retrieved in the second span.

I've thus far been unable to work this into a clean unit test for Brave; I hope it's clear what I'm trying to achieve.

**Prior Art**
 * Instrumentation at present through https://github.com/openzipkin/brave/tree/master/instrumentation/kafka-streams

**Comment by timtebeek** [comment]
@jeqo since you've been involved with writing the Kafka client/streams instrumentation, I hope you're able to weigh in here. Not sure if I should be doing/expecting anything else.

**Comment by jeqo** [comment]
thanks @timtebeek for starting this! 

Currently processors/transformers spans are child's of span created by initial consumer.

Haven't thought about this before but we could actually inject context as we leave each processor/transformer and create a parent/child dependency between their sequence; I will experiment with this in a following PR.

**Comment by timtebeek** [comment]
Awesome! Thanks for the quick work; #957 looks promising!
Not sure if I can contribute much, but really appreciate the work! :)

**Comment by jeqo** [comment]
@timtebeek thanks! could you test your Sleuth app against the PR to double check is covering your use-case?

**Comment by timtebeek** [comment]
@jeqo Confirmed to work in https://github.com/timtebeek/kafka-streams-log-correlation/pull/8 (nevermind the Travis test failures; it lacks the SNAPSHOT dependency). Locally it works like a charm, many thanks!
