### ISSUE TITLE
May be a memory leak

### ISSUE THREAD

**Issue by linmingchang** [openzipkin/brave#962]
## brave.propagation.TraceContext object use too much memory
it is my jmap analyse
![image](https://user-images.githubusercontent.com/18035905/63070147-9af9e980-bf4c-11e9-9ffc-cffaaf7eeefe.png)

## Steps to Reproduce
1. in production environment
2. occasionally triggered

**Comment by adriancole** [comment]
this might be a bit misleading as there are weak references to the
TraceContext cleaned up at GC time. This allows apis to re-use the same
context until GC. This is handled in the PendingSpans type.

**Comment by adriancole** [comment]
not a professional at these tools, but if you want to validate what I say,
you can look for a roots query in jhat. sorry don't know the whole
instructions to do this, but here's a link
https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/tooldescr012.html

**Comment by adriancole** [comment]
interestingly I see 10 million span in scope instances. If they are just awaiting collection that's one thing. I think you need to query what hard references there are. span in scope should not hang around as in almost all cases should be closed inside same method as they are opened.

**Comment by adriancole** [comment]
if SpanInScope not closed, this would certainly cause a memory leak, so check your code doesn't leak these.

**Comment by linmingchang** [comment]
> if SpanInScope not closed, this would certainly cause a memory leak, so check your code doesn't leak these.

thx. i will check my code later

**Comment by adriancole** [comment]
cool feel free to chat here also as back/forth in issue can spam people https://gitter.im/openzipkin/zipkin

**Comment by linmingchang** [comment]
> cool feel free to chat here also as back/forth in issue can spam people https://gitter.im/openzipkin/zipkin

ok , This is very good
