### ISSUE TITLE
Cannot set "b3" on a BytesMessage with body set to read-only (ActiveMQ 5.x)

### ISSUE THREAD

**Issue by adriancole** [openzipkin/brave#967]
Currently, we propagate the current trace ID back onto a message after consumption as the property "b3". The reason is that there is no stack relationship with the consumer. In other words, the consumer happens later and we need some way of handling this. The simplest way is to overwrite the "b3" header with the current trace context.

The problem is that in JMS BytesMessage (as implemented in ActiveMQ 5.x), setting the property results in an exception like this.

```
javax.jms.MessageNotWriteableException: Message body is read-only
	at org.apache.activemq.command.ActiveMQMessage.checkReadOnlyBody(ActiveMQMessage.java:746) ~[activemq-client-5.15.9.jar:5.15.9]
	at org.apache.activemq.command.ActiveMQBytesMessage.initializeWriting(ActiveMQBytesMessage.java:834) ~[activemq-client-5.15.9.jar:5.15.9]
	at org.apache.activemq.command.ActiveMQBytesMessage.setObjectProperty(ActiveMQBytesMessage.java:917) ~[activemq-client-5.15.9.jar:5.15.9]
	at org.apache.activemq.command.ActiveMQMessage.setStringProperty(ActiveMQMessage.java:735) ~[activemq-client-5.15.9.jar:5.15.9]
```

Eventhough we don't propagate this exception it is a failure in so far as now any consumer of this message will restart a new trace.

We have to investigate heuristics to use in this case, possible co-propagation via a weak key map on message, or some other mechanism. Another option is to acknowledge it won't work.

Thanks @Liodene for noticing.

**Comment by adriancole** [comment]
I added failing tests here for when this topic resumes https://github.com/openzipkin/brave/pull/966

**Comment by jeqo** [comment]
Seems like a bug on `BytesMessage` to me: https://github.com/apache/activemq/blob/master/activemq-client/src/main/java/org/apache/activemq/command/ActiveMQBytesMessage.java#L833 `initializeWriting` is called on `setProperty`, validating if body is readOnly, not properties; different from `ActiveMQMessage` https://github.com/apache/activemq/blob/master/activemq-client/src/main/java/org/apache/activemq/command/ActiveMQMessage.java#L487 which actually only check if properties are read-only.

Not sure if this is completely right, but we could open an issue on ActiveMQ about this and document its breaking support for `BytesMessage` with ActiveMQ.

Thinking out loud: would re-using `correlationId` provided by JMS instead of String property make sense? I know it could be already used, but seems we can overwrite it at any point, and the semantics could match.

**Comment by adriancole** [comment]
> Thinking out loud: would re-using correlationId provided by JMS instead of String property make sense? I know it could be already used, but seems we can overwrite it at any point, and the semantics could match.

I don't think the semantics match and we would likely get into a tricky spot where we parse failing due to conflation..

**Comment by adriancole** [comment]
yes I mean it is possibly just a bug. As originally mentioned by @Liodene, this is not broken in artemis eventhough it is when using the same JMS 1 api.

I refined the error to show precisely the one use case broken, which many will be able to avoid I think, by using listeners.
https://github.com/openzipkin/brave/pull/968

**Comment by adriancole** [comment]
next step on this issue: find/raise bug on activemq 5.x as it is very widely used still

**Comment by adriancole** [comment]
logging used to diagnose this going out in 5.6.11

**Comment by jeqo** [comment]
Found this related issue from +10 years ago: https://issues.apache.org/jira/browse/AMQ-1457

**Comment by jeqo** [comment]
Created the following issue to hopefully get some help from ActiveMQ community: https://issues.apache.org/jira/browse/AMQ-7291

**Comment by frederic-kneier** [comment]
Commented on the subject at https://issues.apache.org/jira/browse/AMQ-7291. In my case checking if writing of properties is possible before clearing them would help

**Comment by me3x** [comment]
Even if it is issue of ActiveMQ it will take some time to fix and clearing all properties isn't very nice behaviour. We should try to support current version. 

PR: https://github.com/openzipkin/brave/pull/1042

**Comment by jeqo** [comment]
https://issues.apache.org/jira/browse/AMQ-7291 issue is resolved. I've tried to run failing test with version 5.16.0-SNAPSHOT and is passing. Would be viable to say that jms instrumentation for `BytesMessage`s with activemq-client is only supported from versions 5.15.12/5.16.0 onwards?

**Comment by adriancole** [comment]
We can certainly add a notes section to the README. We probably have some odd things about servlet runtimes we don't document either.

**Comment by jeqo** [comment]
Cool. I'll be waiting for activemq release to bump versions, add notes, and close this one.

**Comment by adriancole** [comment]
will be in next release. Thanks @jeqo!
