### ISSUE TITLE
Spring Cloud Sleuth incompatible with Brave's Kafaka Instumentation

### ISSUE THREAD

**Issue by msmsimondean** [openzipkin/brave#969]
## Describe the Bug
The bug is related to Brave's Kafka instrumentation.  When producing Kafka messages with Spring Cloud Sleuth, Spring JSONifies the B3 headers that get added to the Kafka message.  When consuming these messages with Brave's Kafka instrumentation or Brave's Kafka Streams instrumentation. For example, the `X-B3-Sampled` header has a value of `"1"` instead of `1` the `X-B3-TraceId` header has a value of `"5d5e68b48c8c725b37ce966d36fdeb82"` instead of `5d5e68b48c8c725b37ce966d36fdeb82` etc.  Brave doesn't expect these B3 headers to be JSONified and so fails to parse them, and starts a new trace instead of joining the existing trace.  F

## Steps to Reproduce
See issue https://github.com/spring-cloud/spring-cloud-sleuth/issues/1430 and the accompanying https://github.com/msmsimondean/kafka-tracing example codebase that includes a producer app and a consumer app.  

## Expected Behaviour
Expected behavour is to be able to use Spring Cloud Sleuth when producing Kafka messages and to use  Brave's Kafaka Instumentation to consume those messages.

**Comment by adriancole** [comment]
please only open issues where the problems are. This codebase properly implements https://github.com/openzipkin/b3-propagation

jsonification has never been a supported option. The best route is to have the regression fixed at its source (Spring Cloud Stream Binder Kafka) vs expecting here and all the other places to accept invalid format
