### ISSUE TITLE
add TracingCustomizer, HttpTracingCustomizer, and in future MessagingTracingCustomizer

### ISSUE THREAD

**Issue by adriancole** [openzipkin/brave#973]
In dependency injection such as spring boot (cc @marcingrzejszczak),  guice/dropwizard (cc @jplock) and dagger (cc @anuraaga), there is a common pattern for sharing changes to a builder. `XCustomizer`. This allows decoupling of configuration, where a combination of user and framework change sets can combine.

This also, and importantly in the case of @lambcode's recent issue #970, allows you to change some configuration that has no "hole punched yet" in the configuration layer. For example, if we added a new method on Tracing.Builder, otherwise you have an immediate wrestling match about which versions of the config layer need to immediately update.

I suggest we package java 6 bytecode compatible add TracingCustomizer, HttpTracingCustomizer, and in future MessagingTracingCustomizer interfaces, which are a function of their respective builders. This will allow anything as early as spring 2.5 to immediately take advantage of any new changes allowed by brave, reducing tension on feature normalization.

cc'ing a few usual suspects also @devinsba @shakuzen @jeqo @llinder

**Comment by adriancole** [comment]
probably less obvious is this also really reduces complexity of trying new features. you could build brave off a branch and not need to patch a layer like sleuth also to facilitate a change.. or overwrite the entire tracing object.

**Comment by marcingrzejszczak** [comment]
> I like it. Seems like a good way to allow brave to grow past sleuth and enable our power users to benefit from new work before it can make it into a release

And Sleuth will be able to get it out of the box. I like it :)
